//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2300
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.1.4322.2300.
// 

using System;
using System.ComponentModel;
using System.Configuration;
using System.Diagnostics;
using System.Net;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

namespace PatientAccess.Services.DocumentManagement 
{
    /// <remarks/>
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [WebServiceBinding(Name="DocumentServiceSoapBinding", Namespace="http://vi.webservices.tenethealth.com")]
    [SoapInclude(typeof(NonCashDocument))]
    [SoapInclude(typeof(FaxDocument))]
    [SoapInclude(typeof(CashDocument))]
	[Serializable]
    public class DocumentServiceService : SoapHttpClientProtocol 
    {
        protected override WebRequest GetWebRequest( Uri uri )
        {
            HttpWebRequest webRequest = (HttpWebRequest)base.GetWebRequest( uri );

            if( ConfigurationManager.AppSettings["WEB_REQUEST_DEFAULTS"] != null
                && !bool.Parse( ConfigurationManager.AppSettings["WEB_REQUEST_DEFAULTS"] ) )
            {
                webRequest.KeepAlive = bool.Parse( ConfigurationManager.AppSettings["WEB_REQUEST_KEEP_ALIVE"] );
                webRequest.ProtocolVersion = new Version( ConfigurationManager.AppSettings["WEB_REQUEST_PROTOCOL_VERSION"] );
            }

            return webRequest;
        }
        
        /// <remarks/>
        public DocumentServiceService() 
        {
            string urlSetting = ConfigurationManager.AppSettings["viServiceUrl"];
            if ((urlSetting != null)) 
            {
                this.Url = urlSetting;
            }
            else 
            {
                this.Url = "http://dvld.tenethealth.com:8060/viwebserv/services/DocumentService";
            }
        }
        
        /// <remarks/>
        [SoapRpcMethod("", RequestNamespace="http://vi.webservices.tenethealth.com", ResponseNamespace="http://vi.webservices.tenethealth.com")]
        [return: SoapElement("findDocumentsForReturn")]
        public DocumentListResponse findDocumentsFor(DocumentListRequest dlReq) 
        {
            object[] results = this.Invoke("findDocumentsFor", new object[] {
                                                                                dlReq});
            return ((DocumentListResponse)(results[0]));
        }
        
        /// <remarks/>
        public IAsyncResult BeginfindDocumentsFor(DocumentListRequest dlReq, AsyncCallback callback, object asyncState) 
        {
            return this.BeginInvoke("findDocumentsFor", new object[] {
                                                                         dlReq}, callback, asyncState);
        }
        
        /// <remarks/>
        public DocumentListResponse EndfindDocumentsFor(IAsyncResult asyncResult) 
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((DocumentListResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [SoapType("DocumentListRequest", "urn:DocumentService")]
	[Serializable]
    public class DocumentListRequest 
    {
        
        /// <remarks/>
        public string accountNumber;
        
        /// <remarks/>
        public string appGUID;
        
        /// <remarks/>
        public string appKEY;
        
        /// <remarks/>
        public string hospitalServiceCode;
        
        /// <remarks/>
        public string medicalRecordNumber;
    }
    
    /// <remarks/>
    [SoapType("NonCashDocument", "urn:DocumentService")]
	[Serializable]
    public class NonCashDocument 
    {
        
        /// <remarks/>
        public string amount;
        
        /// <remarks/>
        public string checkBatchNumber;
        
        /// <remarks/>
        public DateTime documentDate;
        
        /// <remarks/>
        public string documentId;
        
        /// <remarks/>
        public string documentType;
        
        /// <remarks/>
        public string patientName;
        
        /// <remarks/>
        public string payorName;
    }
    
    /// <remarks/>
    [SoapType("FaxDocument", "urn:DocumentService")]
	[Serializable]
    public class FaxDocument 
    {
        
        /// <remarks/>
        public string accountNumber;
        
        /// <remarks/>
        public DateTime documentDate;
        
        /// <remarks/>
        public string documentId;
        
        /// <remarks/>
        public string documentType;
        
        /// <remarks/>
        public string faxGUID;
        
        /// <remarks/>
        public string mrNumber;
    }
    
    /// <remarks/>
    [SoapType("CashDocument", "urn:DocumentService")]
	[Serializable]
    public class CashDocument 
    {
        
        /// <remarks/>
        public string amount;
        
        /// <remarks/>
        public string checkBatchNumber;
        
        /// <remarks/>
        public DateTime documentDate;
        
        /// <remarks/>
        public string documentId;
        
        /// <remarks/>
        public string documentType;
        
        /// <remarks/>
        public string patientName;
        
        /// <remarks/>
        public string payorName;
    }
    
    /// <remarks/>
    [SoapType("Account", "urn:DocumentService")]
	[Serializable]
    public class Account 
    {
        
        /// <remarks/>
        public string accountNumber;
        
        /// <remarks/>
        public CashDocument[] cashDocuments;
        
        /// <remarks/>
        public FaxDocument[] faxDocuments;
        
        /// <remarks/>
        public string hspCode;
        
        /// <remarks/>
        public NonCashDocument[] nonCashDocuments;
    }
    
    /// <remarks/>
    [SoapType("DocumentListResponse", "urn:DocumentService")]
	[Serializable]
    public class DocumentListResponse 
    {
        
        /// <remarks/>
        public Account account;
        
        /// <remarks/>
        public bool documentsWereFound;
    }
}
