//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace PatientAccess.BenefitsValidationFusProxy {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BenefitsValidationFusServiceSEIBinding", Namespace="urn:BenefitsValidationFusService/wsdl")]
    public partial class BenefitsValidationFusService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback dropFusNoteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BenefitsValidationFusService() {
            this.Url = global::PatientAccess.Properties.Settings.Default.PatientAccess_AppServer_BenefitsValidationFusProxy_BenefitsValidationFusService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event dropFusNoteCompletedEventHandler dropFusNoteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("dropFusNoteResponse", Namespace="urn:BenefitsValidationFusService/types")]
        public dropFusNoteResponse dropFusNote([System.Xml.Serialization.XmlElementAttribute("dropFusNote", Namespace="urn:BenefitsValidationFusService/types")] dropFusNote dropFusNote1) {
            object[] results = this.Invoke("dropFusNote", new object[] {
                        dropFusNote1});
            return ((dropFusNoteResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindropFusNote(dropFusNote dropFusNote1, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dropFusNote", new object[] {
                        dropFusNote1}, callback, asyncState);
        }
        
        /// <remarks/>
        public dropFusNoteResponse EnddropFusNote(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((dropFusNoteResponse)(results[0]));
        }
        
        /// <remarks/>
        public void dropFusNoteAsync(dropFusNote dropFusNote1) {
            this.dropFusNoteAsync(dropFusNote1, null);
        }
        
        /// <remarks/>
        public void dropFusNoteAsync(dropFusNote dropFusNote1, object userState) {
            if ((this.dropFusNoteOperationCompleted == null)) {
                this.dropFusNoteOperationCompleted = new System.Threading.SendOrPostCallback(this.OndropFusNoteOperationCompleted);
            }
            this.InvokeAsync("dropFusNote", new object[] {
                        dropFusNote1}, this.dropFusNoteOperationCompleted, userState);
        }
        
        private void OndropFusNoteOperationCompleted(object arg) {
            if ((this.dropFusNoteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dropFusNoteCompleted(this, new dropFusNoteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:BenefitsValidationFusService/types")]
    public partial class dropFusNote {
        
        private BenefitsValidationFusRequest benefitsValidationFusRequest_1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public BenefitsValidationFusRequest BenefitsValidationFusRequest_1 {
            get {
                return this.benefitsValidationFusRequest_1Field;
            }
            set {
                this.benefitsValidationFusRequest_1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:BenefitsValidationFusService/types")]
    public partial class BenefitsValidationFusRequest {
        
        private int customerIdField;
        
        private string hspcdField;
        
        private string userIdField;
        
        private string accountNumberField;
        
        private string benefitsValidationUniqueIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int customerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string hspcd {
            get {
                return this.hspcdField;
            }
            set {
                this.hspcdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string benefitsValidationUniqueId {
            get {
                return this.benefitsValidationUniqueIdField;
            }
            set {
                this.benefitsValidationUniqueIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:BenefitsValidationFusService/types")]
    public partial class dropFusNoteResponse {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void dropFusNoteCompletedEventHandler(object sender, dropFusNoteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dropFusNoteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dropFusNoteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dropFusNoteResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dropFusNoteResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591