 --  Generate SQL 
--  Version:                   	V5R3M0 040528 
--  Generated on:              	12/05/06 12:54:21 
--  Relational Database:       	DVLA 
--  Standards Option:          	DB2 UDB iSeries 
  

SET PATH *LIBL ; 

CREATE FUNCTION GETCATEGORYTYPE ( 
	PLANSUFFIX VARCHAR(2) ) 
	RETURNS INTEGER   
	LANGUAGE SQL 
	SPECIFIC GETCATTYPE 
	DETERMINISTIC 
	READS SQL DATA 
	CALLED ON NULL INPUT 
	NO EXTERNAL ACTION 

	BEGIN 

				DECLARE FINALRESULT INTEGER ; 
				DECLARE CATEGORYID INTEGER DEFAULT NULL ; 
				DECLARE CNT INTEGER ; 

				 
				SELECT COUNT ( 1 ) 
				INTO CNT 
				FROM PLANCATEGORYXREF P 
				WHERE P . SUFFIXSTRING = PLANSUFFIX ; 

				IF ( CNT <> 0 ) THEN 

				SELECT P . PLANCATEGORYID 
				INTO CATEGORYID 
				FROM PLANCATEGORYXREF P 
				WHERE P . SUFFIXSTRING = PLANSUFFIX ; 

				ELSE 

				SELECT P . PLANCATEGORYID 
				INTO CATEGORYID 
				FROM PLANCATEGORYXREF P 
				WHERE P . SUFFIXSTRING = SUBSTR ( PLANSUFFIX , 1 , 1 ) || '*' ; 

				END IF ; 

				SET FINALRESULT = CATEGORYID ; 

				RETURN FINALRESULT ; 

				END  ;
