--  Generate SQL 
--  Version:                   	V7R2M0 140418 
--  Generated on:              	04/05/19 04:24:13 
--  Relational Database:       	DVLA 
--  Standards Option:          	DB2 for i 
SET PATH *LIBL ; 
  
CREATE PROCEDURE PACCESS.SELECTLANGUAGEWITH ( 
	IN P_LANGUAGECODE VARCHAR(10) , 
	IN P_FACILITYID INTEGER )  
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PACCESS.SLLANGWI 
	NOT DETERMINISTIC 
	READS SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DBGVIEW = *SOURCE , 
	CLOSQLCSR = *ENDACTGRP , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DLYPRP = *NO , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	RDBCNNMTH = *RUW , 
	SRTSEQ = *HEX   
	P1 : BEGIN DECLARE CURSOR1 CURSOR FOR	
	SELECT 0 AS OID ,	
	TRIM ( NDKEY ) AS CODE ,	
	TRIM ( NDLNDS ) AS DESCRIPTION	
	FROM NDLN01P	
	WHERE NDKEY = P_LANGUAGECODE	
	AND NDHSP# = P_FACILITYID ; 
	OPEN CURSOR1 ; END P1  ;

