//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 

namespace Hsd.PerotSystems.PatientAccess.Services.ViWeb
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "wsdl", "2.0.50727.42" )]
    [System.Web.Services.WebServiceBindingAttribute( Name = "PreviousVisitServiceSoapBinding", Namespace = "http://vi.webservices.tenethealth.com" )]
    [System.Xml.Serialization.SoapIncludeAttribute( typeof( PreviousVisitDocument ) )]
    public interface IPreviousVisitServiceSoapBinding
    {

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute( "", RequestNamespace = "http://vi.webservices.tenethealth.com", ResponseNamespace = "http://vi.webservices.tenethealth.com" )]
        [return: System.Xml.Serialization.SoapElementAttribute( "getPreviousVisitDocumentsReturn" )]
        PreviousVisitDocumentResponse getPreviousVisitDocuments( PreviousVisitDocumentRequest pvdr );

        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute( "", RequestNamespace = "http://vi.webservices.tenethealth.com", ResponseNamespace = "http://vi.webservices.tenethealth.com" )]
        [return: System.Xml.Serialization.SoapElementAttribute( "setPreviousVisitDocumentReturn" )]
        AcceptPreviousVisitDocumentResponse setPreviousVisitDocument( AcceptPreviousVisitDocumentRequest request );
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "wsdl", "2.0.50727.42" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.SoapTypeAttribute( Namespace = "urn:PreviousVisitService" )]
    public partial class PreviousVisitDocumentRequest
    {

        private string docTypeField;

        private string hspCodeField;

        private int maxAgeField;

        private string medicalRecordNumberField;

        private string multipleField;

        private int returnFormatField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute( IsNullable = true )]
        public string docType
        {
            get
            {
                return this.docTypeField;
            }
            set
            {
                this.docTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute( IsNullable = true )]
        public string hspCode
        {
            get
            {
                return this.hspCodeField;
            }
            set
            {
                this.hspCodeField = value;
            }
        }

        /// <remarks/>
        public int maxAge
        {
            get
            {
                return this.maxAgeField;
            }
            set
            {
                this.maxAgeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute( IsNullable = true )]
        public string medicalRecordNumber
        {
            get
            {
                return this.medicalRecordNumberField;
            }
            set
            {
                this.medicalRecordNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute( IsNullable = true )]
        public string multiple
        {
            get
            {
                return this.multipleField;
            }
            set
            {
                this.multipleField = value;
            }
        }

        /// <remarks/>
        public int returnFormat
        {
            get
            {
                return this.returnFormatField;
            }
            set
            {
                this.returnFormatField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "wsdl", "2.0.50727.42" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.SoapTypeAttribute( Namespace = "urn:PreviousVisitService" )]
    public partial class AcceptPreviousVisitDocumentResponse
    {

        private string currentVisitAccountNumberField;

        private bool documentAcceptedField;

        private string errorMessageField;

        private string prevoiusVisitAccountNumberField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute( IsNullable = true )]
        public string currentVisitAccountNumber
        {
            get
            {
                return this.currentVisitAccountNumberField;
            }
            set
            {
                this.currentVisitAccountNumberField = value;
            }
        }

        /// <remarks/>
        public bool documentAccepted
        {
            get
            {
                return this.documentAcceptedField;
            }
            set
            {
                this.documentAcceptedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute( IsNullable = true )]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute( IsNullable = true )]
        public string prevoiusVisitAccountNumber
        {
            get
            {
                return this.prevoiusVisitAccountNumberField;
            }
            set
            {
                this.prevoiusVisitAccountNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "wsdl", "2.0.50727.42" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.SoapTypeAttribute( Namespace = "urn:PreviousVisitService" )]
    public partial class AcceptPreviousVisitDocumentRequest
    {

        private string currentAcctNumberField;

        private string docIDField;

        private string hspCodeField;

        private string previousAcctNumbField;

        private string previousAcctNumberField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute( IsNullable = true )]
        public string currentAcctNumber
        {
            get
            {
                return this.currentAcctNumberField;
            }
            set
            {
                this.currentAcctNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute( IsNullable = true )]
        public string docID
        {
            get
            {
                return this.docIDField;
            }
            set
            {
                this.docIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute( IsNullable = true )]
        public string hspCode
        {
            get
            {
                return this.hspCodeField;
            }
            set
            {
                this.hspCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute( IsNullable = true )]
        public string previousAcctNumb
        {
            get
            {
                return this.previousAcctNumbField;
            }
            set
            {
                this.previousAcctNumbField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute( IsNullable = true )]
        public string previousAcctNumber
        {
            get
            {
                return this.previousAcctNumberField;
            }
            set
            {
                this.previousAcctNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "wsdl", "2.0.50727.42" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.SoapTypeAttribute( Namespace = "urn:PreviousVisitService" )]
    public partial class PreviousVisitDocument
    {

        private string accountNumberField;

        private System.Nullable<System.DateTime> documentDateField;

        private string documentIdField;

        private byte[] documentObjectField;

        private string urlField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute( IsNullable = true )]
        public string accountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute( IsNullable = true )]
        public System.Nullable<System.DateTime> documentDate
        {
            get
            {
                return this.documentDateField;
            }
            set
            {
                this.documentDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute( IsNullable = true )]
        public string documentId
        {
            get
            {
                return this.documentIdField;
            }
            set
            {
                this.documentIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute( DataType = "base64Binary", IsNullable = true )]
        public byte[] documentObject
        {
            get
            {
                return this.documentObjectField;
            }
            set
            {
                this.documentObjectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute( IsNullable = true )]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute( "wsdl", "2.0.50727.42" )]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute( "code" )]
    [System.Xml.Serialization.SoapTypeAttribute( Namespace = "urn:PreviousVisitService" )]
    public partial class PreviousVisitDocumentResponse
    {

        private string docTypeField;

        private bool documentsWereFoundField;

        private string errorMessageField;

        private string hspCodeField;

        private string medicalRecordNumberField;

        private PreviousVisitDocument[] previousVisitDocumentsField;

        private PreviousVisitDocument[] recsFoundField;

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute( IsNullable = true )]
        public string docType
        {
            get
            {
                return this.docTypeField;
            }
            set
            {
                this.docTypeField = value;
            }
        }

        /// <remarks/>
        public bool documentsWereFound
        {
            get
            {
                return this.documentsWereFoundField;
            }
            set
            {
                this.documentsWereFoundField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute( IsNullable = true )]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute( IsNullable = true )]
        public string hspCode
        {
            get
            {
                return this.hspCodeField;
            }
            set
            {
                this.hspCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute( IsNullable = true )]
        public string medicalRecordNumber
        {
            get
            {
                return this.medicalRecordNumberField;
            }
            set
            {
                this.medicalRecordNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute( IsNullable = true )]
        public PreviousVisitDocument[] previousVisitDocuments
        {
            get
            {
                return this.previousVisitDocumentsField;
            }
            set
            {
                this.previousVisitDocumentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute( IsNullable = true )]
        public PreviousVisitDocument[] recsFound
        {
            get
            {
                return this.recsFoundField;
            }
            set
            {
                this.recsFoundField = value;
            }
        }
    }
}