--  Generate SQL 
--  Version:                   	V7R2M0 140418 
--  Generated on:              	09/14/17 02:52:39 
--  Relational Database:       	DVLA 
--  Standards Option:          	DB2 for i 
CREATE VIEW INSURANCES ( 
	HSPNUMBER , 
	ACCOUNTNUMBER FOR COLUMN ACCOU00001 , 
	INSUREDLASTNAME FOR COLUMN INSUR00001 , 
	INSUREDFIRSTNAME FOR COLUMN INSUR00002 , 
	INSUREDMIDDLEINITIAL FOR COLUMN INSUR00003 , 
	INSUREDNAMESUFFIX FOR COLUMN INSUR00021 , 
	INSUREDSEX , 
	INSUREDRELATIONSHIP FOR COLUMN INSUR00004 , 
	INSUREDIDENTIFIER FOR COLUMN INSUR00005 , 
	INSUREDCOUNTRYCODE FOR COLUMN INSUR00006 , 
	INSUREDBIRTHDATE FOR COLUMN INSUR00007 , 
	INSURANCECERTIFICATIONNUM FOR COLUMN INSUR00008 , 
	INSURANCEGROUPNUMBER FOR COLUMN INSGRP0001 , 
	GROUPNUMBER FOR COLUMN GROUP00001 , 
	POLICYNUMBER FOR COLUMN POLIC00001 , 
	EVCNUMBER , 
	AUTHORIZATIONNUMBER FOR COLUMN AUTHO00001 , 
	AUTHORIZEDDAYS FOR COLUMN AUTHO00002 , 
	ISSUEDATE , 
	INSUREDADDRESS FOR COLUMN INSUR00009 , 
	INSUREDCITY FOR COLUMN INSUR00010 , 
	INSUREDSTATE FOR COLUMN INSUR00011 , 
	INSUREDZIP , 
	INSUREDZIPEXT FOR COLUMN INSUR00012 , 
	INSUREDAREACODE1 FOR COLUMN INSUR00013 , 
	INSUREDPHONENUMBER1 FOR COLUMN INSUR00014 , 
	INSUREDAREACODE2 FOR COLUMN INSUR00015 , 
	INSUREDPHONENUMBER2 FOR COLUMN INSUR00016 , 
	INSUREDCELLPHONE FOR COLUMN INSUR00017 , 
	INSURANCECOMPANYNUMBER FOR COLUMN INSUR00018 , 
	SIGNEDOVERMEDICAREHICNUMBER FOR COLUMN INSUR00019 , 
	PRIORITYCODE FOR COLUMN PRIOR00001 , 
	BILLINGADDRESS1 FOR COLUMN BILLI00001 , 
	BILLINGCITYSTATECOUNTRY FOR COLUMN BILLI00002 , 
	BILLINGZIPZIPEXTPHONE FOR COLUMN BILLI00003 , 
	DEDUCTIBLE , 
	COPAY , 
	NOLIABILITY FOR COLUMN NOLIA00001 , 
	ELIGIBILITY FOR COLUMN ELIGI00001 , 
	PRIMARYEMPSTATUS FOR COLUMN PRIMA00001 , 
	PRIMARYEMPCODE FOR COLUMN PRIMA00002 , 
	PRIMARYEMPNAME FOR COLUMN PRIMA00003 , 
	PRIMARYEMPADDRESS FOR COLUMN PRIMA00004 , 
	PRIMARYLOC , 
	PRIMARYEMPZIP FOR COLUMN PRIMA00005 , 
	PRIMARYEMPZIPEXT FOR COLUMN PRIMA00006 , 
	PRIMARYPHONE FOR COLUMN PRIMA00007 , 
	SECONDARYEMPSTATUS FOR COLUMN SECON00001 , 
	SECONDARYEMPCODE FOR COLUMN SECON00002 , 
	SECONDARYEMPNAME FOR COLUMN SECON00003 , 
	SECONDARYEMPADDRESS FOR COLUMN SECON00004 , 
	SECONDARYLOC FOR COLUMN SECON00005 , 
	SECONDARYEMPZIP FOR COLUMN SECON00006 , 
	SECONDARYEMPZIPEXT FOR COLUMN SECON00007 , 
	SECONDARYPHONE FOR COLUMN SECON00008 , 
	CONDITIONOFSERVICE FOR COLUMN CONDI00001 , 
	EFFECTIVEON FOR COLUMN EFFEC00001 , 
	APPROVEDON , 
	AUTHORIZATIONPHONE FOR COLUMN AUTHO00003 , 
	AUTHORIZATIONCOMPANY FOR COLUMN AUTHO00004 , 
	AUTHORIZATIONPMTEXT FOR COLUMN AUTHO00005 , 
	AUTHORIZATIONFLAG FOR COLUMN AUTHO00006 , 
	VERIFICATIONDATE FOR COLUMN VERIF00001 , 
	VERIFICATIONFLAG FOR COLUMN VERIF00002 , 
	VERIFIEDBY , 
	ATTORNEYNAME FOR COLUMN ATTOR00001 , 
	ATTORNEYSTREET FOR COLUMN ATTOR00002 , 
	ATTORNEYCITY FOR COLUMN ATTOR00003 , 
	ATTORNEYSTATE FOR COLUMN ATTOR00004 , 
	ATTORNEYZIP5 FOR COLUMN ATTOR00005 , 
	ATTORNEYZIP4 FOR COLUMN ATTOR00006 , 
	ATTORNEYCOUNTRYCODE FOR COLUMN ATTOR00007 , 
	ATTORNEYPHONE FOR COLUMN ATTOR00008 , 
	AGENTNAME , 
	AGENTPHONE , 
	AGENTSTREET FOR COLUMN AGENT00001 , 
	AGENTCITY , 
	AGENTSTATE , 
	AGENTZIP5 , 
	AGENTZIP4 , 
	AGENTCOUNTRYCODE FOR COLUMN AGENT00002 , 
	BILLINGCAREOFNAME FOR COLUMN BILLI00004 , 
	BILLINGNAME FOR COLUMN BILLI00005 , 
	TRACKINGNUMBER FOR COLUMN TRACK00001 , 
	ADJUSTERSNAME FOR COLUMN ADJUS00001 , 
	EMPLOYEESSUPERVISOR FOR COLUMN EMPLO00001 , 
	AUTHCOMPANYREPFIRSTNAME FOR COLUMN AUTHC00001 , 
	AUTHCOMPANYREPLASTNAME FOR COLUMN AUTHC00002 , 
	SERVICESAUTHORIZED FOR COLUMN SERVI00001 , 
	EFFECTIVEDATEOFAUTH FOR COLUMN EFFEC00002 , 
	EXPIRATIONDATEOFAUTH FOR COLUMN EXPIR00001 , 
	AUTHORIZATIONSTATUS FOR COLUMN AUTHO00007 , 
	AUTHORIZATIONREMARKS FOR COLUMN AUTHO00008 , 
	INSURANCECOMPANYNAME FOR COLUMN INSUR00020 ) 
	AS 
	SELECT  
		  
					I.HBHSP# AS HSPNUMBER,  
		  
					I.HBACCT AS ACCOUNTNUMBER,		  
		  
					I.HBSLNM AS INSUREDLASTNAME,  
		  
					I.HBSFNM AS INSUREDFIRSTNAME,  
		  
					I.HBSMI AS INSUREDMIDDLEINITIAL,  
	  
					I.HBSGNRN AS INSUREDNAMESUFFIX ,  
		  
					I.HBSSEX AS INSUREDSEX,  
		  
					I.HBSRCD AS INSUREDRELATIONSHIP,	  
		  
					I.HBSBID AS INSUREDIDENTIFIER,	  
		  
					I.HBSCUN AS INSUREDCOUNTRYCODE,  
		  
					I.HBSBTH AS INSUREDBIRTHDATE,  
		  
					I.HBIID# AS INSURANCECERTIFICATIONNUM,	  
		  
					I.HBGRPN AS INSURANCEGROUPNUMBER,  
		  
					I.HBGRP# AS GROUPNUMBER,  
		  
					I.HBPOL# AS POLICYNUMBER,  
		  
					I.HBEVC# AS EVCNUMBER,  
		  
					I.HBAUTH# AS AUTHORIZATIONNUMBER,  
		  
					I.HBAUDY AS AUTHORIZEDDAYS,  
		  
					I.HBMCDT AS ISSUEDATE,  
		  
					I.HBJADR AS INSUREDADDRESS,  
		  
					I.HBJCIT AS INSUREDCITY,  
		  
					I.HBJSTE AS INSUREDSTATE,  
		  
					I.HBJZPA AS INSUREDZIP,  
		  
					I.HBJZ4A AS INSUREDZIPEXT,  
		  
					I.HBJACD AS INSUREDAREACODE1,  
		  
					I.HBJPH# AS INSUREDPHONENUMBER1,		  
		  
					I.HBRACD AS INSUREDAREACODE2,  
		  
					I.HBRPH# AS INSUREDPHONENUMBER2,			  
		  
					I.HBCLPH AS INSUREDCELLPHONE,  
		  
					I.HBINS# AS INSURANCECOMPANYNUMBER,  
		  
					I.HBHIC# AS SIGNEDOVERMEDICAREHICNUMBER,  
		  
					I.HBPTY AS PRIORITYCODE,  
		  
					I.HBIAD1 AS BILLINGADDRESS1,	  
		  
					I.HBIAD2 AS BILLINGCITYSTATECOUNTRY,			  
		  
					I.HBIAD3 AS BILLINGZIPZIPEXTPHONE,  
		  
					I.HBDAMT AS DEDUCTIBLE,  
		  
					I.HBCPAY AS COPAY,  
		  
					I.HBCR09 AS NOLIABILITY,  
		  
					I.HBELGS AS ELIGIBILITY,  
		  
					P.LAESC1 AS PRIMARYEMPSTATUS,  
		  
					P.LAGCD1 AS PRIMARYEMPCODE,	  
		  
					P.LAENM1 AS PRIMARYEMPNAME,  
		  
					P.LAEA01 AS PRIMARYEMPADDRESS,	  
		  
					P.LAELO1 AS PRIMARYLOC,  
					P.LAEZP1 AS PRIMARYEMPZIP,  
		  
					P.LAEZ41 AS PRIMARYEMPZIPEXT,  
		  
					P.LAEID1 AS PRIMARYPHONE,	  
		  
					S.LAESC2 AS SECONDARYEMPSTATUS,  
		  
					S.LAGCD2 AS SECONDARYEMPCODE,	  
		  
					S.LAENM2 AS SECONDARYEMPNAME,  
		  
					S.LAEA02 AS SECONDARYEMPADDRESS,	  
		  
					S.LAELO2 AS SECONDARYLOC,  
					S.LAEZP2 AS SECONDARYEMPZIP,  
		  
					S.LAEZ42 AS SECONDARYEMPZIPEXT,  
		  
					S.LAEID2 AS SECONDARYPHONE,  
		  
					I.HBRICF AS CONDITIONOFSERVICE,  
		  
					I.HBCBGD AS EFFECTIVEON,  
		  
					I.HBPLAD AS APPROVEDON ,  
		  
					  
					I.HBAUPH AS AUTHORIZATIONPHONE,  
		  
					I.HBAUCP AS AUTHORIZATIONCOMPANY, 	  
		  
					I.HBAUEX AS AUTHORIZATIONPMTEXT,  
		  
					I.HBAUTFG AS AUTHORIZATIONFLAG,  
		  
					I.HBVFDT AS VERIFICATIONDATE,  
		  
					I.HBVFFG AS VERIFICATIONFLAG,  
		  
					I.HBVFBY AS VERIFIEDBY, 		  
		  
					I.HBATNM AS ATTORNEYNAME,  
		  
					I.HBATST AS ATTORNEYSTREET,  
		  
					I.HBATCT AS ATTORNEYCITY,  
		  
					I.HBATSA AS ATTORNEYSTATE,  
		  
					I.HBATZ5 AS ATTORNEYZIP5,  
		  
					I.HBATZ4 AS ATTORNEYZIP4,  
		  
					I.HBATCC AS ATTORNEYCOUNTRYCODE,  
		  
					I.HBATPH AS ATTORNEYPHONE,  
		  
					I.HBAGNM AS AGENTNAME,  
		  
					I.HBAGPH AS AGENTPHONE,	  
		  
					I.HBAGST AS AGENTSTREET,  
		  
					I.HBAGCT AS AGENTCITY,  
		  
					I.HBAGSA AS AGENTSTATE,  
		  
					I.HBAGZ5 AS AGENTZIP5,  
		  
					I.HBAGZ4 AS AGENTZIP4,  
		  
					I.HBAGCC AS AGENTCOUNTRYCODE ,  
		  
					I.HBCONM AS BILLINGCAREOFNAME,  
		  
					I.HBBLNM AS BILLINGNAME ,  
		  
					I.HBITR# AS TRACKINGNUMBER,  
		  
					I.HBADNM AS ADJUSTERSNAME,  
		  
					I.HBEMSU AS EMPLOYEESSUPERVISOR,  
		  
					I.HBACRFN AS AUTHCOMPANYREPFIRSTNAME,  
		  
					I.HBACRLN AS AUTHCOMPANYREPLASTNAME,  
		  
					I.HBSAUTH AS SERVICESAUTHORIZED ,  
		  
					I.HBEFDA AS EFFECTIVEDATEOFAUTH ,  
		  
					I.HBEXDA AS EXPIRATIONDATEOFAUTH ,  
		  
					I.HBASTS AS AUTHORIZATIONSTATUS ,  
		  
					I.HBARMKS AS AUTHORIZATIONREMARKS,  
		  
					I.HBINM AS INSURANCECOMPANYNAME  
		  
		 			FROM HPADHBP I  
		  
		 			LEFT OUTER JOIN HPADLAP7 P  
		  
					ON ( I.HBMRC# = P.LAMRC# AND I.HBHSP# = P.LAHSP# )  
		  
		 			LEFT OUTER JOIN HPADLAP8 S  
		  
					ON ( I.HBMRC# = S.LAMRC# AND I.HBHSP# = S.LAHSP# ) ; 
  
LABEL ON COLUMN INSURANCES 
( HSPNUMBER IS 'HOSP#' , 
	ACCOUNTNUMBER IS 'ACCT.#' , 
	INSUREDLASTNAME IS 'SUBSCRIBER LAST NAME' , 
	INSUREDFIRSTNAME IS 'SUBSCRIBER FIRST NAME' , 
	INSUREDMIDDLEINITIAL IS 'SUBSCRIBER MID INITIAL' , 
	INSUREDNAMESUFFIX IS 'SUBSCRIBER NAME SUFFIX' , 
	INSUREDSEX IS 'SUBSCRIBER SEX CODE' , 
	INSUREDRELATIONSHIP IS 'SUBSCRIBER REL. CODE' , 
	INSUREDIDENTIFIER IS 'SUBSCRIBER IDENTIFIER' , 
	INSUREDCOUNTRYCODE IS 'SUBSCRIBER COUNTRY''CODE' , 
	INSUREDBIRTHDATE IS 'SUBSCRIBER BIRTH DATE' , 
	INSURANCECERTIFICATIONNUM IS 'CERT/HIC/SSN' , 
	INSURANCEGROUPNUMBER IS 'INSURANCE GROUP #' , 
	GROUPNUMBER IS 'GROUP #' , 
	POLICYNUMBER IS 'POLICY NUMBER' , 
	EVCNUMBER IS 'ELIG VERIFY CONF #' , 
	AUTHORIZATIONNUMBER IS 'AUTHORIZATION#' , 
	AUTHORIZEDDAYS IS 'AUTH DAYS' , 
	ISSUEDATE IS 'INS MEDI-CAL ISSUE DDATE' , 
	INSUREDADDRESS IS 'SUBSCRIBER ADDRESS' , 
	INSUREDCITY IS 'SUBSCRIBER CITY' , 
	INSUREDSTATE IS 'SUBSCRIBER STATE CODE' , 
	INSUREDZIP IS 'ALPHA ZIP' , 
	INSUREDZIPEXT IS 'ALPHA ZIP+4' , 
	INSUREDAREACODE1 IS 'SUBSCRIBER AREA CODE' , 
	INSUREDPHONENUMBER1 IS 'SUBSCRIBER TELEPHONE #' , 
	INSUREDAREACODE2 IS 'SUBSCRIBER AREA CODE' , 
	INSUREDPHONENUMBER2 IS 'SUBSCRIBER TELEPHONE #' , 
	INSUREDCELLPHONE IS 'INSURED CELL PHONE' , 
	SIGNEDOVERMEDICAREHICNUMBER IS 'MEDICARE HIC#' , 
	PRIORITYCODE IS 'BENEF PRIORITY' , 
	BILLINGADDRESS1 IS 'ADDRESS LINE 1' , 
	BILLINGCITYSTATECOUNTRY IS 'ADDRESS LINE 2' , 
	BILLINGZIPZIPEXTPHONE IS 'ADDRESS LINE 3' , 
	DEDUCTIBLE IS 'DEDUCTIBLE  AMOUNT DUE' , 
	COPAY IS 'COPAY AMOUNT DUE' , 
	NOLIABILITY IS 'FLAG1' , 
	ELIGIBILITY IS 'ELIGIBILITY SOURCE CODE' , 
	PRIMARYEMPSTATUS IS 'OTHER EMPL STATUS 1/2' , 
	PRIMARYEMPCODE IS 'EMPLOYER CODE' , 
	PRIMARYEMPNAME IS 'OTHER EMPL NAME 1/2' , 
	PRIMARYEMPADDRESS IS 'O EMPLR ADDRESS' , 
	PRIMARYLOC IS 'OTHER EMPL LOCATION 1' , 
	PRIMARYEMPZIP IS 'EMPLOYER ZIP' , 
	PRIMARYEMPZIPEXT IS 'EMPLOYER ZIP+4' , 
	PRIMARYPHONE IS 'OTHER EMPL ID 1/2' , 
	SECONDARYEMPSTATUS IS 'OTHER EMPL STATUS 2/2' , 
	SECONDARYEMPCODE IS 'EMPLOYER CODE' , 
	SECONDARYEMPNAME IS 'OTHER EMPL NAME 2/2' , 
	SECONDARYEMPADDRESS IS 'O EMPLR ADDRESS' , 
	SECONDARYLOC IS 'OTHER EMPL LOCATION 2' , 
	SECONDARYEMPZIP IS 'EMPLOYER ZIP' , 
	SECONDARYEMPZIPEXT IS 'EMPLOYER ZIP+4' , 
	SECONDARYPHONE IS 'OTHER EMPL ID 2/2' , 
	CONDITIONOFSERVICE IS 'RELEASE OF INFO FLAG' , 
	EFFECTIVEON IS 'EFFECTIVE DATE' , 
	APPROVEDON IS 'APPROVAL DATE' , 
	AUTHORIZATIONPHONE IS 'AUTHORIZATION PHONE #' , 
	AUTHORIZATIONCOMPANY IS 'AUTHORIZATION COMPANY' , 
	AUTHORIZATIONPMTEXT IS 'AUTHORIZATION PMT/EXT #' , 
	AUTHORIZATIONFLAG IS 'AUTH REQUIRED' , 
	VERIFICATIONDATE IS 'START DATE' , 
	VERIFICATIONFLAG IS 'VERIFIY STATUS' , 
	VERIFIEDBY IS 'VERIFIED BY-' , 
	ATTORNEYNAME IS 'ATTORNEY NAME' , 
	ATTORNEYSTREET IS 'ATTORNEY STREET' , 
	ATTORNEYCITY IS 'ATTORNEY CITY' , 
	ATTORNEYSTATE IS 'ATTORNEY STATE' , 
	ATTORNEYZIP5 IS 'ATTORNEY ZIP5' , 
	ATTORNEYZIP4 IS 'ATTORNEY ZIP4' , 
	ATTORNEYCOUNTRYCODE IS 'ATTORNEY COUNTRY CODE' , 
	ATTORNEYPHONE IS 'ATTORNEY PHONE #' , 
	AGENTNAME IS 'AUT/HOM INS AGENT NAME' , 
	AGENTPHONE IS 'AUT/HOM INS AGENT PH #' , 
	AGENTSTREET IS 'AGENT STREET' , 
	AGENTCITY IS 'AGENT CITY' , 
	AGENTSTATE IS 'AGENT STATE' , 
	AGENTZIP5 IS 'AGENT ZIP5' , 
	AGENTZIP4 IS 'AGENT ZIP4' , 
	AGENTCOUNTRYCODE IS 'AGENT COUNTRY CODE' , 
	BILLINGCAREOFNAME IS 'C/O NAME' , 
	BILLINGNAME IS 'BILLING NAME' , 
	TRACKINGNUMBER IS 'INSURANCE TRACKING#' , 
	ADJUSTERSNAME IS 'ADJUSTERS NAME' , 
	EMPLOYEESSUPERVISOR IS 'EMPLOYEES SUPERVISOR' , 
	AUTHCOMPANYREPFIRSTNAME IS 'AUTH COMPANY REP FIRST NAME' , 
	AUTHCOMPANYREPLASTNAME IS 'AUTH COMPANY REP LAST NAME' , 
	SERVICESAUTHORIZED IS 'SERVICES AUTHORIZED' , 
	EFFECTIVEDATEOFAUTH IS 'EFFECTIVE DATE OF AUTH' , 
	EXPIRATIONDATEOFAUTH IS 'EXPIRATION DATE OF AUTH' , 
	AUTHORIZATIONSTATUS IS 'AUTHORIZATION STATUS' , 
	AUTHORIZATIONREMARKS IS 'AUTHORIZATION REMARKS' , 
	INSURANCECOMPANYNAME IS 'INSURANCE COMPANY NAME' ) ; 
  
LABEL ON COLUMN INSURANCES 
( HSPNUMBER TEXT IS 'HOSPITAL NUMBER' , 
	ACCOUNTNUMBER TEXT IS 'PATIENT ACCOUNT NUMBER' , 
	INSUREDLASTNAME TEXT IS 'SUBSCRIBER LAST NAME' , 
	INSUREDFIRSTNAME TEXT IS 'SUBSCRIBER FIRST NAME' , 
	INSUREDMIDDLEINITIAL TEXT IS 'SUBSCRIBER MIDDLE INITIAL' , 
	INSUREDNAMESUFFIX TEXT IS 'SUBSCRIBER NAME SUFFIX' , 
	INSUREDSEX TEXT IS 'SUBSCRIBER SEX CODE' , 
	INSUREDRELATIONSHIP TEXT IS 'SUBSCRIBER RELATIONSHIP CODE' , 
	INSUREDIDENTIFIER TEXT IS 'SUBSCRIBER  IDENTIFIER' , 
	INSUREDCOUNTRYCODE TEXT IS 'SUBSCRIBER COUNTRY CODE' , 
	INSUREDBIRTHDATE TEXT IS 'SUBSCRIBER BIRTH DATE' , 
	INSURANCECERTIFICATIONNUM TEXT IS 'INS CERTIFICATION #' , 
	INSURANCEGROUPNUMBER TEXT IS 'INSURANCE GROUP NUMBER' , 
	GROUPNUMBER TEXT IS 'GROUP NUMBER' , 
	POLICYNUMBER TEXT IS 'POLICY NUMBER' , 
	EVCNUMBER TEXT IS 'ELIG VERIFY CONF #' , 
	AUTHORIZATIONNUMBER TEXT IS 'AUTHORIZATION#' , 
	AUTHORIZEDDAYS TEXT IS 'AUTHORIZED DAYS' , 
	ISSUEDATE TEXT IS 'INS MEDI-CAL ISSUE DATER' , 
	INSUREDADDRESS TEXT IS 'SUBSCRIBER ADDRESS' , 
	INSUREDCITY TEXT IS 'SUBSCRIBER CITY' , 
	INSUREDSTATE TEXT IS 'SUBSCRIBER STATE CODE' , 
	INSUREDZIP TEXT IS 'ALPHA ZIP' , 
	INSUREDZIPEXT TEXT IS 'ALPHA ZIP+4' , 
	INSUREDAREACODE1 TEXT IS 'SUBSCRIBER AREA CODE' , 
	INSUREDPHONENUMBER1 TEXT IS 'SUBSCRIBER TELEPHONE NUMBER' , 
	INSUREDAREACODE2 TEXT IS 'SUBSCRIBER AREA CODE' , 
	INSUREDPHONENUMBER2 TEXT IS 'SUBSCRIBER TELEPHONE NUMBER' , 
	INSUREDCELLPHONE TEXT IS 'INSURED CELL PHONE' , 
	INSURANCECOMPANYNUMBER TEXT IS 'INSURANCE COMPANY NUMBER' , 
	SIGNEDOVERMEDICAREHICNUMBER TEXT IS 'MEDICARE HIC#' , 
	PRIORITYCODE TEXT IS 'PRIORITY CODE' , 
	BILLINGADDRESS1 TEXT IS 'MAILING ADDRESS LINE 1' , 
	BILLINGCITYSTATECOUNTRY TEXT IS 'MAILING ADDRESS LINE 2' , 
	BILLINGZIPZIPEXTPHONE TEXT IS 'MAILING ADDRESS LINE 3' , 
	DEDUCTIBLE TEXT IS 'DEDUCTIBLE AMOUNT DUE' , 
	COPAY TEXT IS 'COPAY AMOUNT DUE' , 
	NOLIABILITY TEXT IS 'FLAG1' , 
	ELIGIBILITY TEXT IS 'ELIGIBILITY SOURCE CODE' , 
	PRIMARYEMPSTATUS TEXT IS 'OTHER EMPLOYMENT STATUS 1/2' , 
	PRIMARYEMPCODE TEXT IS 'EMPLOYER CODE' , 
	PRIMARYEMPNAME TEXT IS 'OTHER EMPLOYER NAME 1/2' , 
	PRIMARYEMPADDRESS TEXT IS 'O EMPLR ADDRESS' , 
	PRIMARYLOC TEXT IS 'OTHER EMPLOYER LOCATION 1/2' , 
	PRIMARYEMPZIP TEXT IS 'EMPLOYER ZIP' , 
	PRIMARYEMPZIPEXT TEXT IS 'EMPLOYER ZIP+4' , 
	PRIMARYPHONE TEXT IS 'OTHER EMPLOYEE ID 1/2' , 
	SECONDARYEMPSTATUS TEXT IS 'OTHER EMPLOYMENT STATUS 2/2' , 
	SECONDARYEMPCODE TEXT IS 'EMPLOYER CODE' , 
	SECONDARYEMPNAME TEXT IS 'OTHER EMPLOYER NAME 2/2' , 
	SECONDARYEMPADDRESS TEXT IS 'O EMPLR ADDRESS' , 
	SECONDARYLOC TEXT IS 'OTHER EMPLOYER LOCATION 2/2' , 
	SECONDARYEMPZIP TEXT IS 'EMPLOYER ZIP' , 
	SECONDARYEMPZIPEXT TEXT IS 'EMPLOYER ZIP+4' , 
	SECONDARYPHONE TEXT IS 'OTHER EMPLOYEE ID 2/2' , 
	CONDITIONOFSERVICE TEXT IS 'RELEASE OF INFO CERT FLAG' , 
	EFFECTIVEON TEXT IS 'EFFECTIVE DATE' , 
	APPROVEDON TEXT IS 'APPROVAL DATE' , 
	AUTHORIZATIONPHONE TEXT IS 'AUTHORIZATION PHONE #' , 
	AUTHORIZATIONCOMPANY TEXT IS 'AUTHORIZATION COMPANY' , 
	AUTHORIZATIONPMTEXT TEXT IS 'AUTHORIZATION PMT/EXT #' , 
	AUTHORIZATIONFLAG TEXT IS 'AUTH REQUIRED' , 
	VERIFICATIONDATE TEXT IS 'START DATE' , 
	VERIFICATIONFLAG TEXT IS 'VERIFICATION STATUS' , 
	VERIFIEDBY TEXT IS 'VERIFIED BY' , 
	ATTORNEYNAME TEXT IS 'ATTORNEY NAME' , 
	ATTORNEYSTREET TEXT IS 'ATTORNEY STREET' , 
	ATTORNEYCITY TEXT IS 'ATTORNEY CITY' , 
	ATTORNEYSTATE TEXT IS 'ATTORNEY STATE' , 
	ATTORNEYZIP5 TEXT IS 'ATTORNEY ZIP5' , 
	ATTORNEYZIP4 TEXT IS 'ATTORNEY ZIP4' , 
	ATTORNEYCOUNTRYCODE TEXT IS 'ATTORNEY COUNTRY CODE' , 
	ATTORNEYPHONE TEXT IS 'ATTORNEY PHONE #' , 
	AGENTNAME TEXT IS 'AUT/HOM INS AGENT NAME' , 
	AGENTPHONE TEXT IS 'AUT/HOM INS AGENT PH #' , 
	AGENTSTREET TEXT IS 'AGENT STREET' , 
	AGENTCITY TEXT IS 'AGENT CITY' , 
	AGENTSTATE TEXT IS 'AGENT STATE' , 
	AGENTZIP5 TEXT IS 'AGENT ZIP5' , 
	AGENTZIP4 TEXT IS 'AGENT ZIP4' , 
	AGENTCOUNTRYCODE TEXT IS 'AGENT COUNTRY CODE' , 
	BILLINGCAREOFNAME TEXT IS 'C/O NAME' , 
	BILLINGNAME TEXT IS 'BILLING NAME' , 
	TRACKINGNUMBER TEXT IS 'INSURANCE TRACKING#' , 
	ADJUSTERSNAME TEXT IS 'ADJUSTERS NAME' , 
	EMPLOYEESSUPERVISOR TEXT IS 'EMPLOYEES SUPERVISOR' , 
	AUTHCOMPANYREPFIRSTNAME TEXT IS 'AUTH COMPANY REP FIRST NAME' , 
	AUTHCOMPANYREPLASTNAME TEXT IS 'AUTH COMPANY REP LAST NAME' , 
	SERVICESAUTHORIZED TEXT IS 'SERVICES AUTHORIZED' , 
	EFFECTIVEDATEOFAUTH TEXT IS 'EFFECTIVE DATE OF AUTH' , 
	EXPIRATIONDATEOFAUTH TEXT IS 'EXPIRATION DATE OF AUTH' , 
	AUTHORIZATIONSTATUS TEXT IS 'AUTHORIZATION STATUS' , 
	AUTHORIZATIONREMARKS TEXT IS 'AUTHORIZATION REMARKS' , 
	INSURANCECOMPANYNAME TEXT IS 'INSURANCE COMPANY NAME' ) ; 
  
GRANT ALTER , REFERENCES , SELECT   
ON INSURANCES TO RMTGRPPRF WITH GRANT OPTION ; 
  
GRANT ALTER , REFERENCES , SELECT   
ON INSURANCES TO TURNOVER WITH GRANT OPTION ;
