//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace HdiStub.HdiService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'UsingAddressing' from namespace 'http://www.w3.org/2006/02/addressing/wsdl' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PatientAccessSoapBinding", Namespace="http://patientaccess.webservice.cie")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(FUSNote))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(WSRequest))]
    public partial class PatientAccessService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getConnectionSpecForOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPBARAvailabilityForOperationCompleted;
        
        private System.Threading.SendOrPostCallback postRemarksFUSNoteForOperationCompleted;
        
        private System.Threading.SendOrPostCallback postExtendedFUSNoteForOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFUSNotesForOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PatientAccessService() {
            this.Url = global::HdiStub.Properties.Settings.Default.HdiStub_PerotSystems_Hdi_PatientAccessService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getConnectionSpecForCompletedEventHandler getConnectionSpecForCompleted;
        
        /// <remarks/>
        public event getPBARAvailabilityForCompletedEventHandler getPBARAvailabilityForCompleted;
        
        /// <remarks/>
        public event postRemarksFUSNoteForCompletedEventHandler postRemarksFUSNoteForCompleted;
        
        /// <remarks/>
        public event postExtendedFUSNoteForCompletedEventHandler postExtendedFUSNoteForCompleted;
        
        /// <remarks/>
        public event getFUSNotesForCompletedEventHandler getFUSNotesForCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://patientaccess.webservice.cie", ResponseNamespace="http://patientaccess.webservice.cie")]
        [return: System.Xml.Serialization.SoapElementAttribute("getConnectionSpecForReturn")]
        public ConnectionSpecification getConnectionSpecFor(ConnectionSpecRequest arg_0_0) {
            object[] results = this.Invoke("getConnectionSpecFor", new object[] {
                        arg_0_0});
            return ((ConnectionSpecification)(results[0]));
        }
        
        /// <remarks/>
        public void getConnectionSpecForAsync(ConnectionSpecRequest arg_0_0) {
            this.getConnectionSpecForAsync(arg_0_0, null);
        }
        
        /// <remarks/>
        public void getConnectionSpecForAsync(ConnectionSpecRequest arg_0_0, object userState) {
            if ((this.getConnectionSpecForOperationCompleted == null)) {
                this.getConnectionSpecForOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetConnectionSpecForOperationCompleted);
            }
            this.InvokeAsync("getConnectionSpecFor", new object[] {
                        arg_0_0}, this.getConnectionSpecForOperationCompleted, userState);
        }
        
        private void OngetConnectionSpecForOperationCompleted(object arg) {
            if ((this.getConnectionSpecForCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getConnectionSpecForCompleted(this, new getConnectionSpecForCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://patientaccess.webservice.cie", ResponseNamespace="http://patientaccess.webservice.cie")]
        [return: System.Xml.Serialization.SoapElementAttribute("getPBARAvailabilityForReturn")]
        public bool getPBARAvailabilityFor(PBARAvailabilityRequest arg_0_1) {
            object[] results = this.Invoke("getPBARAvailabilityFor", new object[] {
                        arg_0_1});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void getPBARAvailabilityForAsync(PBARAvailabilityRequest arg_0_1) {
            this.getPBARAvailabilityForAsync(arg_0_1, null);
        }
        
        /// <remarks/>
        public void getPBARAvailabilityForAsync(PBARAvailabilityRequest arg_0_1, object userState) {
            if ((this.getPBARAvailabilityForOperationCompleted == null)) {
                this.getPBARAvailabilityForOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPBARAvailabilityForOperationCompleted);
            }
            this.InvokeAsync("getPBARAvailabilityFor", new object[] {
                        arg_0_1}, this.getPBARAvailabilityForOperationCompleted, userState);
        }
        
        private void OngetPBARAvailabilityForOperationCompleted(object arg) {
            if ((this.getPBARAvailabilityForCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPBARAvailabilityForCompleted(this, new getPBARAvailabilityForCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://patientaccess.webservice.cie", ResponseNamespace="http://patientaccess.webservice.cie")]
        [return: System.Xml.Serialization.SoapElementAttribute("postRemarksFUSNoteForReturn")]
        public bool postRemarksFUSNoteFor(RemarksFUSNoteRequest arg_0_2) {
            object[] results = this.Invoke("postRemarksFUSNoteFor", new object[] {
                        arg_0_2});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void postRemarksFUSNoteForAsync(RemarksFUSNoteRequest arg_0_2) {
            this.postRemarksFUSNoteForAsync(arg_0_2, null);
        }
        
        /// <remarks/>
        public void postRemarksFUSNoteForAsync(RemarksFUSNoteRequest arg_0_2, object userState) {
            if ((this.postRemarksFUSNoteForOperationCompleted == null)) {
                this.postRemarksFUSNoteForOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpostRemarksFUSNoteForOperationCompleted);
            }
            this.InvokeAsync("postRemarksFUSNoteFor", new object[] {
                        arg_0_2}, this.postRemarksFUSNoteForOperationCompleted, userState);
        }
        
        private void OnpostRemarksFUSNoteForOperationCompleted(object arg) {
            if ((this.postRemarksFUSNoteForCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.postRemarksFUSNoteForCompleted(this, new postRemarksFUSNoteForCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://patientaccess.webservice.cie", ResponseNamespace="http://patientaccess.webservice.cie")]
        [return: System.Xml.Serialization.SoapElementAttribute("postExtendedFUSNoteForReturn")]
        public bool postExtendedFUSNoteFor(ExtendedFUSNoteRequest arg_0_3) {
            object[] results = this.Invoke("postExtendedFUSNoteFor", new object[] {
                        arg_0_3});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void postExtendedFUSNoteForAsync(ExtendedFUSNoteRequest arg_0_3) {
            this.postExtendedFUSNoteForAsync(arg_0_3, null);
        }
        
        /// <remarks/>
        public void postExtendedFUSNoteForAsync(ExtendedFUSNoteRequest arg_0_3, object userState) {
            if ((this.postExtendedFUSNoteForOperationCompleted == null)) {
                this.postExtendedFUSNoteForOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpostExtendedFUSNoteForOperationCompleted);
            }
            this.InvokeAsync("postExtendedFUSNoteFor", new object[] {
                        arg_0_3}, this.postExtendedFUSNoteForOperationCompleted, userState);
        }
        
        private void OnpostExtendedFUSNoteForOperationCompleted(object arg) {
            if ((this.postExtendedFUSNoteForCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.postExtendedFUSNoteForCompleted(this, new postExtendedFUSNoteForCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://patientaccess.webservice.cie", ResponseNamespace="http://patientaccess.webservice.cie")]
        [return: System.Xml.Serialization.SoapElementAttribute("getFUSNotesForReturn")]
        public FUSNote1[] getFUSNotesFor(ReadFUSNotesRequest arg_0_4) {
            object[] results = this.Invoke("getFUSNotesFor", new object[] {
                        arg_0_4});
            return ((FUSNote1[])(results[0]));
        }
        
        /// <remarks/>
        public void getFUSNotesForAsync(ReadFUSNotesRequest arg_0_4) {
            this.getFUSNotesForAsync(arg_0_4, null);
        }
        
        /// <remarks/>
        public void getFUSNotesForAsync(ReadFUSNotesRequest arg_0_4, object userState) {
            if ((this.getFUSNotesForOperationCompleted == null)) {
                this.getFUSNotesForOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFUSNotesForOperationCompleted);
            }
            this.InvokeAsync("getFUSNotesFor", new object[] {
                        arg_0_4}, this.getFUSNotesForOperationCompleted, userState);
        }
        
        private void OngetFUSNotesForOperationCompleted(object arg) {
            if ((this.getFUSNotesForCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFUSNotesForCompleted(this, new getFUSNotesForCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://domain.patientaccess.webservice.cie")]
    public partial class ConnectionSpecRequest : WSHospitalRequest {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(WSPatientSpecificRequest))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ReadFUSNotesRequest))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(PBARAvailabilityRequest))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ConnectionSpecRequest))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(FUSNoteRequest))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ExtendedFUSNoteRequest))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemarksFUSNoteRequest))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ExtendedRemarksFUSNoteRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://domain.webservice.cie")]
    public abstract partial class WSHospitalRequest : WSRequest {
        
        private string hospitalCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string hospitalCode {
            get {
                return this.hospitalCodeField;
            }
            set {
                this.hospitalCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(WSHospitalRequest))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(WSPatientSpecificRequest))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ReadFUSNotesRequest))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(PBARAvailabilityRequest))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ConnectionSpecRequest))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(FUSNoteRequest))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ExtendedFUSNoteRequest))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemarksFUSNoteRequest))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ExtendedRemarksFUSNoteRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://domain.webservice.cie")]
    public abstract partial class WSRequest {
        
        private string clientGUIDField;
        
        private string userIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string clientGUID {
            get {
                return this.clientGUIDField;
            }
            set {
                this.clientGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string userID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(FUSNote1))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://fusnote.domain.webservice.cie")]
    public partial class FUSNote {
        
        private string activityCodeField;
        
        private string descriptionField;
        
        private System.Nullable<System.DateTime> entryDateTimeField;
        
        private string keyedByField;
        
        private string[] medicalRecordNumbersField;
        
        private string remarksField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string activityCode {
            get {
                return this.activityCodeField;
            }
            set {
                this.activityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> entryDateTime {
            get {
                return this.entryDateTimeField;
            }
            set {
                this.entryDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string keyedBy {
            get {
                return this.keyedByField;
            }
            set {
                this.keyedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string[] medicalRecordNumbers {
            get {
                return this.medicalRecordNumbersField;
            }
            set {
                this.medicalRecordNumbersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(TypeName="FUSNote", Namespace="http://domain.patientaccess.webservice.cie")]
    public partial class FUSNote1 : FUSNote {
        
        private System.Nullable<decimal> amount1Field;
        
        private System.Nullable<decimal> amount2Field;
        
        private System.Nullable<System.DateTime> date1Field;
        
        private System.Nullable<System.DateTime> date2Field;
        
        private string noteTypeField;
        
        private System.Nullable<System.DateTime> workListDateField;
        
        private string extensionMonthField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> amount1 {
            get {
                return this.amount1Field;
            }
            set {
                this.amount1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> amount2 {
            get {
                return this.amount2Field;
            }
            set {
                this.amount2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> date1 {
            get {
                return this.date1Field;
            }
            set {
                this.date1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> date2 {
            get {
                return this.date2Field;
            }
            set {
                this.date2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string noteType {
            get {
                return this.noteTypeField;
            }
            set {
                this.noteTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> workListDate {
            get {
                return this.workListDateField;
            }
            set {
                this.workListDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string extensionMonth {
            get {
                return this.extensionMonthField;
            }
            set {
                this.extensionMonthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://domain.patientaccess.webservice.cie")]
    public partial class ConnectionSpecification {
        
        private string hubNameField;
        
        private string descriptionField;
        
        private string ipAddressField;
        
        private string hospitalCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string hubName {
            get {
                return this.hubNameField;
            }
            set {
                this.hubNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ipAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string hospitalCode {
            get {
                return this.hospitalCodeField;
            }
            set {
                this.hospitalCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ReadFUSNotesRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://domain.webservice.cie")]
    public partial class WSPatientSpecificRequest : WSHospitalRequest {
        
        private string accountNumberField;
        
        private string medicalRecordNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string medicalRecordNumber {
            get {
                return this.medicalRecordNumberField;
            }
            set {
                this.medicalRecordNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://fusnote.domain.webservice.cie")]
    public partial class ReadFUSNotesRequest : WSPatientSpecificRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://domain.patientaccess.webservice.cie")]
    public partial class PBARAvailabilityRequest : WSHospitalRequest {
        
        private bool onlineUpCheckField;
        
        /// <remarks/>
        public bool onlineUpCheck {
            get {
                return this.onlineUpCheckField;
            }
            set {
                this.onlineUpCheckField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ExtendedFUSNoteRequest))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemarksFUSNoteRequest))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ExtendedRemarksFUSNoteRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://fusnote.domain.webservice.cie")]
    public partial class FUSNoteRequest : WSHospitalRequest {
        
        private string accountNumberField;
        
        private string activityCodeField;
        
        private System.Nullable<System.DateTime> serviceDateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string activityCode {
            get {
                return this.activityCodeField;
            }
            set {
                this.activityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> serviceDateTime {
            get {
                return this.serviceDateTimeField;
            }
            set {
                this.serviceDateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://fusnote.domain.webservice.cie")]
    public partial class ExtendedFUSNoteRequest : FUSNoteRequest {
        
        private System.Nullable<decimal> amount1Field;
        
        private System.Nullable<decimal> amount2Field;
        
        private System.Nullable<System.DateTime> date1Field;
        
        private System.Nullable<System.DateTime> date2Field;
        
        private System.Nullable<System.DateTime> workListDateField;
        
        private string extensionMonthField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> amount1 {
            get {
                return this.amount1Field;
            }
            set {
                this.amount1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> amount2 {
            get {
                return this.amount2Field;
            }
            set {
                this.amount2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> date1 {
            get {
                return this.date1Field;
            }
            set {
                this.date1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> date2 {
            get {
                return this.date2Field;
            }
            set {
                this.date2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> workListDate {
            get {
                return this.workListDateField;
            }
            set {
                this.workListDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string extensionMonth {
            get {
                return this.extensionMonthField;
            }
            set {
                this.extensionMonthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ExtendedRemarksFUSNoteRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://fusnote.domain.webservice.cie")]
    public partial class RemarksFUSNoteRequest : FUSNoteRequest {
        
        private string remarksField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string remarks {
            get {
                return this.remarksField;
            }
            set {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://fusnote.domain.webservice.cie")]
    public partial class ExtendedRemarksFUSNoteRequest : RemarksFUSNoteRequest {
        
        private System.Nullable<decimal> amount1Field;
        
        private System.Nullable<decimal> amount2Field;
        
        private System.Nullable<System.DateTime> date1Field;
        
        private System.Nullable<System.DateTime> date2Field;
        
        private System.Nullable<System.DateTime> workListDateField;
        
        private string extensionMonthField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> amount1 {
            get {
                return this.amount1Field;
            }
            set {
                this.amount1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> amount2 {
            get {
                return this.amount2Field;
            }
            set {
                this.amount2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> date1 {
            get {
                return this.date1Field;
            }
            set {
                this.date1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> date2 {
            get {
                return this.date2Field;
            }
            set {
                this.date2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> workListDate {
            get {
                return this.workListDateField;
            }
            set {
                this.workListDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string extensionMonth {
            get {
                return this.extensionMonthField;
            }
            set {
                this.extensionMonthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getConnectionSpecForCompletedEventHandler(object sender, getConnectionSpecForCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getConnectionSpecForCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getConnectionSpecForCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConnectionSpecification Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConnectionSpecification)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getPBARAvailabilityForCompletedEventHandler(object sender, getPBARAvailabilityForCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPBARAvailabilityForCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPBARAvailabilityForCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void postRemarksFUSNoteForCompletedEventHandler(object sender, postRemarksFUSNoteForCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class postRemarksFUSNoteForCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal postRemarksFUSNoteForCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void postExtendedFUSNoteForCompletedEventHandler(object sender, postExtendedFUSNoteForCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class postExtendedFUSNoteForCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal postExtendedFUSNoteForCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void getFUSNotesForCompletedEventHandler(object sender, getFUSNotesForCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFUSNotesForCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFUSNotesForCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FUSNote1[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FUSNote1[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591