using System;
using System.Configuration;
using System.Net;
using PatientAccess.Services;

namespace PatientAccess.ComplianceCheckerProxy
{

    /// <summary>
    /// This contains augmentations for the ComplianceCheckerService generated by the web reference
    /// </summary>
    public partial class ComplianceCheckerService : IComplianceCheckerService 
    {

        #region Construction & Finalization

        /// <summary>
        /// Initializes a new instance of the <see cref="ComplianceCheckerService"/> class.
        /// </summary>
        /// <param name="serviceUrl">The service URL.</param>
        /// <remarks>
        /// Setting the url on construction will allow us to keep from manually editing the
        /// generated stub code to place the Peradigm configuration code in it.
        /// </remarks>
        public ComplianceCheckerService( string serviceUrl ) : base()
        {

            base.Url = serviceUrl;

        }//method


        /// <summary>
        /// Gets the web request.
        /// </summary>
        /// <param name="uri">The URI.</param>
        /// <returns></returns>
        /// <remarks>
        /// This allows us to stay functioning in a load balanced environment
        /// </remarks>
        protected override WebRequest GetWebRequest( Uri uri )
        {

            HttpWebRequest webRequest = (HttpWebRequest)base.GetWebRequest( uri );

            if( ( null != ConfigurationManager.AppSettings["WEB_REQUEST_DEFAULTS"] ) &&
                ( !bool.Parse( ConfigurationManager.AppSettings["WEB_REQUEST_DEFAULTS"] ) ) )
            {

                webRequest.KeepAlive = 
                    bool.Parse( ConfigurationManager.AppSettings["WEB_REQUEST_KEEP_ALIVE"] );
                webRequest.ProtocolVersion = 
                    new Version( ConfigurationManager.AppSettings["WEB_REQUEST_PROTOCOL_VERSION"] );

            }//if

            return webRequest;

        }//method

        #endregion

    }//class

}//namespace
