//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePreRegistrationDataCreator.PatientAccess.OnlinePreRegistration {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PatientAccess.OnlinePreRegistration.PreRegistrationHandlerServiceSoap")]
    public interface PreRegistrationHandlerServiceSoap {
        
        // CODEGEN: Generating message contract since element name message from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcessMessage", ReplyAction="*")]
        OnlinePreRegistrationDataCreator.PatientAccess.OnlinePreRegistration.ProcessMessageResponse ProcessMessage(OnlinePreRegistrationDataCreator.PatientAccess.OnlinePreRegistration.ProcessMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessMessage", Namespace="http://tempuri.org/", Order=0)]
        public OnlinePreRegistrationDataCreator.PatientAccess.OnlinePreRegistration.ProcessMessageRequestBody Body;
        
        public ProcessMessageRequest() {
        }
        
        public ProcessMessageRequest(OnlinePreRegistrationDataCreator.PatientAccess.OnlinePreRegistration.ProcessMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string messageType;
        
        public ProcessMessageRequestBody() {
        }
        
        public ProcessMessageRequestBody(string message, string messageType) {
            this.message = message;
            this.messageType = messageType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlinePreRegistrationDataCreator.PatientAccess.OnlinePreRegistration.ProcessMessageResponseBody Body;
        
        public ProcessMessageResponse() {
        }
        
        public ProcessMessageResponse(OnlinePreRegistrationDataCreator.PatientAccess.OnlinePreRegistration.ProcessMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ProcessMessageResponseBody {
        
        public ProcessMessageResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PreRegistrationHandlerServiceSoapChannel : OnlinePreRegistrationDataCreator.PatientAccess.OnlinePreRegistration.PreRegistrationHandlerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PreRegistrationHandlerServiceSoapClient : System.ServiceModel.ClientBase<OnlinePreRegistrationDataCreator.PatientAccess.OnlinePreRegistration.PreRegistrationHandlerServiceSoap>, OnlinePreRegistrationDataCreator.PatientAccess.OnlinePreRegistration.PreRegistrationHandlerServiceSoap {
        
        public PreRegistrationHandlerServiceSoapClient() {
        }
        
        public PreRegistrationHandlerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PreRegistrationHandlerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PreRegistrationHandlerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PreRegistrationHandlerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlinePreRegistrationDataCreator.PatientAccess.OnlinePreRegistration.ProcessMessageResponse OnlinePreRegistrationDataCreator.PatientAccess.OnlinePreRegistration.PreRegistrationHandlerServiceSoap.ProcessMessage(OnlinePreRegistrationDataCreator.PatientAccess.OnlinePreRegistration.ProcessMessageRequest request) {
            return base.Channel.ProcessMessage(request);
        }
        
        public void ProcessMessage(string message, string messageType) {
            OnlinePreRegistrationDataCreator.PatientAccess.OnlinePreRegistration.ProcessMessageRequest inValue = new OnlinePreRegistrationDataCreator.PatientAccess.OnlinePreRegistration.ProcessMessageRequest();
            inValue.Body = new OnlinePreRegistrationDataCreator.PatientAccess.OnlinePreRegistration.ProcessMessageRequestBody();
            inValue.Body.message = message;
            inValue.Body.messageType = messageType;
            OnlinePreRegistrationDataCreator.PatientAccess.OnlinePreRegistration.ProcessMessageResponse retVal = ((OnlinePreRegistrationDataCreator.PatientAccess.OnlinePreRegistration.PreRegistrationHandlerServiceSoap)(this)).ProcessMessage(inValue);
        }
    }
}
