
-- define table
CREATE TABLE MEDICAREPLANHSVXREF ( 
	SERVICECODE	VARCHAR(2), 
	PLANID		VARCHAR(12) ) ; 	-- populate dataDELETE FROM MEDICAREPLANHSVXREF;

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('SB', '5354C');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('SB', 'VE30C');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('SB', 'VE35C');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('SB', 'VE38C');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('SB', 'VE37C');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('SB', 'VE33C');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('SB', '5354S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('SB', 'VE30S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('SB', 'VE38S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('SB', 'VE37S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('SB', 'VE33S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('SB', 'VE35S');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('VB', '5354S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('VB', 'VE30S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('VB', 'VE38S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('VB', 'VE37S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('VB', 'VE33S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('VB', 'VE35S');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('VE', '5354S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('VE', 'VE30S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('VE', 'VE38S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('VE', 'VE37S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('VE', 'VE33S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('VE', 'VE35S');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('08', '5354P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('08', 'VE30P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('08', 'VE38P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('08', 'VE37P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('08', 'VE33P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('08', 'VE35P');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('09', '5354P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('09', 'VE30P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('09', 'VE38P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('09', 'VE37P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('09', 'VE33P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('09', 'VE35P');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('14', '5354P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('14', 'VE30P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('14', 'VE38P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('14', 'VE37P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('14', 'VE33P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('14', 'VE35P');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('15', '5354P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('15', 'VE30P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('15', 'VE38P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('15', 'VE37P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('15', 'VE33P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('15', 'VE35P');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('24', '5354P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('24', 'VE30P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('24', 'VE38P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('24', 'VE37P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('24', 'VE33P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('24', 'VE35P');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('28', '5354P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('28', 'VE30P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('28', 'VE38P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('28', 'VE37P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('28', 'VE33P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('28', 'VE35P');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('29', '5354P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('29', 'VE30P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('29', 'VE38P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('29', 'VE37P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('29', 'VE33P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('29', 'VE35P');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('66', '5354R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('66', 'VE30R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('66', 'VE38R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('66', 'VE37R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('66', 'VE33R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('66', 'VE35R');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('67', '5354R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('67', 'VE30R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('67', 'VE38R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('67', 'VE37R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('67', 'VE33R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('67', 'VE35R');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('68', '5354R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('68', 'VE30R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('68', 'VE38R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('68', 'VE37R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('68', 'VE33R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('68', 'VE35R');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('69', '5354R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('69', 'VE30R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('69', 'VE38R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('69', 'VE37R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('69', 'VE33R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('69', 'VE35R');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('70', '5354R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('70', 'VE30R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('70', 'VE38R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('70', 'VE37R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('70', 'VE33R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('70', 'VE35R');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('71', '5354R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('71', 'VE30R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('71', 'VE38R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('71', 'VE37R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('71', 'VE33R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('71', 'VE35R');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('72', '5354P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('72', 'VE30P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('72', 'VE38P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('72', 'VE37P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('72', 'VE33P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('72', 'VE35P');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('73', '5354R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('73', 'VE30R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('73', 'VE38R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('73', 'VE37R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('73', 'VE33R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('73', 'VE35R');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('74', '5354R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('74', 'VE30R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('74', 'VE38R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('74', 'VE37R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('74', 'VE33R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('74', 'VE35R');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('75', '5354R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('75', 'VE30R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('75', 'VE38R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('75', 'VE37R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('75', 'VE33R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('75', 'VE35R');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('76', '5354R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('76', 'VE30R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('76', 'VE38R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('76', 'VE37R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('76', 'VE33R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('76', 'VE35R');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('77', '5354R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('77', 'VE30R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('77', 'VE38R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('77', 'VE37R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('77', 'VE33R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('77', 'VE35R');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('78', '5354R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('78', 'VE30R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('78', 'VE38R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('78', 'VE37R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('78', 'VE33R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('78', 'VE35R');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('79', '5354R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('79', 'VE30R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('79', 'VE38R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('79', 'VE37R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('79', 'VE33R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('79', 'VE35R');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('81', '5354R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('81', 'VE30R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('81', 'VE38R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('81', 'VE37R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('81', 'VE33R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('81', 'VE35R');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('82', '5354R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('82', 'VE30R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('82', 'VE38R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('82', 'VE37R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('82', 'VE33R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('82', 'VE35R');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('83', '5354R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('83', 'VE30R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('83', 'VE38R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('83', 'VE37R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('83', 'VE33R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('83', 'VE35R');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('84', '5354R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('84', 'VE30R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('84', 'VE38R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('84', 'VE37R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('84', 'VE33R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('84', 'VE35R');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('85', '5354R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('85', 'VE30R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('85', 'VE38R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('85', 'VE37R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('85', 'VE33R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('85', 'VE35R');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('88', '5354D');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('88', 'VE30D');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('88', 'VE35D');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('88', 'VE38D');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('88', 'VE37D');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('88', 'VE33D');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('89', '5354R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('89', 'VE30R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('89', 'VE38R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('89', 'VE37R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('89', 'VE33R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('89', 'VE35R');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('92', '5354R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('92', 'VE30R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('92', 'VE38R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('92', 'VE37R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('92', 'VE33R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('92', 'VE35R');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('95', '5354S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('95', 'VE30S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('95', 'VE38S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('95', 'VE37S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('95', 'VE33S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('95', 'VE35S');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('96', '5354S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('96', 'VE30S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('96', 'VE38S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('96', 'VE37S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('96', 'VE33S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('96', 'VE35S');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('97', '5354S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('97', 'VE30S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('97', 'VE38S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('97', 'VE37S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('97', 'VE33S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('97', 'VE35S');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('98', '5354S')  ;
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('98', 'VE30S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('98', 'VE38S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('98', 'VE37S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('98', 'VE33S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('98', 'VE35S');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('98', '5354R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('98', 'VE30R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('98', 'VE38R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('98', 'VE37R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('98', 'VE33R');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('98', 'VE35R');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('99', '5354S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('99', 'VE30S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('99', 'VE38S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('99', 'VE37S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('99', 'VE33S');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('99', 'VE35S');

INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('99', '5354P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('99', 'VE30P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('99', 'VE38P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('99', 'VE37P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('99', 'VE33P');
INSERT INTO MEDICAREPLANHSVXREF ( SERVICECODE,PLANID ) VALUES ('99', 'VE35P');
  