/*************I********************************************************/        
/*            I                                                       */        
/* iSeries400 I  HSVBENEFITCATEGORYXREF - TABLE FOR PATIENT ACCESS    */      
/*            I                                                       */        
/*    ************************************************************    */        
/*    * Perot Systems, Copyright 2003, All rights reserved(U.S.) *    */        
/*    *       I                                                  *    */        
/*    * This unpublished material is proprietary to Perot Sys.   *    */        
/*    * The methods and techniques described herein are          *    */        
/*    * considered trade secrets and/or confidential.            *    */        
/*    * Reproduction or distribution, in whole or in part, is    *    */        
/*    * forbidden except by express written permission of        *    */        
/*    * Perot Systems, Inc.                                      *    */        
/*    ************************************************************    */        
/*            I                                                       */        
/*************I********************I***********************************/        
/*  Date      I  Programmer        I  Modification Description        */        
/*************I********************I***********************************/        
/* 02/04/2008 I  Jenney Alexandria      I NEW TABLE CREATION          */        
/*************I********************I***********************************/ 
----------------------------------------------------------------------------------------
-- define table

CREATE TABLE HSVBENEFITCATEGORYXREF (
	SERVICECODE			FOR COLUMN SRVCD VARCHAR(10) CCSID 37 DEFAULT NULL ,
	BENEFITCATEGORYID	FOR COLUMN BNTCTGRYID INTEGER DEFAULT NULL,
						CONSTRAINT FK_BENEFITCATEGORYID
						FOREIGN KEY( BENEFITCATEGORYID )
	REFERENCES BENEFITCATEGORIES ( BENEFITCATEGORYID )
	ON DELETE NO ACTION
	ON UPDATE RESTRICT) ;
	
RENAME HSVBENEFITCATEGORYXREF TO SYSTEM NAME HSVBNCTGYX;

-----------------------------------------------------------------------------------------	
-- populate data	
	
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('AB', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('CI', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('CO', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('C1', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('C2', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('FA', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('IJ', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('LB', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('LD', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('RS', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('SB', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('SP', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('TC', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('VB', 9);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('VD', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('VE', 9);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('WA', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('01', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('02', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('03', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('04', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('05', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('06', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('07', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('08', 7);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('09', 7);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('10', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('11', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('12', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('13', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('14', 6);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('15', 6);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('16', 4);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('16', 3);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('17', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('19', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('21', 8);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('21', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('22', 10);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('23', 6);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('24', 6);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('25', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('26', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('27', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('28', 6);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('29', 6);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('30', 4);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('31', 5);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('34', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('35', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('36', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('37', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('38', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('39', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('40', 5);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('41', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('42', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('43', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('44', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('45', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('46', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('47', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('48', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('49', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('50', 1);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('51', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('52', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('53', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('54', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('55', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('56', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('58', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('59', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('60', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('61', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('62', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('63', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('64', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('65', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('66', 10);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('67', 10);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('68', 10);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('69', 11);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('70', 10);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('71', 10);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('72', 8);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('73', 10);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('74', 10);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('75', 10);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('76', 10);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('77', 10);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('78', 10);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('79', 10);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('80', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('81', 10);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('82', 10);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('83', 10);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('84', 10);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('85', 10);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('86', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('87', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('88', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('89', 10);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('91', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('92', 10);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('93', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('94', 2);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('95', 9);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('96', 9);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('97', 9);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('98', 10);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('99', 6);
INSERT INTO HSVBENEFITCATEGORYXREF (SERVICECODE, BENEFITCATEGORYID) VALUES ('86', 1);
