-- Sophie 01/16/2008
----------------------------------------------------------------------------------------
-- define table

CREATE TABLE PLANCATEGORIES ( 
	PLANCATEGORYID					FOR COLUMN PLNCTGRYID INTEGER NOT NULL , 
	PLANCATEGORYDESCRIPTION			FOR COLUMN PLNCTGRYDE VARCHAR(32), 
	EXPECTEDASSOCIATEDNUMBERLABEL	FOR COLUMN NMBRLBL    VARCHAR(32), 
	DISPLAYORDER					FOR COLUMN DSPLYRDR   INTEGER, 
	CONSTRAINT PK_PLANCATEGORYID PRIMARY KEY( PLANCATEGORYID ) ) ;
	
-----------------------------------------------------------------------------------------	
-- populate data	
	
INSERT INTO PLANCATEGORIES ( PLANCATEGORYID, PLANCATEGORYDESCRIPTION, EXPECTEDASSOCIATEDNUMBERLABEL, DISPLAYORDER ) 
VALUES ( 1, 'Commercial/Managed care', 'Cert/SSN/ID Number', 1); 

INSERT INTO PLANCATEGORIES ( PLANCATEGORYID, PLANCATEGORYDESCRIPTION, EXPECTEDASSOCIATEDNUMBERLABEL, DISPLAYORDER ) 
VALUES ( 2, 'Government-Miscellaneous', 'Cert/SSN/ID Number', 4); 

INSERT INTO PLANCATEGORIES ( PLANCATEGORYID, PLANCATEGORYDESCRIPTION, EXPECTEDASSOCIATEDNUMBERLABEL, DISPLAYORDER ) 
VALUES ( 3, 'Government-Medicare', 'HIC Number', 3); 

INSERT INTO PLANCATEGORIES ( PLANCATEGORYID, PLANCATEGORYDESCRIPTION, EXPECTEDASSOCIATEDNUMBERLABEL, DISPLAYORDER ) 
VALUES ( 4, 'Government-Medicaid', 'Policy/CIN Number', 2); 

INSERT INTO PLANCATEGORIES ( PLANCATEGORYID, PLANCATEGORYDESCRIPTION, EXPECTEDASSOCIATEDNUMBERLABEL, DISPLAYORDER ) 
VALUES ( 5, 'Self-pay', NULL, 7); 

INSERT INTO PLANCATEGORIES ( PLANCATEGORYID, PLANCATEGORYDESCRIPTION, EXPECTEDASSOCIATEDNUMBERLABEL, DISPLAYORDER ) 
VALUES ( 6, 'Workers compensation', 'Policy Number', 5); 

INSERT INTO PLANCATEGORIES ( PLANCATEGORYID, PLANCATEGORYDESCRIPTION, EXPECTEDASSOCIATEDNUMBERLABEL, DISPLAYORDER ) 
VALUES ( 7, 'Miscellaneous', 'Cert/SSN/ID Number', 6); 
