-- Sophie 01/16/2008
----------------------------------------------------------------------------------------
-- define table

CREATE TABLE PLANCATEGORYXREF ( 
	SUFFIXSTRING FOR COLUMN SFFXSTR    VARCHAR(2), 
	PLANCATEGORYID FOR COLUMN PLNCTGRYID INTEGER );
	
-----------------------------------------------------------------------------------------	
-- populate data	
	
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( '01', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( '05', 6); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( '0O', 6); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( '0Q', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( '0*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( '1*', 2); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( '31', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( '32', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( '33', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( '34', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( '35', 6); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( '36', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( '37', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( '38', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( '3O', 6); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( '3*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( '4*', 3); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( '5*', 4); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( '6*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( '7*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( '8*', 5); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'C*', 5); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'E*', 2); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'I*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'J*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'K*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'M*', 2); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'N*', 2); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'O*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'P*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'Q5', 6); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'Q*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'R*', 2); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( '2*', 6); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( '9*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'H*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'L*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'Y*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'A*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'B*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'D*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'F*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'G*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'S*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'T*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'U*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'V*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'W*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'X*', 1); 
INSERT INTO PLANCATEGORYXREF ( SUFFIXSTRING, PLANCATEGORYID ) VALUES ( 'Z*', 7); 