--  Generate SQL 
--  Version:                   	V5R3M0 040528 
--  Generated on:              	12/07/06 17:23:35 
--  Relational Database:       	DVLA 
--  Standards Option:          	DB2 UDB iSeries 
  
CREATE TABLE ACCOUNTWORKLISTITEMS ( 
--  SQL1509   10   Format name ACCOU00002 for ACCOUNTWORKLISTITEMS in PACCESS ignored. 
	WORKLISTITEMID FOR COLUMN WORKL00001 INTEGER GENERATED ALWAYS AS IDENTITY ( 
	START WITH 1 INCREMENT BY 1 
	NO MINVALUE NO MAXVALUE 
	NO CYCLE NO ORDER 
	CACHE 20 ) 
	, 
	FACILITYID INTEGER DEFAULT NULL , 
	ACCOUNTNUMBER FOR COLUMN ACCOU00001 INTEGER DEFAULT NULL , 
	WORKLISTID INTEGER DEFAULT NULL , 
	COMPOSITERULEID FOR COLUMN COMPO00001 INTEGER DEFAULT NULL , 
	RULEID INTEGER DEFAULT NULL ) ;   
CREATE TABLE REMAININGACTIONS ( 
	ACTIONID INTEGER DEFAULT NULL , 
	WORKLISTITEMID FOR COLUMN WORKL00001 INTEGER DEFAULT NULL ) ; 
  
CREATE TABLE WORKLISTITEMS ( 
--  SQL1509   10   Format name WORKL00001 for WORKLISTITEMS in PACCESS ignored. 
	WORKLISTITEMID FOR COLUMN WORKL00001 INTEGER NOT NULL , 
	WORKLISTID INTEGER DEFAULT NULL , 
	FACILITYID INTEGER DEFAULT NULL , 
	ACCOUNTNUMBER FOR COLUMN ACCOU00001 INTEGER DEFAULT NULL ) ; 
  
CREATE TABLE WORKLISTRANGES ( 
--  SQL1509   10   Format name WORKL00003 for WORKLISTRANGES in PACCESS ignored. 
	WORKLISTID INTEGER NOT NULL , 
	WORKLISTSELECTIONRANGEID FOR COLUMN WORKL00001 INTEGER NOT NULL ) ; 
  
CREATE TABLE WORKLISTS ( 
	WORKLISTID INTEGER NOT NULL , 
	WORKLISTNAME FOR COLUMN WORKL00001 VARCHAR(150) CCSID 37 DEFAULT NULL ) ; 
  
CREATE TABLE WORKLISTSELECTIONRANGES ( 
--  SQL1509   10   Format name WORKL00004 for WORKLISTSELECTIONRANGES in PACCESS ignored. 
	WORKLISTSELECTIONRANGEID FOR COLUMN WORKL00001 INTEGER NOT NULL , 
	DESCRIPTION FOR COLUMN DESCR00001 VARCHAR(50) CCSID 37 DEFAULT NULL , 
	RANGEINDAYS FOR COLUMN RANGE00001 INTEGER DEFAULT NULL , 
	DISPLAYORDER FOR COLUMN DISPL00001 INTEGER DEFAULT NULL ) ;
