// <copyright file="DiagnosisViewPresenterTests.TestHandleProcedureField_WhenActivityIsPreRegistration.g.cs" company="Perot Systems Corporation">Copyright © Perot Systems Corporation 2007</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Tests.Unit.PatientAccess.UI.DiagnosisViews
{
    public partial class DiagnosisViewPresenterTests
    {
       
        [TestMethod]
        [PexGeneratedBy(typeof(DiagnosisViewPresenterTests))]
        public void TestHandleProcedureField_WhenActivityIsPreReg01()
        {
            this.TestHandleProcedureField_WhenActivityIsPreRegistration("0", true);
        }
    
    }
}
