// <copyright file="DiagnosisViewPresenterTests.TestEnabledOrDisableProcedure_WhenActivityIsRegistration.g.cs" company="Perot Systems Corporation">Copyright © Perot Systems Corporation 2007</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace Tests.Unit.PatientAccess.UI.DiagnosisViews
{
    public partial class DiagnosisViewPresenterTests
    {
        [TestMethod]
        [PexGeneratedBy(typeof(DiagnosisViewPresenterTests))]
        public void TestEnableOrDisableProcedure_WhenActivityIsReg()
        {
            this.TestEnabledOrDisableProcedure_WhenActivityIsRegistration("1" );
        }
        [TestMethod]
        [PexGeneratedBy(typeof(DiagnosisViewPresenterTests))]
        public void TestEnableOrDisableProcedure_WhenActivityIsReg02()
        {
            this.TestEnabledOrDisableProcedure_WhenActivityIsRegistration("9" );
        }
        [TestMethod]
        [PexGeneratedBy(typeof(DiagnosisViewPresenterTests))]
        public void TestEnableOrDisableProcedure_WhenActivityIsReg03()
        {
            this.TestEnabledOrDisableProcedure_WhenActivityIsRegistration("4" );
        }
        [TestMethod]
        [PexGeneratedBy(typeof(DiagnosisViewPresenterTests))]
        public void TestEnableOrDisableProcedure_WhenActivityIsReg04()
        {
            this.TestEnabledOrDisableProcedure_WhenActivityIsRegistration("2" );
        }
        [TestMethod]
        [PexGeneratedBy(typeof(DiagnosisViewPresenterTests))]
        public void TestEnableOrDisableProcedure_WhenActivityIsReg05()
        {
            this.TestEnabledOrDisableProcedure_WhenActivityIsRegistration("3" );
        }
    }
}
