/*************I********************************************************/
/*            I                                                       */
/* iSeries400 I  ACCOUNTS  - SQL VIEW FOR PATIENT ACCESS              */
/*            I                                                       */
/*    ************************************************************    */
/*    * Perot Systems, Copyright 2003, All rights reserved(U.S.) *    */
/*    *       I                                                  *    */
/*    * This unpublished material is proprietary to Perot Sys.   *    */
/*    * The methods and techniques described herein are          *    */
/*    * considered trade secrets and/or confidential.            *    */
/*    * Reproduction or distribution, in whole or in part, is    *    */
/*    * forbidden except by express written permission of        *    */
/*    * Perot Systems, Inc.                                      *    */
/*    ************************************************************    */
/*            I                                                       */
/*************I********************I***********************************/
/*  Date      I  Programmer        I  Modification Description        */
/*************I********************I***********************************/
/* 12/07/2006 I                    I Implement View in Turnover       */
/*************I********************I***********************************/
SET PATH *LIBL;

CREATE VIEW &LIBRARY/ACCOUNTS (
	FACILITYID ,
	PAT_ACCT_NUM FOR COLUMN PAT_A00001 ,
	MED_RECORD_NUM FOR COLUMN MED_R00001 ,
	PAT_LAST_NAME FOR COLUMN PAT_L00001 ,
	PAT_FIRST_NAME FOR COLUMN PAT_F00001 ,
	RELIGION_CODE FOR COLUMN RELIG00001 ,
	INPAT_OUTPAT_FLAG FOR COLUMN INPAT00001 ,
	GUARANTOR_NUM FOR COLUMN GUARA00001 ,
	ATTENDING_DR_NUM FOR COLUMN ATTEN00001 ,
	MED_SERVICE_CODE FOR COLUMN MED_S00001 ,
	ABSTRACT_REQUIRED FOR COLUMN ABSTR00001 ,
	MONTH_OF_ADMISSION FOR COLUMN MONTH00001 ,
	DAY_OF_ADMISSION FOR COLUMN DAY_O00001 ,
	YEAR_OF_ADMISSION FOR COLUMN YEAR_00001 ,
	TIME_OF_ADMISSION FOR COLUMN TIME_00001 ,
	DISCH_DATE ,
	TIME_OF_DISCH FOR COLUMN TIME_00002 ,
	TYPE_OF_CERT FOR COLUMN TYPE_00001 ,
	DAYS_PER_CERT FOR COLUMN DAYS_00001 ,
	START_DATE_FOR_CURRENT_CERT FOR COLUMN START00001 ,
	NEXT_CERTIFICATION_DATE FOR COLUMN NEXT_00001 ,
	DAYS_IN_INITIAL_CERT FOR COLUMN DAYS_00002 ,
	NUM_OF_EXTENSIONS FOR COLUMN NUM_O00001 ,
	TOTAL_CERTIFIED_DAYS FOR COLUMN TOTAL00001 ,
	ADMITTING_CATEGORY FOR COLUMN ADMIT00001 ,
	NURSING_STATION FOR COLUMN NURSI00001 ,
	ROOM_NUM ,
	BED_NUM ,
	RESERVED_FIELD_2_POSITION FOR COLUMN RESER00001 ,
	PAT_TYPE ,
	ROOM_RATE ,
	ROOM_CHG_CHARGE_DESC_NUM FOR COLUMN ROOM_00001 ,
	ISOLATION_CODE FOR COLUMN ISOLA00001 ,
	CONDITION_CODE FOR COLUMN CONDI00001 ,
	NUM_OF_VISITS FOR COLUMN NUM_O00002 ,
	OP_VISIT_NUM FOR COLUMN OP_VI00001 ,
	LAST_CYCLE_BILL_NUM FOR COLUMN LAST_00001 ,
	HOW_ARRIVED FOR COLUMN HOW_A00001 ,
	DIAGNOSIS ,
	CODED_DIAGNOSIS01 FOR COLUMN CODED00001 ,
	CODED_DIAGNOSIS02 FOR COLUMN CODED00002 ,
	CODED_DIAGNOSIS03 FOR COLUMN CODED00003 ,
	CODED_DIAGNOSIS04 FOR COLUMN CODED00004 ,
	CODED_DIAGNOSIS05 FOR COLUMN CODED00005 ,
	CODED_DIAGNOSIS06 FOR COLUMN CODED00006 ,
	CODED_DIAGNOSIS07 FOR COLUMN CODED00007 ,
	CODED_DIAGNOSIS08 FOR COLUMN CODED00008 ,
	TYPE_OF_REGISTRATION FOR COLUMN TYPE_00002 ,
	PENDING_PURGE FOR COLUMN PENDI00001 ,
	CORONER_CASE FOR COLUMN CORON00001 ,
	OPERATING_DR_NUM FOR COLUMN OPERA00001 ,
	OP_PROCEDUR01 FOR COLUMN OP_PR00001 ,
	OP_PROCEDUR02 FOR COLUMN OP_PR00002 ,
	OP_PROCEDUR03 FOR COLUMN OP_PR00003 ,
	OP_PROCEDUR04 FOR COLUMN OP_PR00004 ,
	OP_PROCEDUREDATE01 FOR COLUMN OP_PR00005 ,
	OP_PROCEDUREDATE02 FOR COLUMN OP_PR00006 ,
	OP_PROCEDUREDATE03 FOR COLUMN OP_PR00007 ,
	OP_PROCEDUREDATE04 FOR COLUMN OP_PR00008 ,
	ACCIDENT_LOCATION FOR COLUMN ACCID00001 ,
	ACCIDENT_TIME FOR COLUMN ACCID00002 ,
	MOTHER_BABY_FLAG_LP FOR COLUMN MOTHE00001 ,
	DISCOUNT_PCT FOR COLUMN DISCO00001 ,
	EXPIRATION_DATE_FOR_DISCOUNT FOR COLUMN EXPIR00001 ,
	RELATIONSHIP_TO_GUARANTOR FOR COLUMN RELAT00001 ,
	BATCH_BALANCE FOR COLUMN BATCH00001 ,
	CURRENT_BALANCE FOR COLUMN CURRE00001 ,
	BALANCE_OF_UNBILLED_CHARGES FOR COLUMN BALAN00001 ,
	TOTAL_CHARGES_FOR_ACCT FOR COLUMN TOTAL00002 ,
	TOTAL_ADJ_FOR_THIS_ACCT FOR COLUMN TOTAL00003 ,
	TOTAL_PAYMENTS_FOR_ACCT FOR COLUMN TOTAL00004 ,
	DATE_OF_LAST_PAYMENT FOR COLUMN DATE_00001 ,
	BALANCE_ON_LAST_STATEMENT FOR COLUMN BALAN00002 ,
	DATE_OF_LAST_CYCLE_BILL FOR COLUMN DATE_00002 ,
	DATE_OF_LAST_STATEMENT FOR COLUMN DATE_00003 ,
	DAYS_IN_STAY FOR COLUMN DAYS_00003 ,
	DATE_OF_LAST_ROOM_CHARGE FOR COLUMN DATE_00004 ,
	DISCH_PENDING_UPDATE_FLA FOR COLUMN DISCH00001 ,
	DISCH_CODE ,
	ACUITY_CODE FOR COLUMN ACUIT00001 ,
	DIABETIC ,
	FLAG_INS_BENEFITS_EXIST FOR COLUMN FLAG_00001 ,
	FINAL_BILLING_FLAG FOR COLUMN FINAL00001 ,
	DAILY_FLAG ,
	YESTERDAY_INPAT_STATUS FOR COLUMN YESTE00001 ,
	YESTERDAY_OUTPAT_STATUS FOR COLUMN YESTE00002 ,
	YESTERDAY_NURSING_STATION FOR COLUMN YESTE00003 ,
	YESTERDAY_ROOM_NUM FOR COLUMN YESTE00004 ,
	YESTERDAY_BED_NUM FOR COLUMN YESTE00005 ,
	YESTERDAY_BATCH_BALANCE FOR COLUMN YESTE00006 ,
	YESTERDAY_CURRENT_BALANCE FOR COLUMN YESTE00007 ,
	YESTERDAY_BAL_UNBILLED_CHGS FOR COLUMN YESTE00008 ,
	DATE_OF_LAST_MAINTENANCE FOR COLUMN DATE_00005 ,
	LAST_MAINTENANCE_LOG_NUM FOR COLUMN LAST_00002 ,
	UPDATE_LOG_NUM FOR COLUMN UPDAT00001 ,
	CUMULATIVE_BAD_DEBT_WRITEOFF FOR COLUMN CUMUL00001 ,
	MOTHER_PAT_ACCT FOR COLUMN MOTHE00002 ,
	INPAT_STATUS_CODE FOR COLUMN INPAT00002 ,
	OUTPAT_STATUS_CODE FOR COLUMN OUTPA00001 ,
	LAST_CLINIC_REGISTERED_FOR FOR COLUMN LAST_00003 ,
	DATE_OF_INITIAL_REGISTRATION FOR COLUMN DATE_00006 ,
	FINAL_LAB_SUMMARY_PRINTED FOR COLUMN FINAL00002 ,
	YEST_FINAL_LAB_SUMMARY_FLAG FOR COLUMN YEST_00001 ,
	MONTH_PORTION_OF_DATE FOR COLUMN MONTH00002 ,
	DAY_PORTION_OF_DATE FOR COLUMN DAY_P00001 ,
	YEAR_PORTION_OF_DATE FOR COLUMN YEAR_00002 ,
	DELETE_CODE FOR COLUMN DELET00001 ,
	PAT_ADMIT_SOURCE_CODE FOR COLUMN PAT_A00002 ,
	PAT_STATUS_CODE FOR COLUMN PAT_S00001 ,
	CONDITION_CODE_ARRAY01 FOR COLUMN CONDI00002 ,
	CONDITION_CODE_ARRAY02 FOR COLUMN CONDI00003 ,
	CONDITION_CODE_ARRAY03 FOR COLUMN CONDI00004 ,
	CONDITION_CODE_ARRAY04 FOR COLUMN CONDI00005 ,
	CONDITION_CODE_ARRAY05 FOR COLUMN CONDI00006 ,
	CONDITION_CODE_ARRAY06 FOR COLUMN CONDI00007 ,
	CONDITION_CODE_ARRAY07 FOR COLUMN CONDI00008 ,
	SPECIAL_PROGRAM_INDICATOR FOR COLUMN SPECI00001 ,
	PSRO_UR_PRO_APPROVAL_FLAG FOR COLUMN PSRO_00001 ,
	PSRO_UR_PRO_APPR_FROM_DATE FOR COLUMN PSRO_00002 ,
	PSRO_UR_PRO_APPROVED_TO_DATE FOR COLUMN PSRO_00003 ,
	PSRO_UR_PRO_OF_GRACE_DAYS FOR COLUMN PSRO_00004 ,
	TRTMT_AUTH_CODE FOR COLUMN TRTMT00001 ,
	OCCURANCE_CODE_ARRAY01 FOR COLUMN OCCUR00001 ,
	OCCURANCE_CODE_ARRAY02 FOR COLUMN OCCUR00002 ,
	OCCURANCE_CODE_ARRAY03 FOR COLUMN OCCUR00003 ,
	OCCURANCE_CODE_ARRAY04 FOR COLUMN OCCUR00004 ,
	OCCURANCE_CODE_ARRAY05 FOR COLUMN OCCUR00005 ,
	OCCURANCE_DATE_ARRAY01 FOR COLUMN OCCUR00006 ,
	OCCURANCE_DATE_ARRAY02 FOR COLUMN OCCUR00007 ,
	OCCURANCE_DATE_ARRAY03 FOR COLUMN OCCUR00008 ,
	OCCURANCE_DATE_ARRAY04 FOR COLUMN OCCUR00009 ,
	OCCURANCE_DATE_ARRAY05 FOR COLUMN OCCUR00010 ,
	SPAN_CODE ,
	SPAN_FROM_DATE FOR COLUMN SPAN_00001 ,
	SPAN_TO_DATE FOR COLUMN SPAN_00002 ,
	REASON_FOR_ADMISSION_DIAG01 FOR COLUMN REASO00001 ,
	REASON_FOR_ADMISSION_DIAG02 FOR COLUMN REASO00002 ,
	REASON_FOR_ADMISSION_DIAG03 FOR COLUMN REASO00003 ,
	REASON_FOR_ADMISSION_DIAG04 FOR COLUMN REASO00004 ,
	REASON_FOR_ADMISSION_DIAG05 FOR COLUMN REASO00005 ,
	COMPLICATIONS_DIAGNOSIS01 FOR COLUMN COMPL00001 ,
	COMPLICATIONS_DIAGNOSIS02 FOR COLUMN COMPL00002 ,
	COMPLICATIONS_DIAGNOSIS03 FOR COLUMN COMPL00003 ,
	MED_REQUIRED_PRIVATE_ROOM FOR COLUMN MED_R00002 ,
	GUAR_PAT_RELATIONSHIP_CODE FOR COLUMN GUAR_00001 ,
	COST_OF_UNBILLED_CHARGES FOR COLUMN COST_00001 ,
	YEST_COST_OF_UNBILL_CHGS FOR COLUMN YEST_00002 ,
	INSTITUTION_NAME FOR COLUMN INSTI00001 ,
	REREGISTER_RECURR_OUTP FOR COLUMN REREG00001 ,
	STAY_DENIED_EFFECTIVE_DATE FOR COLUMN STAY_00001 ,
	DENIAL_NOTIFICATION_DATE FOR COLUMN DENIA00001 ,
	TYPE_OF_ALTERNATE_CARE FOR COLUMN TYPE_00003 ,
	ALTERNATE_CARD_DATE FOR COLUMN ALTER00001 ,
	NUM_OF_CARVE_OUT_DAYS FOR COLUMN NUM_O00003 ,
	ACCIDENT_TYPE_CODE FOR COLUMN ACCID00003 ,
	WORKERS_COMPENSATION_CODE FOR COLUMN WORKE00001 ,
	NO_FAULT_CODE FOR COLUMN NO_FA00001 ,
	ABORTION_STERILIZATION_CODE FOR COLUMN ABORT00001 ,
	DATE_OF_LAST_MENSTRATION FOR COLUMN DATE_00007 ,
	RATE_CARD_CODE FOR COLUMN RATE_00001 ,
	TRTMT_SCREEN_RELATED_CDE FOR COLUMN TRTMT00002 ,
	CONSULTING_DR1_NUM FOR COLUMN CONSU00001 ,
	CONSULTING_DR2_NUM FOR COLUMN CONSU00002 ,
	CONSULTING_DR3_NUM FOR COLUMN CONSU00003 ,
	CONSULTING_DR4_NUM FOR COLUMN CONSU00004 ,
	CONSULTING_DR5_NUM FOR COLUMN CONSU00005 ,
	CLINIC_REGISTERED01 FOR COLUMN CLINI00001 ,
	CLINIC_REGISTERED02 FOR COLUMN CLINI00002 ,
	CLINIC_REGISTERED03 FOR COLUMN CLINI00003 ,
	CLINIC_REGISTERED04 FOR COLUMN CLINI00004 ,
	CLINIC_REGISTERED05 FOR COLUMN CLINI00005 ,
	CLINIC_REGISTERED06 FOR COLUMN CLINI00006 ,
	CLINIC_REGISTERED07 FOR COLUMN CLINI00007 ,
	CLINIC_REGISTERED08 FOR COLUMN CLINI00008 ,
	CLINIC_REGISTERED09 FOR COLUMN CLINI00009 ,
	CLINIC_REGISTERED10 FOR COLUMN CLINI00010 ,
	CLINIC_REGISTERED11 FOR COLUMN CLINI00011 ,
	CLINIC_REGISTERED12 FOR COLUMN CLINI00012 ,
	CLINIC_REGISTERED13 FOR COLUMN CLINI00013 ,
	CLINIC_REGISTERED14 FOR COLUMN CLINI00014 ,
	CLINIC_REGISTERED15 FOR COLUMN CLINI00015 ,
	CLINIC_REGISTERED16 FOR COLUMN CLINI00016 ,
	CLINIC_REGISTERED17 FOR COLUMN CLINI00017 ,
	CLINIC_REGISTERED18 FOR COLUMN CLINI00018 ,
	CLINIC_REGISTERED19 FOR COLUMN CLINI00019 ,
	CLINIC_REGISTERED20 FOR COLUMN CLINI00020 ,
	CLINIC_REGISTERED21 FOR COLUMN CLINI00021 ,
	CLINIC_REGISTERED22 FOR COLUMN CLINI00022 ,
	CLINIC_REGISTERED23 FOR COLUMN CLINI00023 ,
	CLINIC_REGISTERED24 FOR COLUMN CLINI00024 ,
	CLINIC_REGISTERED25 FOR COLUMN CLINI00025 ,
	VALIDATE_BALANCE_FLAG FOR COLUMN VALID00001 ,
	PRIVATE_ROOM_REASON FOR COLUMN PRIVA00001 ,
	PREV_BAD_DEBT_FLAG FOR COLUMN PREV_00001 ,
	MOTHER_BABY_FLAG_LB FOR COLUMN MOTHE00003 ,
	EMERGENCY_OUTPAT_FLAG FOR COLUMN EMERG00001 ,
	FINANCIAL_CLASS_CODE FOR COLUMN FINAN00001 ,
	ACCOMODATION_CODE FOR COLUMN ACCOM00001 ,
	REFERRAL_SOURCE FOR COLUMN REFER00001 ,
	FATHER_DOB ,
	MOTHER_DOB ,
	REGIST_FORM FOR COLUMN REGIS00001 ,
	PREGNANCY_TERMINATED FOR COLUMN PREGN00001 ,
	MEDICARE_ELIGIBLE FOR COLUMN MEDIC00001 ,
	ABORTION_CODE FOR COLUMN ABORT00002 ,
	LAB_UPDATE_LOG_NUM FOR COLUMN LAB_U00001 ,
	WARNING_FLAG FOR COLUMN WARNI00001 ,
	NAME_TITLE ,
	DATE_OF_BIRTH_CENTURY FOR COLUMN DATE_00008 ,
	ACCIDENT_COMMENT FOR COLUMN ACCID00004 ,
	MOTHER_BABY_ACCT1 FOR COLUMN MOTHE00004 ,
	MOTHER_BABY_ACCT2 FOR COLUMN MOTHE00005 ,
	MOTHER_BABY_ACCT3 FOR COLUMN MOTHE00006 ,
	LAST_REVIEW_DATE FOR COLUMN LAST_00004 ,
	NEXT_REVIEW_DATE FOR COLUMN NEXT_00002 ,
	PAT_LOCAL_ADDRESS FOR COLUMN PAT_L00002 ,
	PAT_LOCAL_ADDRESS_CITY FOR COLUMN PAT_L00003 ,
	LOCAL_ADDRESS_STATE_ID FOR COLUMN LOCAL00001 ,
	PAT_LOCAL_5ZIP FOR COLUMN PAT_L00004 ,
	PAT_LOCAL_9ZIP FOR COLUMN PAT_L00005 ,
	AREA_CODE ,
	PHONE_NUM ,
	ADMITING_DR_NUM FOR COLUMN ADMIT00002 ,
	FORCE_BILL_FLAG FOR COLUMN FORCE00001 ,
	ABSTRACT_EXISTS FOR COLUMN ABSTR00002 ,
	AML_FLAG ,
	DIET_CODE ,
	VALUABLES_ARE_TAKEN FOR COLUMN VALUA00001 ,
	SECOND_SPAN_CODE FOR COLUMN SECON00001 ,
	OCCURANCE_CODE_ARRAY6 FOR COLUMN OCCUR00011 ,
	OCCURANCE_CODE_ARRAY7 FOR COLUMN OCCUR00012 ,
	OCCURANCE_CODE_ARRAY8 FOR COLUMN OCCUR00013 ,
	OCCURANCE_DATE_ARRAY6 FOR COLUMN OCCUR00014 ,
	OCCURANCE_DATE_ARRAY7 FOR COLUMN OCCUR00015 ,
	OCCURANCE_DATE_ARRAY8 FOR COLUMN OCCUR00016 ,
	CENTURY_FOR_LPLDD FOR COLUMN CENTU00001 ,
	ADT_CENTURY FOR COLUMN ADT_C00001 ,
	DAT_CENTURY FOR COLUMN DAT_C00001 ,
	FILLER ,
	IPA_CLINIC ,
	CLERGY_VISIT FOR COLUMN CLERG00001 ,
	PAT_MMIDDLE_INITIAL FOR COLUMN PAT_M00001 ,
	REFERRING_DR_NUM FOR COLUMN REFER00002 ,
	OTHER_DR_NUM FOR COLUMN OTHER00001 ,
	PARISH_CODE FOR COLUMN PARIS00001 ,
	AUTO_ACCIDENT_STATE FOR COLUMN AUTO_00001 ,
	COUNTRY_CODE FOR COLUMN COUNT00001 ,
	IPA ,
	RESEARCH_ID FOR COLUMN RESEA00001 ,
	SCHEDULED_CODE FOR COLUMN SCHED00001 )
	AS
	SELECT
		 LPHSP#  	--as  FACILITYID
		, LPACCT 	--as PAT_ACCT_NUM
		, LPMRC#	--as MED_RECORD_NUM
		, LPPLNM	--as PAT_LAST_NAME
		, LPPFNM	--as PAT_FIRST_NAME
		, LPRLGN	--as RELIGION_CODE
		, LPIPOP	--as INPAT_OUTPAT_FLAG
		, LPGAR#	--as GUARANTOR_NUM
		, LPADR#	--as ATTENDING_DR_NUM
		, LPMSV		--as MED_SERVICE_CODE
		, LPABRQ	--as ABSTRACT_REQUIRED
		, LPADT1	--as MONTH_OF_ADMISSION
		, LPADT2	--as DAY_OF_ADMISSION
		, LPADT3	--as YEAR_OF_ADMISSION
		, LPLAT		--as TIME_OF_ADMISSION
		, LPLDD		--as DISCH_DATE
		, LPLDT		--as TIME_OF_DISCH
		, LPTCRT	--as TYPE_OF_CERT
		, LPDCRT	--as DAYS_PER_CERT
		, LPSCRT	--as START_DATE_FOR_CURRENT_CERT
		, LPNCRT	--as NEXT_CERTIFICATION_DATE
		, LPICRT	--as DAYS_IN_INITIAL_CERT
		, LP#EXT	--as NUM_OF_EXTENSIONS
		, LPDTOT	--as TOTAL_CERTIFIED_DAYS
		, LPADMC	--as ADMITTING_CATEGORY
		, LPNS		--as NURSING_STATION
		, LPROOM	--as ROOM_NUM
		, LPBED		--as  BED_NUM
		, FLR142	--as  RESERVED_FIELD_2_POSITION
		, LPPTYP	--as  PAT_TYPE
		, LPRMRT	--as  ROOM_RATE
		, LPRMCT	--as  ROOM_CHG_CHARGE_DESC_NUM
		, LPISO		--as  ISOLATION_CODE
		, LPCOND	--as  CONDITION_CODE
		, LPDIET	--as  NUM_OF_VISITS
		, LPVIS#	--as  OP_VISIT_NUM
		, LPLCYB	--as  LAST_CYCLE_BILL_NUM
		, LPHOWA	--as  HOW_ARRIVED
		, LPDIAG	--as  DIAGNOSIS
		, LPCD01	--as "CODED_DIAGNOSIS01"
		, LPCD02	--as "CODED_DIAGNOSIS02"
		, LPCD03	--as "CODED_DIAGNOSIS03"
		, LPCD04	--as "CODED_DIAGNOSIS04"
		, LPCD05	--as "CODED_DIAGNOSIS05"
		, LPCD06	--as "CODED_DIAGNOSIS06"
		, LPCD07	--as "CODED_DIAGNOSIS07"
		, LPCD08	--as "CODED_DIAGNOSIS08"
		, LPTREG	--as TYPE_OF_REGISTRATION
		, LPPOLN	--as PENDING_PURGE
		, LPCORC	--as CORONER_CASE
		, LPODR#	--as OPERATING_DR_NUM
		, LPOP01	--as "OP_PROCEDUR01"
		, LPOP02	--as "OP_PROCEDUR02"
		, LPOP03	--as "OP_PROCEDUR03"
		, LPOP04	--as "OP_PROCEDUR04"
		, LPOD01	--as "OP_PROCEDUREDATE01"
		, LPOD02	--as "OP_PROCEDUREDATE02"
		, LPOD03	--as "OP_PROCEDUREDATE03"
		, LPOD04	--as "OP_PROCEDUREDATE04"
		, LPALOC	--as ACCIDENT_LOCATION
		, LPATIM	--as ACCIDENT_TIME
		, LPMOTH	--as MOTHER_BABY_FLAG
		, LPDISC	--as DISCOUNT_PCT
		, LPDEDT	--as EXPIRATION_DATE_FOR_DISCOUNT
		, LPGREL	--as RELATIONSHIP_TO_GUARANTOR
		, LPBBAL	--as BATCH_BALANCE
		, LPCBAL	--as CURRENT_BALANCE
		, LPUBAL	--as BALANCE_OF_UNBILLED_CHARGES
		, LPCHGS	--as TOTAL_CHARGES_FOR_ACCT
		, LPADJ		--as TOTAL_ADJ_FOR_THIS_ACCT
		, LPPMTS	--as TOTAL_PAYMENTS_FOR_ACCT
		, LPLPD		--as DATE_OF_LAST_PAYMENT
		, LPSBAL	--as BALANCE_ON_LAST_STATEMENT
		, LPLCBD	--as DATE_OF_LAST_CYCLE_BILL
		, LPLSD		--as DATE_OF_LAST_STATEMENT
		, LP#DAY	--as DAYS_IN_STAY
		, LPLRMD	--as DATE_OF_LAST_ROOM_CHARGE
		, LPDSFL	--as DISCH_PENDING_UPDATE_FLA
		, LPDCOD	--as DISCH_CODE
		, LPCCOD	--as ACUITY_CODE
		, LPNDM		--as DIABETIC
		, LPINSB	--as FLAG_INS_BENEFITS_EXIST
		, LPFBIL	--as FINAL_BILLING_FLAG
		, LPDFLG	--as DAILY_FLAG
		, LPYSTI	--as YESTERDAY_INPAT_STATUS
		, LPYSTO	--as YESTERDAY_OUTPAT_STATUS
		, LPYNS		--as YESTERDAY_NURSING_STATION
		, LPYRM		--as YESTERDAY_ROOM_NUM
		, LPYBED	--as YESTERDAY_BED_NUM
		, LPYBBL	--as YESTERDAY_BATCH_BALANCE
		, LPYCBL	--as YESTERDAY_CURRENT_BALANCE
		, LPYUBL	--as YESTERDAY_BAL_UNBILLED_CHGS
		, LPLMD		--as DATE_OF_LAST_MAINTENANCE
		, LPLML		--as LAST_MAINTENANCE_LOG_NUM
		, LPLUL#	--as UPDATE_LOG_NUM
		, LPBDBT	--as CUMULATIVE_BAD_DEBT_WRITEOFF
		, LPMPT#	--as MOTHER_PAT_ACCT
		, LPPSTI	--as INPAT_STATUS_CODE
		, LPPSTO	--as OUTPAT_STATUS_CODE
		, LPLCL		--as LAST_CLINIC_REGISTERED_FOR
		, LPDIR		--as DATE_OF_INITIAL_REGISTRATION
		, LPLSM		--as FINAL_LAB_SUMMARY_PRINTED
		, LPYLSM	--as YEST_FINAL_LAB_SUMMARY_FLAG
		, LPDAT1	--as MONTH_PORTION_OF_DATE
		, LPDAT2	--as DAY_PORTION_OF_DATE
		, LPDAT3	--as YEAR_PORTION_OF_DATE
		, LPDEL		--as DELETE_CODE
		, LPPSRC	--as PAT_ADMIT_SOURCE_CODE
		, LPPSTS	--as PAT_STATUS_CODE
		, LPCI01	--as "CONDITION_CODE_ARRAY01"
		, LPCI02	--as "CONDITION_CODE_ARRAY02"
		, LPCI03	--as "CONDITION_CODE_ARRAY03"
		, LPCI04	--as "CONDITION_CODE_ARRAY04"
		, LPCI05	--as "CONDITION_CODE_ARRAY05"
		, LPCI06	--as "CONDITION_CODE_ARRAY06"
		, LPCI07	--as "CONDITION_CODE_ARRAY07"
		, LPSPGM	--as SPECIAL_PROGRAM_INDICATOR
		, LPAPVL	--as PSRO_UR_PRO_APPROVAL_FLAG
		, LPAPFR	--as PSRO_UR_PRO_APPR_FROM_DATE
		, LPAPTO	--as PSRO_UR_PRO_APPROVED_TO_DATE
		, LPGRCD	--as PSRO_UR_PRO_OF_GRACE_DAYS
		, LPTACD	--as TRTMT_AUTH_CODE
		, LPOC01	--as "OCCURANCE_CODE_ARRAY01"
		, LPOC02	--as "OCCURANCE_CODE_ARRAY02"
		, LPOC03	--as "OCCURANCE_CODE_ARRAY03"
		, LPOC04	--as "OCCURANCE_CODE_ARRAY04"
		, LPOC05	--as "OCCURANCE_CODE_ARRAY05"
		, LPOA01	--as "OCCURANCE_DATE_ARRAY01"
		, LPOA02	--as "OCCURANCE_DATE_ARRAY02"
		, LPOA03	--as "OCCURANCE_DATE_ARRAY03"
		, LPOA04	--as "OCCURANCE_DATE_ARRAY04"
		, LPOA05	--as "OCCURANCE_DATE_ARRAY05"
		, LPSPNC	--as SPAN_CODE
		, LPSPFR	--as SPAN_FROM_DATE
		, LPSPTO	--as SPAN_TO_DATE
		, LPRA01	--as "REASON_FOR_ADMISSION_DIAG01"
		, LPRA02	--as "REASON_FOR_ADMISSION_DIAG02"
		, LPRA03	--as "REASON_FOR_ADMISSION_DIAG03"
		, LPRA04	--as "REASON_FOR_ADMISSION_DIAG04"
		, LPRA05	--as "REASON_FOR_ADMISSION_DIAG05"
		, LPCC01	--as "COMPLICATIONS_DIAGNOSIS01"
		, LPCC02	--as "COMPLICATIONS_DIAGNOSIS02"
		, LPCC03	--as "COMPLICATIONS_DIAGNOSIS03"
		, LPMRPR	--as MED_REQUIRED_PRIVATE_ROOM
		, LPRRCD	--as GUAR_PAT_RELATIONSHIP_CODE
		, LPUCST	--as COST_OF_UNBILLED_CHARGES
		, LPYUCS	--as YEST_COST_OF_UNBILL_CHGS
		, LPINSN	--as INSTITUTION_NAME
		, LPPUBL	--as REREGISTER_RECURR_OUTP
		, LPSDED	--as STAY_DENIED_EFFECTIVE_DATE
		, LPDNOT	--as DENIAL_NOTIFICATION_DATE
		, LPTALT	--as TYPE_OF_ALTERNATE_CARE
		, LPALTD	--as ALTERNATE_CARD_DATE
		, LP#COD	--as NUM_OF_CARVE_OUT_DAYS
		, LPACTP	--as ACCIDENT_TYPE_CODE
		, LPWRKC	--as WORKERS_COMPENSATION_CODE
		, LPNOFT	--as NO_FAULT_CODE
		, LPABOR	--as ABORTION_STERILIZATION_CODE
		, LPLMEN	--as DATE_OF_LAST_MENSTRATION
		, LPRTCD	--as RATE_CARD_CODE
		, LPTSCR	--as TRTMT_SCREEN_RELATED_CDE
		, LPMD01	--as CONSULTING_DR1_NUM
		, LPMD02	--as CONSULTING_DR2_NUM
		, LPMD03	--as CONSULTING_DR3_NUM
		, LPMD04	--as CONSULTING_DR4_NUM
		, LPMD05	--as CONSULTING_DR5_NUM
		, LPCL01	--as "CLINIC_REGISTERED01"
		, LPCL02	--as "CLINIC_REGISTERED02"
		, LPCL03	--as "CLINIC_REGISTERED03"
		, LPCL04	--as "CLINIC_REGISTERED04"
		, LPCL05	--as "CLINIC_REGISTERED05"
		, LPCL06	--as "CLINIC_REGISTERED06"
		, LPCL07	--as "CLINIC_REGISTERED07"
		, LPCL08	--as "CLINIC_REGISTERED08"
		, LPCL09	--as "CLINIC_REGISTERED09"
		, LPCL10	--as "CLINIC_REGISTERED10"
		, LPCL11	--as "CLINIC_REGISTERED11"
		, LPCL12	--as "CLINIC_REGISTERED12"
		, LPCL13	--as "CLINIC_REGISTERED13"
		, LPCL14	--as "CLINIC_REGISTERED14"
		, LPCL15	--as "CLINIC_REGISTERED15"
		, LPCL16	--as "CLINIC_REGISTERED16"
		, LPCL17	--as "CLINIC_REGISTERED17"
		, LPCL18	--as "CLINIC_REGISTERED18"
		, LPCL19	--as "CLINIC_REGISTERED19"
		, LPCL20	--as "CLINIC_REGISTERED20"
		, LPCL21	--as "CLINIC_REGISTERED21"
		, LPCL22	--as "CLINIC_REGISTERED22"
		, LPCL23	--as "CLINIC_REGISTERED23"
		, LPCL24	--as "CLINIC_REGISTERED24"
		, LPCL25	--as "CLINIC_REGISTERED25"
		, LPVALD	--as VALIDATE_BALANCE_FLAG
		, LPPVRR	--as PRIVATE_ROOM_REASON
		, LPBDFG	--as PREV_BAD_DEBT_FLAG
		, LPMBF		--as MOTHER_BABY_FLAG
		, LPERFG	--as EMERGENCY_OUTPAT_FLAG
		, LPFC		--as FINANCIAL_CLASS_CODE
		, LPACC		--as ACCOMODATION_CODE
		, LPRSRC	--as REFERRAL_SOURCE
		, LPFDOB	--as FATHER_DOB
		, LPMDOB	--as MOTHER_DOB
		, LPFORM	--as REGIST_FORM
		, LPPRGT	--as PREGNANCY_TERMINATED
		, LPMELG	--as MEDICARE_ELIGIBLE   --(Y/N)
		, LPABC1	--as ABORTION_CODE
		, LPLULL	--as LAB_UPDATE_LOG_NUM
		, LPWRNF	--as WARNING_FLAG
		, LPNMTL	--as NAME_TITLE
		, LPDOB8	--as DATE_OF_BIRTH_CENTURY
		, LPACMT	--as ACCIDENT_COMMENT
		, LPMB#1	--as "MOTHER_BABY_ACCT1"
		, LPMB#2	--as "MOTHER_BABY_ACCT2"
		, LPMB#3	--as "MOTHER_BABY_ACCT3"
		, LPLRDT	--as LAST_REVIEW_DATE
		, LPNRDT	--as NEXT_REVIEW_DATE
		, LPPADR	--as PAT_LOCAL_ADDRESS
		, LPPCIT	--as PAT_LOCAL_ADDRESS_CITY
		, LPPSTE	--as LOCAL_ADDRESS_STATE_ID
		, LPPZPA	--as PAT_LOCAL_5ZIP
		, LPPZ4A	--as PAT_LOCAL_9ZIP
		, LPPACD	--as AREA_CODE
		, LPPPH#	--as PHONE_NUM
		, LPMDR#	--as ADMITING_DR_NUM
		, LPFBLF	--as FORCE_BILL_FLAG
		, LPABST	--as ABSTRACT_EXISTS
		, LPAMLF	--as AML_FLAG
		, LPDTCD	--as DIET_CODE
		, LPVALU	--as VALUABLES_ARE_TAKEN
		, LPSPN2	--as SECOND_SPAN_CODE
		, LPOC06	--as "OCCURANCE_CODE_ARRAY6"
		, LPOC07	--as "OCCURANCE_CODE_ARRAY7"
		, LPOC08	--as "OCCURANCE_CODE_ARRAY8"
		, LPOA06	--as "OCCURANCE_DATE_ARRAY6"
		, LPOA07	--as "OCCURANCE_DATE_ARRAY7"
		, LPOA08	--as "OCCURANCE_DATE_ARRAY8"
		, LPLDDC	--as CENTURY_FOR_LPLDD
		, LPADT4	--as ADT_CENTURY
		, LPDAT4	--as DAT_CENTURY
		, LPFILL	--as FILLER
		, LPIPAC	--as IPA_CLINIC
		, LPCLVS	--as CLERGY_VISIT
		, LPPMI		--as PAT_MMIDDLE_INITIAL
		, LPRDR#	--as REFERRING_DR_NUM
		, LPTDR#	--as OTHER_DR_NUM
		, LPPARC	--as PARISH_CODE
		, LPACST	--as AUTO_ACCIDENT_STATE
		, LPACCN	--as COUNTRY_CODE
		, LPIPA		--as IPA
		, LPRSID	--as RESEARCH_ID
		, LPSCHD	--as SCHEDULED_CODE
		FROM HPADLPP ;

LABEL ON COLUMN &LIBRARY/ACCOUNTS
( FACILITYID IS 'HOSP#' ,
	PAT_ACCT_NUM IS 'ACCT.#' ,
	MED_RECORD_NUM IS 'MEDICAL RECORD#' ,
	PAT_LAST_NAME IS 'LAST NAME' ,
	PAT_FIRST_NAME IS 'FIRST NAME' ,
	RELIGION_CODE IS 'RELIGION' ,
	INPAT_OUTPAT_FLAG IS 'IP/OP TYPE FLAG' ,
	GUARANTOR_NUM IS 'GUARANTOR #' ,
	ATTENDING_DR_NUM IS 'DOCTOR NUMBER' ,
	MED_SERVICE_CODE IS 'MED SVC CODE' ,
	ABSTRACT_REQUIRED IS 'ABSTRACT REQUIRED' ,
	MONTH_OF_ADMISSION IS 'MONTH' ,
	DAY_OF_ADMISSION IS 'DAY' ,
	YEAR_OF_ADMISSION IS 'YEAR' ,
	TIME_OF_ADMISSION IS 'TIME-ADM/OP VIS' ,
	DISCH_DATE IS 'DATE DISCHARGED' ,
	TIME_OF_DISCH IS 'TIME DISCHARGED' ,
	TYPE_OF_CERT IS 'TYPE-CERTIFICAT' ,
	DAYS_PER_CERT IS 'DAYS PER CERTIF' ,
	START_DATE_FOR_CURRENT_CERT IS 'CERTIF-START-DY' ,
	NEXT_CERTIFICATION_DATE IS 'NEXT CERTIF DTE' ,
	DAYS_IN_INITIAL_CERT IS 'INIT CERTF DAYS' ,
	NUM_OF_EXTENSIONS IS '# OF EXTENSIONS' ,
	TOTAL_CERTIFIED_DAYS IS 'TOT CERTIF DAYS' ,
	ADMITTING_CATEGORY IS 'ADMIT CATEGORY' ,
	NURSING_STATION IS 'NS' ,
	ROOM_NUM IS 'ROOM' ,
	BED_NUM IS 'BED' ,
	PAT_TYPE IS 'PATIENT TYPE' ,
	ROOM_RATE IS 'ROOM RATE' ,
	ROOM_CHG_CHARGE_DESC_NUM IS 'ROOM CHG DESC #' ,
	ISOLATION_CODE IS 'ISOLATION CODE' ,
	CONDITION_CODE IS 'CONDITION CODE' ,
	NUM_OF_VISITS IS '# OF VISITS FOR RX' ,
	OP_VISIT_NUM IS 'OUT-PAT VISIT #' ,
	LAST_CYCLE_BILL_NUM IS 'LAST CYCL BILL#' ,
	HOW_ARRIVED IS 'HOW PAT ARRIVED' ,
	DIAGNOSIS IS 'CURR. DIAGNOSIS' ,
	CODED_DIAGNOSIS01 IS 'CODED DIAG 1' ,
	CODED_DIAGNOSIS02 IS 'CODED DIAG 2' ,
	CODED_DIAGNOSIS03 IS 'CODED DIAG 3' ,
	CODED_DIAGNOSIS04 IS 'CODED DIAG 4' ,
	CODED_DIAGNOSIS05 IS 'CODED DIAG 5' ,
	CODED_DIAGNOSIS06 IS 'CODED DIAG 6' ,
	CODED_DIAGNOSIS07 IS 'CODED DIAG 7' ,
	CODED_DIAGNOSIS08 IS 'CODED DIAG 8' ,
	TYPE_OF_REGISTRATION IS 'REGISTR TYPE CD' ,
	PENDING_PURGE IS 'PENDING PURGE' ,
	CORONER_CASE IS 'CORONER CASE CD' ,
	OPERATING_DR_NUM IS 'OPERATING DR #' ,
	OP_PROCEDUR01 IS 'OPERATIV PROCED 1' ,
	OP_PROCEDUR02 IS 'OPERATIV PROCED 2' ,
	OP_PROCEDUR03 IS 'OPERATIV PROCED 3' ,
	OP_PROCEDUR04 IS 'OPERATIV PROCED 4' ,
	OP_PROCEDUREDATE01 IS 'OPER PROC DATES 1' ,
	OP_PROCEDUREDATE02 IS 'OPER PROC DATES 2' ,
	OP_PROCEDUREDATE03 IS 'OPER PROC DATES 3' ,
	OP_PROCEDUREDATE04 IS 'OPER PROC DATES 4' ,
	ACCIDENT_LOCATION IS 'ACCIDENT LOCAT.' ,
	ACCIDENT_TIME IS 'ACCIDENT TIME' ,
	MOTHER_BABY_FLAG_LP IS 'MOTHER/BABY FLG' ,
	DISCOUNT_PCT IS 'DISCOUNT %' ,
	EXPIRATION_DATE_FOR_DISCOUNT IS 'DISC EXPR. DATE' ,
	RELATIONSHIP_TO_GUARANTOR IS 'GUAR REL' ,
	BATCH_BALANCE IS 'BATCH BALANCE' ,
	CURRENT_BALANCE IS 'CURRENT BALANCE' ,
	BALANCE_OF_UNBILLED_CHARGES IS 'UNBILL CHGS BAL' ,
	TOTAL_CHARGES_FOR_ACCT IS 'TOTAL CHARGES' ,
	TOTAL_ADJ_FOR_THIS_ACCT IS 'TOT ADJUSTMENTS' ,
	TOTAL_PAYMENTS_FOR_ACCT IS 'TOTAL PAYMENTS' ,
	DATE_OF_LAST_PAYMENT IS 'LAST PAYMT DATE' ,
	BALANCE_ON_LAST_STATEMENT IS 'LAST STMT. BAL.' ,
	DATE_OF_LAST_CYCLE_BILL IS 'DATE-LST BILLED' ,
	DATE_OF_LAST_STATEMENT IS 'LAST STMT. DATE' ,
	DAYS_IN_STAY IS '# DAYS IN STAY' ,
	DATE_OF_LAST_ROOM_CHARGE IS 'LST RM CHG DATE' ,
	DISCH_PENDING_UPDATE_FLA IS 'DISCHG PEND FLG' ,
	DISCH_CODE IS 'DISCHARGE CODE' ,
	ACUITY_CODE IS 'ACUITY CODE' ,
	FLAG_INS_BENEFITS_EXIST IS 'INS BENEF EXIST' ,
	FINAL_BILLING_FLAG IS 'FINAL BILL FLAG' ,
	DAILY_FLAG IS 'DAILY FLAG' ,
	YESTERDAY_INPAT_STATUS IS 'Y''DAY IP STATUS' ,
	YESTERDAY_OUTPAT_STATUS IS 'Y''DAY OP STATUS' ,
	YESTERDAY_NURSING_STATION IS 'Y''DAY NURS STAT' ,
	YESTERDAY_ROOM_NUM IS 'Y''DAY ROOM #' ,
	YESTERDAY_BED_NUM IS 'Y''DAY BED #' ,
	YESTERDAY_BATCH_BALANCE IS 'YEST BATCH BAL' ,
	YESTERDAY_CURRENT_BALANCE IS 'YEST CURR BAL' ,
	YESTERDAY_BAL_UNBILLED_CHGS IS 'YEST UNB CHGS' ,
	DATE_OF_LAST_MAINTENANCE IS 'LAST MAINT DATE' ,
	LAST_MAINTENANCE_LOG_NUM IS 'LAST MAINT LOG #' ,
	UPDATE_LOG_NUM IS 'LAST UPDATE LOG #' ,
	CUMULATIVE_BAD_DEBT_WRITEOFF IS 'CUMM BAD DEBT $' ,
	MOTHER_PAT_ACCT IS 'MOTHER PAT ACCT' ,
	INPAT_STATUS_CODE IS 'CURR I/P STATUS' ,
	OUTPAT_STATUS_CODE IS 'CURR O/P STATUS' ,
	LAST_CLINIC_REGISTERED_FOR IS 'LAST CLINIC REG' ,
	DATE_OF_INITIAL_REGISTRATION IS 'DATE INIT REGISTRATION' ,
	FINAL_LAB_SUMMARY_PRINTED IS 'FRLSM' ,
	YEST_FINAL_LAB_SUMMARY_FLAG IS 'FRYLSM' ,
	MONTH_PORTION_OF_DATE IS 'MONTH' ,
	DAY_PORTION_OF_DATE IS 'DAY' ,
	YEAR_PORTION_OF_DATE IS 'YEAR' ,
	DELETE_CODE IS 'DELETE CODE' ,
	PAT_ADMIT_SOURCE_CODE IS 'PATIENT/ADM SOURCE CODE' ,
	PAT_STATUS_CODE IS 'PATIENT STATUS CODE' ,
	CONDITION_CODE_ARRAY01 IS 'CONDITION CODE ARRAY' ,
	CONDITION_CODE_ARRAY02 IS 'CONDITION CODE ARRAY' ,
	CONDITION_CODE_ARRAY03 IS 'CONDITION CODE ARRAY' ,
	CONDITION_CODE_ARRAY04 IS 'CONDITION CODE ARRAY' ,
	CONDITION_CODE_ARRAY05 IS 'CONDITION CODE ARRAY' ,
	CONDITION_CODE_ARRAY06 IS 'CONDITION CODE ARRAY' ,
	CONDITION_CODE_ARRAY07 IS 'CONDITION CODE ARRAY' ,
	SPECIAL_PROGRAM_INDICATOR IS 'SPECIAL PGM INDICATOR' ,
	PSRO_UR_PRO_APPROVAL_FLAG IS 'PSRO/UR/PRO APPROVAL CD' ,
	PSRO_UR_PRO_APPR_FROM_DATE IS 'PSRO/UR/PRO APP FROM DT' ,
	PSRO_UR_PRO_APPROVED_TO_DATE IS 'PSRO/UR/PRO APP TO DATE' ,
	PSRO_UR_PRO_OF_GRACE_DAYS IS 'PSRO/UR/PRO #GRACE DAYS' ,
	TRTMT_AUTH_CODE IS 'TREATMENT AUTH CODE' ,
	OCCURANCE_CODE_ARRAY01 IS 'OCCURANCE CODE ARRAY' ,
	OCCURANCE_CODE_ARRAY02 IS 'OCCURANCE CODE ARRAY' ,
	OCCURANCE_CODE_ARRAY03 IS 'OCCURANCE CODE ARRAY' ,
	OCCURANCE_CODE_ARRAY04 IS 'OCCURANCE CODE ARRAY' ,
	OCCURANCE_CODE_ARRAY05 IS 'OCCURANCE CODE ARRAY' ,
	OCCURANCE_DATE_ARRAY01 IS 'OCCURANCE DATES ARRAY' ,
	OCCURANCE_DATE_ARRAY02 IS 'OCCURANCE DATES ARRAY' ,
	OCCURANCE_DATE_ARRAY03 IS 'OCCURANCE DATES ARRAY' ,
	OCCURANCE_DATE_ARRAY04 IS 'OCCURANCE DATES ARRAY' ,
	OCCURANCE_DATE_ARRAY05 IS 'OCCURANCE DATES ARRAY' ,
	SPAN_CODE IS 'SPAN CODE' ,
	SPAN_FROM_DATE IS 'SPAN FROM DATE' ,
	SPAN_TO_DATE IS 'SPAN TO DATE' ,
	REASON_FOR_ADMISSION_DIAG01 IS 'REASON FOR ADMIS' ,
	REASON_FOR_ADMISSION_DIAG02 IS 'REASON FOR ADMIS' ,
	REASON_FOR_ADMISSION_DIAG03 IS 'REASON FOR ADMIS' ,
	REASON_FOR_ADMISSION_DIAG04 IS 'REASON FOR ADMIS' ,
	REASON_FOR_ADMISSION_DIAG05 IS 'REASON FOR ADMIS' ,
	COMPLICATIONS_DIAGNOSIS01 IS 'COMPL' ,
	COMPLICATIONS_DIAGNOSIS02 IS 'COMPL' ,
	COMPLICATIONS_DIAGNOSIS03 IS 'COMPL' ,
	MED_REQUIRED_PRIVATE_ROOM IS 'MED REQD PVT ROOM' ,
	GUAR_PAT_RELATIONSHIP_CODE IS 'GUAR/PAT RELAT. CODE' ,
	COST_OF_UNBILLED_CHARGES IS 'COST/UNBILL CHARGES' ,
	YEST_COST_OF_UNBILL_CHGS IS 'YEST COST/UNBILL CHGS' ,
	INSTITUTION_NAME IS 'INSTITUTION NAME' ,
	REREGISTER_RECURR_OUTP IS 'REREGISTER RECURR.OUTP.' ,
	STAY_DENIED_EFFECTIVE_DATE IS 'STAY DENIED EFFECT DATE' ,
	DENIAL_NOTIFICATION_DATE IS 'DATE DENIAL NOTIFICAT`N' ,
	TYPE_OF_ALTERNATE_CARE IS 'TYPE OF ALT CARE' ,
	ALTERNATE_CARD_DATE IS 'ALTERNATE CARE DATE' ,
	NUM_OF_CARVE_OUT_DAYS IS '# OF CARVE OUT DAYS' ,
	ACCIDENT_TYPE_CODE IS 'ACCIDENT TYPE CODE' ,
	WORKERS_COMPENSATION_CODE IS 'WORKERS COMP CODE' ,
	NO_FAULT_CODE IS 'NO FAULT CODE' ,
	ABORTION_STERILIZATION_CODE IS 'ABORTION/STERIL CODE' ,
	DATE_OF_LAST_MENSTRATION IS 'DATE/LAST MENSTRATION' ,
	RATE_CARD_CODE IS 'RATE CARE CODE' ,
	TRTMT_SCREEN_RELATED_CDE IS 'TREATMENT SCREEN CODE' ,
	CONSULTING_DR1_NUM IS 'CONS DR #' ,
	CONSULTING_DR2_NUM IS 'CONS DR #' ,
	CONSULTING_DR3_NUM IS 'CONS DR #' ,
	CONSULTING_DR4_NUM IS 'CONS DR #' ,
	CONSULTING_DR5_NUM IS 'CONS DR #' ,
	CLINIC_REGISTERED01 IS 'REG CLINIC 01' ,
	CLINIC_REGISTERED02 IS 'REG CLINIC 01' ,
	CLINIC_REGISTERED03 IS 'REG CLINIC 01' ,
	CLINIC_REGISTERED04 IS 'REG CLINIC 01' ,
	CLINIC_REGISTERED05 IS 'REG CLINIC 01' ,
	CLINIC_REGISTERED06 IS 'REG CLINIC 01' ,
	CLINIC_REGISTERED07 IS 'REG CLINIC 01' ,
	CLINIC_REGISTERED08 IS 'REG CLINIC 01' ,
	CLINIC_REGISTERED09 IS 'REG CLINIC 01' ,
	CLINIC_REGISTERED10 IS 'REG CLINIC 01' ,
	CLINIC_REGISTERED11 IS 'REG CLINIC 01' ,
	CLINIC_REGISTERED12 IS 'REG CLINIC 01' ,
	CLINIC_REGISTERED13 IS 'REG CLINIC 01' ,
	CLINIC_REGISTERED14 IS 'REG CLINIC 01' ,
	CLINIC_REGISTERED15 IS 'REG CLINIC 01' ,
	CLINIC_REGISTERED16 IS 'REG CLINIC 01' ,
	CLINIC_REGISTERED17 IS 'REG CLINIC 01' ,
	CLINIC_REGISTERED18 IS 'REG CLINIC 01' ,
	CLINIC_REGISTERED19 IS 'REG CLINIC 01' ,
	CLINIC_REGISTERED20 IS 'REG CLINIC 01' ,
	CLINIC_REGISTERED21 IS 'REG CLINIC 01' ,
	CLINIC_REGISTERED22 IS 'REG CLINIC 01' ,
	CLINIC_REGISTERED23 IS 'REG CLINIC 01' ,
	CLINIC_REGISTERED24 IS 'REG CLINIC 01' ,
	CLINIC_REGISTERED25 IS 'REG CLINIC 01' ,
	VALIDATE_BALANCE_FLAG IS 'VALIDATE BALANCE FLG' ,
	PRIVATE_ROOM_REASON IS 'PRIV ROOM REASON' ,
	PREV_BAD_DEBT_FLAG IS 'PREV BAD DEBT FLAG' ,
	MOTHER_BABY_FLAG_LB IS 'BILL CODE PRICE ARRAY(4)' ,
	EMERGENCY_OUTPAT_FLAG IS 'ER O/P FLAG' ,
	REFERRAL_SOURCE IS 'REFERRAL SOURCE' ,
	FATHER_DOB IS 'FATHER DOB' ,
	MOTHER_DOB IS 'REFERRAL SOURCE' ,
	REGIST_FORM IS 'REGIST FORM' ,
	PREGNANCY_TERMINATED IS 'PREGNANCY TERMINATED' ,
	MEDICARE_ELIGIBLE IS 'MEDICARE ELIGIBLE' ,
	ABORTION_CODE IS 'ABORTION  CODE' ,
	LAB_UPDATE_LOG_NUM IS 'LAB UPDATE LOG NUMBER' ,
	WARNING_FLAG IS 'WARNING FLAG' ,
	NAME_TITLE IS 'NAME TITLE' ,
	DATE_OF_BIRTH_CENTURY IS 'DATE OF BIRTH/CENTURY' ,
	ACCIDENT_COMMENT IS 'ACCIDENT COMMENT' ,
	MOTHER_BABY_ACCT1 IS 'MOTHER/BABY ACCT #1' ,
	MOTHER_BABY_ACCT2 IS 'MOTHER/BABY ACCT #2' ,
	MOTHER_BABY_ACCT3 IS 'MOTHER/BABY ACCT #3' ,
	LAST_REVIEW_DATE IS 'LAST REVIEW DATE' ,
	NEXT_REVIEW_DATE IS 'NEXT REVIEW DATE' ,
	PAT_LOCAL_ADDRESS IS 'LOCAL ADRESS' ,
	PAT_LOCAL_ADDRESS_CITY IS 'PAT LOCAL ADS CITY' ,
	LOCAL_ADDRESS_STATE_ID IS 'LOCAL ADDR STATE ID' ,
	PAT_LOCAL_5ZIP IS 'PATIENT LOCAL ZIP' ,
	PAT_LOCAL_9ZIP IS 'PATIENT LOCAL ZIP+4' ,
	AREA_CODE IS 'PHONE AREA CODE' ,
	PHONE_NUM IS 'PHONE NUMBER' ,
	ADMITING_DR_NUM IS 'ADMITING DOCTOR #' ,
	FORCE_BILL_FLAG IS 'FORCE BILL FLAG' ,
	ABSTRACT_EXISTS IS 'ABSTRACT EXISTS-Y/N' ,
	AML_FLAG IS 'AML FLAG' ,
	DIET_CODE IS 'DIET CODE' ,
	VALUABLES_ARE_TAKEN IS 'VALUABLES ARE TAKEN' ,
	SECOND_SPAN_CODE IS '2ND SPAN CODE' ,
	OCCURANCE_CODE_ARRAY6 IS 'OCCURANCE CODE ARRAY' ,
	OCCURANCE_CODE_ARRAY7 IS 'OCCURANCE CODE ARRAY' ,
	OCCURANCE_CODE_ARRAY8 IS 'OCCURANCE CODE ARRAY' ,
	OCCURANCE_DATE_ARRAY6 IS 'OCCURANCE DATES ARRAY' ,
	OCCURANCE_DATE_ARRAY7 IS 'OCCURANCE DATES ARRAY' ,
	OCCURANCE_DATE_ARRAY8 IS 'OCCURANCE DATES ARRAY' ,
	CENTURY_FOR_LPLDD IS 'DISCH CENT' ,
	ADT_CENTURY IS 'ADM CENT' ,
	DAT_CENTURY IS 'CENTURY' ,
	IPA_CLINIC IS 'IPA CLINIC' ,
	CLERGY_VISIT IS 'CLERGY VISIT' ,
	PAT_MMIDDLE_INITIAL IS 'PATIENT MIDDLE INITIAL' ,
	REFERRING_DR_NUM IS 'REFERRING DOCTOR #' ,
	OTHER_DR_NUM IS 'OTHER DOCTOR #' ,
	PARISH_CODE IS 'Parish Code' ,
	AUTO_ACCIDENT_STATE IS 'AUTO ACCIDENT STATE' ,
	COUNTRY_CODE IS 'COUNTRY CODE' ,
	RESEARCH_ID IS 'RESEARCH ID' ,
	SCHEDULED_CODE IS 'SCHEDULED CODE' ) ;

LABEL ON COLUMN &LIBRARY/ACCOUNTS
( FACILITYID TEXT IS 'HOSPITAL NUMBER' ,
	PAT_ACCT_NUM TEXT IS 'PATIENT ACCOUNT NUMBER' ,
	MED_RECORD_NUM TEXT IS 'MEDICAL RECORD NUMBER' ,
	PAT_LAST_NAME TEXT IS 'PATIENT LAST NAME' ,
	PAT_FIRST_NAME TEXT IS 'PATIENT FIRST NAME' ,
	RELIGION_CODE TEXT IS 'RELIGION CODE' ,
	INPAT_OUTPAT_FLAG TEXT IS 'INPATIENT/OUTPATIENT FLAG' ,
	GUARANTOR_NUM TEXT IS 'GUARANTOR NUMBER' ,
	ATTENDING_DR_NUM TEXT IS 'ATTENDING DOCTOR NUMBER' ,
	MED_SERVICE_CODE TEXT IS 'MEDICAL SERVICE CODE' ,
	ABSTRACT_REQUIRED TEXT IS 'ABSTRACT REQUIRED' ,
	MONTH_OF_ADMISSION TEXT IS 'MONTH OF ADMISSION' ,
	DAY_OF_ADMISSION TEXT IS 'DAY OF ADMISSION' ,
	YEAR_OF_ADMISSION TEXT IS 'YEAR OF ADMISSION' ,
	TIME_OF_ADMISSION TEXT IS 'TIME OF ADMISSION' ,
	DISCH_DATE TEXT IS 'DISCHARGE DATE' ,
	TIME_OF_DISCH TEXT IS 'TIME OF DISCHARGE' ,
	TYPE_OF_CERT TEXT IS 'TYPE OF CERTIFICATION' ,
	DAYS_PER_CERT TEXT IS 'DAYS PER CERTIFICATION' ,
	START_DATE_FOR_CURRENT_CERT TEXT IS 'START DATE FOR CURRENT CERT.' ,
	NEXT_CERTIFICATION_DATE TEXT IS 'NEXT CERTIFICATION DATE' ,
	DAYS_IN_INITIAL_CERT TEXT IS 'DAYS IN INITIAL CERTIFICATIO' ,
	NUM_OF_EXTENSIONS TEXT IS 'NUMBER OF EXTENSIONS' ,
	TOTAL_CERTIFIED_DAYS TEXT IS 'TOTAL CERTIFIED DAYS' ,
	ADMITTING_CATEGORY TEXT IS 'ADMITTING CATEGORY' ,
	NURSING_STATION TEXT IS 'NURSING STATION' ,
	ROOM_NUM TEXT IS 'ROOM NUMBER' ,
	BED_NUM TEXT IS 'BED NUMBER' ,
	RESERVED_FIELD_2_POSITION TEXT IS 'RESERVED FIELD  2 POSITION' ,
	PAT_TYPE TEXT IS 'PATIENT TYPE' ,
	ROOM_RATE TEXT IS 'ROOM RATE' ,
	ROOM_CHG_CHARGE_DESC_NUM TEXT IS 'ROOM CHG CHARGE DESC NUMBER' ,
	ISOLATION_CODE TEXT IS 'ISOLATION CODE' ,
	CONDITION_CODE TEXT IS 'CONDITION CODE' ,
	NUM_OF_VISITS TEXT IS 'NUMBER OF VISITS' ,
	OP_VISIT_NUM TEXT IS 'O/P VISIT #' ,
	LAST_CYCLE_BILL_NUM TEXT IS 'LAST CYCLE BILL NUMBER' ,
	HOW_ARRIVED TEXT IS 'HOW ARRIVED' ,
	DIAGNOSIS TEXT IS 'DIAGNOSIS' ,
	CODED_DIAGNOSIS01 TEXT IS 'CODED DIAGNOSIS' ,
	CODED_DIAGNOSIS02 TEXT IS 'CODED DIAGNOSIS' ,
	CODED_DIAGNOSIS03 TEXT IS 'CODED DIAGNOSIS' ,
	CODED_DIAGNOSIS04 TEXT IS 'CODED DIAGNOSIS' ,
	CODED_DIAGNOSIS05 TEXT IS 'CODED DIAGNOSIS' ,
	CODED_DIAGNOSIS06 TEXT IS 'CODED DIAGNOSIS' ,
	CODED_DIAGNOSIS07 TEXT IS 'CODED DIAGNOSIS' ,
	CODED_DIAGNOSIS08 TEXT IS 'CODED DIAGNOSIS' ,
	TYPE_OF_REGISTRATION TEXT IS 'TYPE OF REGISTRATION' ,
	PENDING_PURGE TEXT IS 'PENDING PURGE' ,
	CORONER_CASE TEXT IS 'CORONER CASE' ,
	OPERATING_DR_NUM TEXT IS 'OPERATING DOCTOR NUMBER' ,
	OP_PROCEDUR01 TEXT IS 'OPERATIVE PROCEDURES' ,
	OP_PROCEDUR02 TEXT IS 'OPERATIVE PROCEDURES' ,
	OP_PROCEDUR03 TEXT IS 'OPERATIVE PROCEDURES' ,
	OP_PROCEDUR04 TEXT IS 'OPERATIVE PROCEDURES' ,
	OP_PROCEDUREDATE01 TEXT IS 'DATES FOR OPERATIVE PROCEDUR' ,
	OP_PROCEDUREDATE02 TEXT IS 'DATES FOR OPERATIVE PROCEDUR' ,
	OP_PROCEDUREDATE03 TEXT IS 'DATES FOR OPERATIVE PROCEDUR' ,
	OP_PROCEDUREDATE04 TEXT IS 'DATES FOR OPERATIVE PROCEDUR' ,
	ACCIDENT_LOCATION TEXT IS 'ACCIDENT LOCATION' ,
	ACCIDENT_TIME TEXT IS 'ACCIDENT TIME' ,
	MOTHER_BABY_FLAG_LP TEXT IS 'MOTHER-BABY FLAG' ,
	DISCOUNT_PCT TEXT IS 'DISCOUNT PER CENT' ,
	EXPIRATION_DATE_FOR_DISCOUNT TEXT IS 'EXPIRATION DATE FOR DISCOUNT' ,
	RELATIONSHIP_TO_GUARANTOR TEXT IS 'RELATIONSHIP TO GUARANTOR' ,
	BATCH_BALANCE TEXT IS 'BATCH BALANCE' ,
	CURRENT_BALANCE TEXT IS 'CURRENT BALANCE' ,
	BALANCE_OF_UNBILLED_CHARGES TEXT IS 'BALANCE OF UNBILLED CHARGES' ,
	TOTAL_CHARGES_FOR_ACCT TEXT IS 'TOTAL CHARGES FOR ACCOUNT' ,
	TOTAL_ADJ_FOR_THIS_ACCT TEXT IS 'TOTAL ADJ FOR THIS ACCOUNT' ,
	TOTAL_PAYMENTS_FOR_ACCT TEXT IS 'TOTAL PAYMENTS FOR ACCOUNT' ,
	DATE_OF_LAST_PAYMENT TEXT IS 'DATE OF LAST PAYMENT' ,
	BALANCE_ON_LAST_STATEMENT TEXT IS 'BALANCE ON LAST STATEMENT' ,
	DATE_OF_LAST_CYCLE_BILL TEXT IS 'DATE OF LAST CYCLE BILL' ,
	DATE_OF_LAST_STATEMENT TEXT IS 'DATE OF LAST STATEMENT' ,
	DAYS_IN_STAY TEXT IS '# OF DAYS IN STAY' ,
	DATE_OF_LAST_ROOM_CHARGE TEXT IS 'DATE OF LAST ROOM CHARGE' ,
	DISCH_PENDING_UPDATE_FLA TEXT IS 'DISCHARGE PENDING UPDATE FLA' ,
	DISCH_CODE TEXT IS 'DISCHARGE CODE' ,
	ACUITY_CODE TEXT IS 'ACUITY CODE' ,
	DIABETIC TEXT IS 'DIABETIC' ,
	FLAG_INS_BENEFITS_EXIST TEXT IS 'FLAG - INS BENEFITS EXIST' ,
	FINAL_BILLING_FLAG TEXT IS 'FINAL BILLING FLAG -Y-YES' ,
	DAILY_FLAG TEXT IS 'DAILY FLAG' ,
	YESTERDAY_INPAT_STATUS TEXT IS 'YESTERDAY INPATIENT STATUS' ,
	YESTERDAY_OUTPAT_STATUS TEXT IS 'YESTERDAY OUTPATIENT STATUS' ,
	YESTERDAY_NURSING_STATION TEXT IS 'YESTERDAY''S NURSING STATION' ,
	YESTERDAY_ROOM_NUM TEXT IS 'YESTERDAY''S ROOM NUMBER' ,
	YESTERDAY_BED_NUM TEXT IS 'YESTERDAY''S BED NUMBER' ,
	YESTERDAY_BATCH_BALANCE TEXT IS 'YESTERDAY''S BATCH BALANCE' ,
	YESTERDAY_CURRENT_BALANCE TEXT IS 'YESTERDAY''S CURRENT BALANCE' ,
	YESTERDAY_BAL_UNBILLED_CHGS TEXT IS 'YESTERDAY BAL-UNBILLED CHGS' ,
	DATE_OF_LAST_MAINTENANCE TEXT IS 'DATE OF LAST MAINTENANCE' ,
	LAST_MAINTENANCE_LOG_NUM TEXT IS 'LAST MAINTENANCE LOG NUMBER' ,
	UPDATE_LOG_NUM TEXT IS 'UPDATE LOG NUMBER' ,
	CUMULATIVE_BAD_DEBT_WRITEOFF TEXT IS 'CUMULATIVE BAD DEBT WRITEOFF' ,
	MOTHER_PAT_ACCT TEXT IS 'MOTHER''S PATIENT ACCOUNT #' ,
	INPAT_STATUS_CODE TEXT IS 'INPATIENT STATUS CODE' ,
	OUTPAT_STATUS_CODE TEXT IS 'OUTPATIENT STATUS CODE' ,
	LAST_CLINIC_REGISTERED_FOR TEXT IS 'LAST CLINIC REGISTERED FOR' ,
	DATE_OF_INITIAL_REGISTRATION TEXT IS 'DATE OF INITIAL REGISTRATION' ,
	FINAL_LAB_SUMMARY_PRINTED TEXT IS 'FINAL LAB SUMMARY PRINTED' ,
	YEST_FINAL_LAB_SUMMARY_FLAG TEXT IS 'YEST FINAL LAB SUMMARY FLAG' ,
	MONTH_PORTION_OF_DATE TEXT IS 'MONTH PORTION OF DATE' ,
	DAY_PORTION_OF_DATE TEXT IS 'DAY PORTION OF DATE' ,
	YEAR_PORTION_OF_DATE TEXT IS 'YEAR PORTION OF DATE' ,
	DELETE_CODE TEXT IS 'DELETE CODE' ,
	PAT_ADMIT_SOURCE_CODE TEXT IS 'PATIENT/ADMIT. SOURCE CODE' ,
	PAT_STATUS_CODE TEXT IS 'PATIENT STATUS CODE' ,
	CONDITION_CODE_ARRAY01 TEXT IS 'CONDITION CODE ARRAY' ,
	CONDITION_CODE_ARRAY02 TEXT IS 'CONDITION CODE ARRAY' ,
	CONDITION_CODE_ARRAY03 TEXT IS 'CONDITION CODE ARRAY' ,
	CONDITION_CODE_ARRAY04 TEXT IS 'CONDITION CODE ARRAY' ,
	CONDITION_CODE_ARRAY05 TEXT IS 'CONDITION CODE ARRAY' ,
	CONDITION_CODE_ARRAY06 TEXT IS 'CONDITION CODE ARRAY' ,
	CONDITION_CODE_ARRAY07 TEXT IS 'CONDITION CODE ARRAY' ,
	SPECIAL_PROGRAM_INDICATOR TEXT IS 'SPECIAL PROGRAM INDICATOR' ,
	PSRO_UR_PRO_APPROVAL_FLAG TEXT IS 'PSRO/UR/PRO APPROVAL FLAG' ,
	PSRO_UR_PRO_APPR_FROM_DATE TEXT IS 'PSRO/UR/PRO APPR FROM DATE' ,
	PSRO_UR_PRO_APPROVED_TO_DATE TEXT IS 'PSRO/UR/PRO APPROVED TO DATE' ,
	PSRO_UR_PRO_OF_GRACE_DAYS TEXT IS 'PSRO/UR/PRO # OF GRACE DAYS' ,
	TRTMT_AUTH_CODE TEXT IS 'TREATMENT AUTHORIZATION CODE' ,
	OCCURANCE_CODE_ARRAY01 TEXT IS 'OCCURANCE CODE ARRAY' ,
	OCCURANCE_CODE_ARRAY02 TEXT IS 'OCCURANCE CODE ARRAY' ,
	OCCURANCE_CODE_ARRAY03 TEXT IS 'OCCURANCE CODE ARRAY' ,
	OCCURANCE_CODE_ARRAY04 TEXT IS 'OCCURANCE CODE ARRAY' ,
	OCCURANCE_CODE_ARRAY05 TEXT IS 'OCCURANCE CODE ARRAY' ,
	OCCURANCE_DATE_ARRAY01 TEXT IS 'OCCURANCE DATES ARRAY' ,
	OCCURANCE_DATE_ARRAY02 TEXT IS 'OCCURANCE DATES ARRAY' ,
	OCCURANCE_DATE_ARRAY03 TEXT IS 'OCCURANCE DATES ARRAY' ,
	OCCURANCE_DATE_ARRAY04 TEXT IS 'OCCURANCE DATES ARRAY' ,
	OCCURANCE_DATE_ARRAY05 TEXT IS 'OCCURANCE DATES ARRAY' ,
	SPAN_CODE TEXT IS 'SPAN CODE' ,
	SPAN_FROM_DATE TEXT IS 'SPAN FROM DATE' ,
	SPAN_TO_DATE TEXT IS 'SPAN TO DATE' ,
	REASON_FOR_ADMISSION_DIAG01 TEXT IS 'REASON FOR ADMISSION DIAG' ,
	REASON_FOR_ADMISSION_DIAG02 TEXT IS 'REASON FOR ADMISSION DIAG' ,
	REASON_FOR_ADMISSION_DIAG03 TEXT IS 'REASON FOR ADMISSION DIAG' ,
	REASON_FOR_ADMISSION_DIAG04 TEXT IS 'REASON FOR ADMISSION DIAG' ,
	REASON_FOR_ADMISSION_DIAG05 TEXT IS 'REASON FOR ADMISSION DIAG' ,
	COMPLICATIONS_DIAGNOSIS01 TEXT IS 'COMPLICATIONS DIAGNOSIS' ,
	COMPLICATIONS_DIAGNOSIS02 TEXT IS 'COMPLICATIONS DIAGNOSIS' ,
	COMPLICATIONS_DIAGNOSIS03 TEXT IS 'COMPLICATIONS DIAGNOSIS' ,
	MED_REQUIRED_PRIVATE_ROOM TEXT IS 'MED. REQUIRED PRIVATE ROOM' ,
	GUAR_PAT_RELATIONSHIP_CODE TEXT IS 'GUAR/PAT RELATIONSHIP CODE' ,
	COST_OF_UNBILLED_CHARGES TEXT IS 'COST OF UNBILLED CHARGES' ,
	YEST_COST_OF_UNBILL_CHGS TEXT IS 'YEST. COST OF UNBILL CHGS' ,
	INSTITUTION_NAME TEXT IS 'INSTITUTION NAME' ,
	REREGISTER_RECURR_OUTP TEXT IS 'REREGISTER RECURR.OUTP.' ,
	STAY_DENIED_EFFECTIVE_DATE TEXT IS 'STAY DENIED EFFECTIVE DATE' ,
	DENIAL_NOTIFICATION_DATE TEXT IS 'DENIAL NOTIFICATION DATE' ,
	TYPE_OF_ALTERNATE_CARE TEXT IS 'TYPE OF ALTERNATE CARE' ,
	ALTERNATE_CARD_DATE TEXT IS 'ALTERNATE CARD DATE' ,
	NUM_OF_CARVE_OUT_DAYS TEXT IS 'NUMBER OF CARVE OUT DAYS' ,
	ACCIDENT_TYPE_CODE TEXT IS 'ACCIDENT TYPE CODE' ,
	WORKERS_COMPENSATION_CODE TEXT IS 'WORKERS COMPENSATION CODE' ,
	NO_FAULT_CODE TEXT IS 'NO FAULT CODE' ,
	ABORTION_STERILIZATION_CODE TEXT IS 'ABORTION/STERILIZATION CODE' ,
	DATE_OF_LAST_MENSTRATION TEXT IS 'DATE OF LAST MENSTRATION' ,
	RATE_CARD_CODE TEXT IS 'RATE CARD CODE' ,
	TRTMT_SCREEN_RELATED_CDE TEXT IS 'TREATMENT SCREEN RELATED CDE' ,
	CONSULTING_DR1_NUM TEXT IS 'CONSULTING DOCTOR NUMBER' ,
	CONSULTING_DR2_NUM TEXT IS 'CONSULTING DOCTOR NUMBER' ,
	CONSULTING_DR3_NUM TEXT IS 'CONSULTING DOCTOR NUMBER' ,
	CONSULTING_DR4_NUM TEXT IS 'CONSULTING DOCTOR NUMBER' ,
	CONSULTING_DR5_NUM TEXT IS 'CONSULTING DOCTOR NUMBER' ,
	CLINIC_REGISTERED01 TEXT IS 'CLINIC REGISTERED -  1' ,
	CLINIC_REGISTERED02 TEXT IS 'CLINIC REGISTERED -  1' ,
	CLINIC_REGISTERED03 TEXT IS 'CLINIC REGISTERED -  1' ,
	CLINIC_REGISTERED04 TEXT IS 'CLINIC REGISTERED -  1' ,
	CLINIC_REGISTERED05 TEXT IS 'CLINIC REGISTERED -  1' ,
	CLINIC_REGISTERED06 TEXT IS 'CLINIC REGISTERED -  1' ,
	CLINIC_REGISTERED07 TEXT IS 'CLINIC REGISTERED -  1' ,
	CLINIC_REGISTERED08 TEXT IS 'CLINIC REGISTERED -  1' ,
	CLINIC_REGISTERED09 TEXT IS 'CLINIC REGISTERED -  1' ,
	CLINIC_REGISTERED10 TEXT IS 'CLINIC REGISTERED -  1' ,
	CLINIC_REGISTERED11 TEXT IS 'CLINIC REGISTERED -  1' ,
	CLINIC_REGISTERED12 TEXT IS 'CLINIC REGISTERED -  1' ,
	CLINIC_REGISTERED13 TEXT IS 'CLINIC REGISTERED -  1' ,
	CLINIC_REGISTERED14 TEXT IS 'CLINIC REGISTERED -  1' ,
	CLINIC_REGISTERED15 TEXT IS 'CLINIC REGISTERED -  1' ,
	CLINIC_REGISTERED16 TEXT IS 'CLINIC REGISTERED -  1' ,
	CLINIC_REGISTERED17 TEXT IS 'CLINIC REGISTERED -  1' ,
	CLINIC_REGISTERED18 TEXT IS 'CLINIC REGISTERED -  1' ,
	CLINIC_REGISTERED19 TEXT IS 'CLINIC REGISTERED -  1' ,
	CLINIC_REGISTERED20 TEXT IS 'CLINIC REGISTERED -  1' ,
	CLINIC_REGISTERED21 TEXT IS 'CLINIC REGISTERED -  1' ,
	CLINIC_REGISTERED22 TEXT IS 'CLINIC REGISTERED -  1' ,
	CLINIC_REGISTERED23 TEXT IS 'CLINIC REGISTERED -  1' ,
	CLINIC_REGISTERED24 TEXT IS 'CLINIC REGISTERED -  1' ,
	CLINIC_REGISTERED25 TEXT IS 'CLINIC REGISTERED -  1' ,
	VALIDATE_BALANCE_FLAG TEXT IS 'VALIDATE BALANCE FLAG' ,
	PRIVATE_ROOM_REASON TEXT IS 'PRIVATE ROOM REASON' ,
	PREV_BAD_DEBT_FLAG TEXT IS 'PREV BAD DEBT FLAG' ,
	MOTHER_BABY_FLAG_LB TEXT IS 'MOTHER BABY FLAG' ,
	EMERGENCY_OUTPAT_FLAG TEXT IS 'EMERGENCY OUTPATIENT FLAG' ,
	FINANCIAL_CLASS_CODE TEXT IS 'FINANCIAL CLASS CODE' ,
	ACCOMODATION_CODE TEXT IS 'ACCOMODATION CODE' ,
	REFERRAL_SOURCE TEXT IS 'REFERRAL SOURCE' ,
	FATHER_DOB TEXT IS 'FATHER DOB' ,
	MOTHER_DOB TEXT IS 'MOTHER DOB' ,
	REGIST_FORM TEXT IS 'REGIST FORM' ,
	PREGNANCY_TERMINATED TEXT IS 'PREGNANCY TERMINATED' ,
	MEDICARE_ELIGIBLE TEXT IS 'MEDICARE ELIGIBLE (Y/N)' ,
	ABORTION_CODE TEXT IS 'ABORTION CODE' ,
	LAB_UPDATE_LOG_NUM TEXT IS 'LAB UPDATE LOG NUMBER' ,
	WARNING_FLAG TEXT IS 'WARNING FLAG' ,
	NAME_TITLE TEXT IS 'NAME TITLE' ,
	DATE_OF_BIRTH_CENTURY TEXT IS 'DATE OF BIRTH/CENTURY' ,
	ACCIDENT_COMMENT TEXT IS 'ACCIDENT COMMENT' ,
	MOTHER_BABY_ACCT1 TEXT IS 'MOTHER/BABY ACCT #1' ,
	MOTHER_BABY_ACCT2 TEXT IS 'MOTHER/BABY ACCT #2' ,
	MOTHER_BABY_ACCT3 TEXT IS 'MOTHER/BABY ACCT #3' ,
	LAST_REVIEW_DATE TEXT IS 'LAST REVIEW DATE' ,
	NEXT_REVIEW_DATE TEXT IS 'NEXT REVIEW DATE' ,
	PAT_LOCAL_ADDRESS TEXT IS 'PATIENT LOCAL ADDRESS' ,
	PAT_LOCAL_ADDRESS_CITY TEXT IS 'PATIENT LOCAL ADDRESS CITY' ,
	LOCAL_ADDRESS_STATE_ID TEXT IS 'LOCAL ADDRESS STATE ID' ,
	PAT_LOCAL_5ZIP TEXT IS 'PATIENT LOCAL ZIP' ,
	PAT_LOCAL_9ZIP TEXT IS 'PATIENT LOCAL ZIP+4' ,
	AREA_CODE TEXT IS 'AREA CODE' ,
	PHONE_NUM TEXT IS 'PHONE NUMBER' ,
	ADMITING_DR_NUM TEXT IS 'ADMITING DOCTOR #' ,
	FORCE_BILL_FLAG TEXT IS 'FORCE BILL FLAG' ,
	ABSTRACT_EXISTS TEXT IS 'ABSTRACT EXISTS-Y/N' ,
	AML_FLAG TEXT IS 'AML FLAG' ,
	DIET_CODE TEXT IS 'DIET CODE' ,
	VALUABLES_ARE_TAKEN TEXT IS 'VALUABLES ARE TAKEN' ,
	SECOND_SPAN_CODE TEXT IS '2ND SPAN CODE' ,
	OCCURANCE_CODE_ARRAY6 TEXT IS 'OCCURANCE CODE ARRAY' ,
	OCCURANCE_CODE_ARRAY7 TEXT IS 'OCCURANCE CODE ARRAY' ,
	OCCURANCE_CODE_ARRAY8 TEXT IS 'OCCURANCE CODE ARRAY' ,
	OCCURANCE_DATE_ARRAY6 TEXT IS 'OCCURANCE DATES ARRAY' ,
	OCCURANCE_DATE_ARRAY7 TEXT IS 'OCCURANCE DATES ARRAY' ,
	OCCURANCE_DATE_ARRAY8 TEXT IS 'OCCURANCE DATES ARRAY' ,
	CENTURY_FOR_LPLDD TEXT IS 'CENTURY FOR LPLDD' ,
	ADT_CENTURY TEXT IS 'CENTURY FOR LPADT1,2,3' ,
	DAT_CENTURY TEXT IS 'CENTURY FOR LPDAT1,2,3' ,
	FILLER TEXT IS 'FILLER' ,
	IPA_CLINIC TEXT IS 'IPA CLINIC' ,
	CLERGY_VISIT TEXT IS 'CLERGY VISIT' ,
	PAT_MMIDDLE_INITIAL TEXT IS 'PATIENT MIDDLE INITIAL' ,
	REFERRING_DR_NUM TEXT IS 'REFERRING DOCTOR #' ,
	OTHER_DR_NUM TEXT IS 'OTHER DOCTOR #' ,
	PARISH_CODE TEXT IS 'Parish Code' ,
	AUTO_ACCIDENT_STATE TEXT IS 'AUTO ACCIDENT STATE' ,
	COUNTRY_CODE TEXT IS 'COUNTRY CODE' ,
	IPA TEXT IS 'IPA' ,
	RESEARCH_ID TEXT IS 'RESEARCH ID' ,
	SCHEDULED_CODE TEXT IS 'SCHEDULED CODE' ) ;
