/**********************************************************************/                                    
/*                                                                    */                                    
/* iSeries400    ACCOUNTPROXIES - SQL VIEW FOR PX                     */                                    
/*                                                                    */                                    
/*    ************************************************************    */                                    
/*    * Perot Systems, Copyright 2003, All rights reserved(U.S.) *    */                                    
/*    *                                                          *    */                                    
/*    * This unpublished material is proprietary to Perot Sys.   *    */                                    
/*    * The methods and techniques described herein are          *    */                                    
/*    * considered trade secrets and/or confidential.            *    */                                    
/*    * Reproduction or distribution, in whole or in part, is    *    */                                    
/*    * forbidden except by express written permission of        *    */                                    
/*    * Perot Systems, Inc.                                      *    */                                    
/*    ************************************************************    */                                    
/*                                                                    */                                    
/**********************************************************************/                                    
/*  Date        Programmer          Modification Description          */                                    
/**********************************************************************/                                    
/* 11/01/2006 I  KEVIN SEDOTA      I MODIFIED STORED VIEW             */
/* 09/18/2007 I  Gauthreaux		   I Add doco for table names & locs  */                                    
/* 12/29/2010 I  Deepa Raju        I SR1190 - Read new column to      */        
/*            I                    I   denote Short Registration acct */    
/* 07/20/2011 I  Nereid Tavares    I SR1557 - Read new column to      */        
/*            I                    I   denote Newborn Reg acct        */
/* 10/19/2011 I  Nereid Tavares    I Dft18075 - Read LPADMC from      */        
/*            I                    I   HPADLPP table                  */              
/* 04/30/2012 I  Nereid Tavares    I SR1623 - Read LPBTFG from      */        
/*            I                    I   HPADLPP table                  */              

/**********************************************************************/                                    
                                                                                                            
SET PATH *LIBL;                                                                                             
                                                                                                            
CREATE VIEW &LIBRARY/ACCOUNTPROXIES ( 
	FACILITYID , 
	MEDICALRECORDNUMBER FOR COLUMN MEDIC00001 , 
	ACCOUNTNUMBER FOR COLUMN ACCOU00001 , 
	ADMISSIONDATE FOR COLUMN ADMIS00001 , 
	DISCHARGEDATE FOR COLUMN DISCH00001 , 
	SERVICECODE FOR COLUMN SERVI00001 , 
	CLINICCODEID FOR COLUMN CLINI00001 , 
	CLINICCODE , 
	CLINICDESCRIPTION FOR COLUMN CLINI00002 , 
	FINANCIALCODE FOR COLUMN FINAN00001 , 
	FIRSTNAME , 
	LASTNAME , 
	MIDDLEINITIAL FOR COLUMN MIDDL00001 , 
	PATIENTTYPE FOR COLUMN PATIE00001 , 
	OPSTATUSCODE FOR COLUMN OPSTA00001 , 
	IPSTATUSCODE FOR COLUMN IPSTA00001 , 
	FINALBILLINGFLAG FOR COLUMN FINAL00001 , 
	OPVISITNUMBER FOR COLUMN OPVIS00001 , 
	PENDINGPURGE FOR COLUMN PENDI00001 , 
	UNBILLEDBALANCE FOR COLUMN UNBIL00001 , 
	MEDICALSERVICECODE FOR COLUMN MEDIC00002 , 
	LOCKINDICATOR FOR COLUMN LOCKI00001 , 
	LOCKERPBARID FOR COLUMN LOCKI00002 , 
	LOCKDATE FOR COLUMN LOCKI00003 , 
	LOCKTIME FOR COLUMN LOCKI00004 ,
	SHORTREGTYPE FOR COLUMN SHTRG00001, 
	NEWBORNREGTYPE FOR COLUMN NWBRG00001,
	ADMITCATEGORY FOR COLUMN ADMCG00001 ,
	BIRTHTIMEENTERED FOR COLUMN BTENT00001,
	OPERATINGDRID FOR COLUMN OPERA00001 , 
	ATTENDINGDRID FOR COLUMN ATTEN00001 , 
	ADMITTINGDRID FOR COLUMN ADMIT00001 , 
	REFERINGDRID FOR COLUMN REFER00001 , 
	OTHERDRID , 
	CONSULTINGDR1ID FOR COLUMN CONSU00001 , 
	CONSULTINGDR2ID FOR COLUMN CONSU00002 , 
	CONSULTINGDR3ID FOR COLUMN CONSU00003 , 
	CONSULTINGDR4ID FOR COLUMN CONSU00004 , 
	CONSULTINGDR5ID FOR COLUMN CONSU00005 , 
	NURSINGSTATION FOR COLUMN NURSI00001 , 
	ROOM , 
	BED , 
	ISOLATIONCODE FOR COLUMN ISOLA00001 , 
	PENDINGDISCHARGE FOR COLUMN PENDI00002 , 
	DISCHARGECODE FOR COLUMN DISCH00002 , 
	VALUABLESARETAKEN FOR COLUMN VALUA00001 , 
	ABSTRACTEXISTS FOR COLUMN ABSTR00001 , 
	CLERGYVISIT FOR COLUMN CLERG00001 , 
	CHIEFCOMPLAINT FOR COLUMN CHIEF00001 , 
	ACCOMODATIONCODE FOR COLUMN ACCOM00001 , 
	ACCOMODATIONDESC FOR COLUMN ACCOM00002 , 
	BLOODLESS , 
	RELIGIONID , 
	PLACEOFWORSHIP FOR COLUMN PLACE00001 , 
	DOB , 
	GENDERID , 
	OPTOUT , 
	ADMITSOURCECODE FOR COLUMN ADMIT00002 , 
	CONFIDENTIAL FOR COLUMN CONFI00001 , 
	PREDISCHARGESTATUS FOR COLUMN PREDI00001 , 
	LASTMAINTENANCEDATE FOR COLUMN LASTM00001 , 
	LASTMAINTENANCELOGNUMBER FOR COLUMN LASTM00002 , 
	UPDATELOGNUMBER FOR COLUMN UPDAT00001 , 
	LOCKEDWORKSTATION FOR COLUMN LOCKE00001 , 
	LFKEY )
	 
	AS 

	SELECT A.LPHSP# AS FACILITYID , 	 
		A.LPMRC# AS MEDREC , 	 
		A.LPACCT AS ACCOUNTNUMBER , 	 
		CASE WHEN A.LPADT1 = 0 OR A.LPADT2 = 0 	 
		THEN NULL 	 
		ELSE TIMESTAMP(DATE(TRIM(CHAR(A.LPADT1))||'/' || 	 
		TRIM(CHAR(A.LPADT2))||'/'||TRIM(A.LPADT4)|| 	 
		RIGHT('0' ||TRIM(CHAR(A.LPADT3)),2)), 	 
		TIME(SUBSTR(RIGHT('0000' || 	 
		TRIM(CHAR(ABS(A.LPLAT))),4) ,1,2)||'.'|| 	 
		SUBSTR(RIGHT('0000' || 	 
		TRIM(CHAR(ABS(A.LPLAT))),4),3,2)||'.00')) 	 
		END , 	 
		CASE LPLDD WHEN 0 	 
		THEN NULL 	 
		ELSE TIMESTAMP( 	 
		DATE(RTRIM(CASE WHEN LENGTH(TRIM(LPLDD)) = 5 	 
		THEN '0' || SUBSTR(TRIM(A.LPLDD),1,1) 	 
		ELSE SUBSTR(TRIM(A.LPLDD),1,2) END) || '/' || 	
		CASE WHEN LENGTH(TRIM(LPLDD)) = 5 	 
		THEN SUBSTR(TRIM(A.LPLDD),2,2) 	 
		ELSE SUBSTR(TRIM(A.LPLDD),3,2) 	 
		END || '/' || A.LPLDDC || 	 
		CASE WHEN LENGTH(TRIM(LPLDD)) = 5 	 
		THEN SUBSTR(TRIM(A.LPLDD),4,2) 	 
		ELSE SUBSTR(A.LPLDD,5,2) END) , 	 
		TIME(SUBSTR(RIGHT('0000'|| 	 
		TRIM(CHAR(ABS(A.LPLDT))),4),1,2) ||'.'|| 	 
		SUBSTR(RIGHT('0000' || 	 
		TRIM(CHAR(ABS(A.LPLDT))),4),3,2)||'.00')) 	 
		END AS DISCHDATE , 	 
		A.LPMSV AS SERVICECODE , 
		' ' AS CLINICCODEID , 	 
		A.LPCL01 AS CLINICCODE , 	 
		C.QTCDES AS CLINICDESCRIPTION , 	 
		A.LPFC AS FINANCIALCODE , 	 
		A.LPPFNM AS FIRSTNAME , 	 
		A.LPPLNM AS LASTNAME , 	 
		A.LPPMI AS MIDDLEINITIAL , 	 
		A.LPPTYP AS PATIENTTYPE , 	 
		A.LPPSTO AS OPSTATUSCODE , 	 
		A.LPPSTI AS IPSTATUSCODE , 	 
		A.LPFBIL AS FINALBILLINGFLAG , 	 
		A.LPVIS# AS OPVISITNUMBER , 	 
		A.LPPOLN AS PENDINGPURGE , 	 
		A.LPUBAL AS UNBILLEDBALANCE , 	 
		A.LPMSV AS MEDICALSERVICECODE , 	 
		H.LFRCID AS LOCKINDICATOR , 	 
		H.LFUSER AS LOCKERPBARID , 	 
		H.LFTDAT AS LOCKDATE , 	 
		H.LFTTIM AS LOCKTIME ,
		A.LPRGTP AS SHORTREGTYPE , 
		A.LPNBFG AS NEWBORNREGTYPE ,	
		A.LPADMC AS ADMITCATEGORY ,  
		A.LPBTFG AS BIRTHTIMEENTERED ,
		A.LPODR# AS OPERATINGDRID , 	 
		A.LPADR# AS ATTENDINGDRID , 	 
		A.LPMDR# AS ADMITTINGDRID , 	 
		A.LPRDR# AS REFERINGDRID , 	 
		A.LPTDR# AS OTHERDRID , 	 
		A.LPMD01 AS CONSULTINGDR1ID , 	 
		A.LPMD02 AS CONSULTINGDR2ID , 	 
		A.LPMD03 AS CONSULTINGDR3ID , 	 
		A.LPMD04 ASCONSULTINGDR4ID , 	 
		A.LPMD05 AS CONSULTINGDR5ID , 	 
		A.LPNS AS NURSINGSTATION , 	 
		A.LPROOM AS ROOM , 	 
		A.LPBED AS BED , 	 
		A.LPISO AS ISOLATIONCODE , 	 
		A.LPDSFL AS PENDINGDISCHARGE , 	 
		A.LPDCOD AS DISCHARGECODE , 	 
		A.LPVALU AS VALUABLESARETAKEN , 	 
		A.LPABST AS ABSTRACTEXISTS , 	 
		A.LPCLVS AS CLERGYVISIT , 	 
		A.LPDIAG AS CHIEFCOMPLAINT , 	 
		A.LPACC AS ACCOMODATIONCODE , 	 
		AC.QTACCD AS ACCOMODATIONDESC , 	 
		I.MDBLDL AS BLOODLESS , 	 
		I.MDRLGN AS RELIGIONID , 	 
		I.MDPARC AS PLACEOFWORSHIP , 	 
		I.MDDOB8 AS DOB , 	 
		I.MDSEX AS GENDERID , 	 
		I.MDNPPF AS OPTOUT , 	 
		A.LPPSRC , 	 
		R.RWCNFG , 	 
		A.FLR142 , 	 
		A.LPLMD , 	 
		A.LPLML , 	 
		A.LPLUL# , 	 
		H.LFTTIM AS LOCKEDWORKSTATION, 
		H.LFKEY AS LFKEY 	 
		FROM HPDATA1/HPADLPP A 	 
		LEFT JOIN HPDATA1/HPADQTCL C 	 
		ON (A.LPHSP# = C.QTHSP# 	 
			AND A.LPCL01 = C.QTKEY) 	 
		LEFT JOIN XADATA/NQHRLFP H 	 
		ON (         LPAD(TRIM(CHAR(A.LPACCT)),9,'0') 		
			= SUBSTR(H.LFKEY,1,9) 	 
			AND A.LPHSP# = H.LFHSP#) 	 
		LEFT JOIN HPDATA1/HPADMDP I 	 
		ON (A.LPHSP# = I.MDHSP# 	 
			AND A.LPMRC# = I.MDMRC#) 	 
		LEFT JOIN HPDATA1/HXMRRWP R 	 
		ON (A.LPHSP# = R.RWHSP# 
			AND A.LPACCT=R.RWACCT 	 
			AND A.LPMRC# = R.RWMRC# ) 	 
		LEFT OUTER JOIN HPDATA1/HPADQTAC AC 	 
		ON (A.LPACC=AC.QTKEY AND A.LPHSP#=AC.QTHSP#)   
		
-- SQL1514 10 Schema qualifier in ACCOUNTPROXIES in PACCESS was removed.
	  
	RCDFMT ACCOU00001 ; 
  
LABEL ON COLUMN &LIBRARY/ACCOUNTPROXIES 
( FACILITYID IS 'HOSP#' , 
	MEDICALRECORDNUMBER IS 'MEDICAL RECORD#' , 
	ACCOUNTNUMBER IS 'ACCT.#' , 
	SERVICECODE IS 'MED SVC CODE' , 
	CLINICCODE IS 'REG CLINIC 01' , 
	CLINICDESCRIPTION IS 'DESCRIPTION' , 
	FIRSTNAME IS 'FIRST NAME' , 
	LASTNAME IS 'LAST NAME' , 
	MIDDLEINITIAL IS 'PATIENT MIDDLE INITIAL' , 
	PATIENTTYPE IS 'PATIENT TYPE' , 
	OPSTATUSCODE IS 'CURR O/P STATUS' , 
	IPSTATUSCODE IS 'CURR I/P STATUS' , 
	FINALBILLINGFLAG IS 'FINAL BILL FLAG' , 
	OPVISITNUMBER IS 'OUT-PAT VISIT #' , 
	PENDINGPURGE IS 'PENDING PURGE' , 
	UNBILLEDBALANCE IS 'UNBILL CHGS BAL' , 
	MEDICALSERVICECODE IS 'MED SVC CODE' , 
	LOCKINDICATOR IS 'RECORD ID' , 
	LOCKERPBARID IS 'USER NAME' , 
	LOCKDATE IS 'TRANSACTION DATE' , 
	LOCKTIME IS 'TRANSACTION TIME' , 
	SHORTREGTYPE IS 'SHORT REGISTRATION TYPE' ,
	NEWBORNREGTYPE IS 'NEWBORN REGISTRATION TYPE' ,
	OPERATINGDRID IS 'OPERATING DR #' , 
	ATTENDINGDRID IS 'DOCTOR NUMBER' , 
	ADMITTINGDRID IS 'ADMITING DOCTOR #' , 
	REFERINGDRID IS 'REFERRING DOCTOR #' , 
	OTHERDRID IS 'OTHER DOCTOR #' , 
	CONSULTINGDR1ID IS 'CONS DR #' , 
	CONSULTINGDR2ID IS 'CONS DR #' , 
	CONSULTINGDR3ID IS 'CONS DR #' , 
	CONSULTINGDR4ID IS 'CONS DR #' , 
	CONSULTINGDR5ID IS 'CONS DR #' , 
	NURSINGSTATION IS 'NS' , 
	ISOLATIONCODE IS 'ISOLATION CODE' , 
	PENDINGDISCHARGE IS 'DISCHG PEND FLG' , 
	DISCHARGECODE IS 'DISCHARGE CODE' , 
	VALUABLESARETAKEN IS 'VALUABLES ARE TAKEN' , 
	ABSTRACTEXISTS IS 'ABSTRACT EXISTS-Y/N' , 
	CLERGYVISIT IS 'CLERGY VISIT' , 
	CHIEFCOMPLAINT IS 'CURR. DIAGNOSIS' , 
	ACCOMODATIONDESC IS 'DESCRIPTION' , 
	RELIGIONID IS 'RELIGION' , 
	PLACEOFWORSHIP IS 'Parish Code' , 
	DOB IS 'PATIENT D.O.B.' , 
	GENDERID IS 'SEX CODE' , 
	OPTOUT IS 'NPP FLAG' , 
	ADMITSOURCECODE IS 'PATIENT/ADM SOURCE CODE' , 
	ADMITCATEGORY IS 'ADMIT CATEGORY',
	BIRTHTIMEENTERED IS 'BirthTime Entered',
	CONFIDENTIAL IS 'CON CDE' , 
	LASTMAINTENANCEDATE IS 'LAST MAINT DATE' , 
	LASTMAINTENANCELOGNUMBER IS 'LAST MAINT LOG #' , 
	UPDATELOGNUMBER IS 'LAST UPDATE LOG #' , 
	LOCKEDWORKSTATION IS 'TRANSACTION TIME' , 
	LFKEY IS 'RECORD KEY' ) ; 
  
LABEL ON COLUMN &LIBRARY/ACCOUNTPROXIES 
( FACILITYID TEXT IS 'HOSPITAL NUMBER' , 
	MEDICALRECORDNUMBER TEXT IS 'MEDICAL RECORD NUMBER' , 
	ACCOUNTNUMBER TEXT IS 'PATIENT ACCOUNT NUMBER' , 
	SERVICECODE TEXT IS 'MEDICAL SERVICE CODE' , 
	CLINICCODE TEXT IS 'CLINIC REGISTERED -  1' , 
	CLINICDESCRIPTION TEXT IS 'CLINIC DESCRIPTION' , 
	FINANCIALCODE TEXT IS 'FINANCIAL CLASS CODE' , 
	FIRSTNAME TEXT IS 'PATIENT FIRST NAME' , 
	LASTNAME TEXT IS 'PATIENT LAST NAME' , 
	MIDDLEINITIAL TEXT IS 'PATIENT MIDDLE INITIAL' , 
	PATIENTTYPE TEXT IS 'PATIENT TYPE' , 
	OPSTATUSCODE TEXT IS 'OUTPATIENT STATUS CODE' , 
	IPSTATUSCODE TEXT IS 'INPATIENT STATUS CODE' , 
	FINALBILLINGFLAG TEXT IS 'FINAL BILLING FLAG -Y-YES' , 
	OPVISITNUMBER TEXT IS 'O/P VISIT #' , 
	PENDINGPURGE TEXT IS 'PENDING PURGE' , 
	UNBILLEDBALANCE TEXT IS 'BALANCE OF UNBILLED CHARGES' , 
	MEDICALSERVICECODE TEXT IS 'MEDICAL SERVICE CODE' , 
	LOCKINDICATOR TEXT IS 'RECORD ID' , 
	LOCKERPBARID TEXT IS 'USER NAME' , 
	LOCKDATE TEXT IS 'TRANSACTION DATE' , 
	LOCKTIME TEXT IS 'TRANSACTION TIME' , 
	SHORTREGTYPE TEXT IS 'SHORT REGISTRATION TYPE' ,
	NEWBORNREGTYPE TEXT IS 'NEWBORN REGISTRATION TYPE' ,
	OPERATINGDRID TEXT IS 'OPERATING DOCTOR NUMBER' , 
	ATTENDINGDRID TEXT IS 'ATTENDING DOCTOR NUMBER' , 
	ADMITTINGDRID TEXT IS 'ADMITING DOCTOR #' , 
	REFERINGDRID TEXT IS 'REFERRING DOCTOR #' , 
	OTHERDRID TEXT IS 'OTHER DOCTOR #' , 
	CONSULTINGDR1ID TEXT IS 'CONSULTING DOCTOR NUMBER' , 
	CONSULTINGDR2ID TEXT IS 'CONSULTING DOCTOR NUMBER' , 
	CONSULTINGDR3ID TEXT IS 'CONSULTING DOCTOR NUMBER' , 
	CONSULTINGDR4ID TEXT IS 'CONSULTING DOCTOR NUMBER' , 
	CONSULTINGDR5ID TEXT IS 'CONSULTING DOCTOR NUMBER' , 
	NURSINGSTATION TEXT IS 'NURSING STATION' , 
	ROOM TEXT IS 'ROOM NUMBER' , 
	BED TEXT IS 'BED NUMBER' , 
	ISOLATIONCODE TEXT IS 'ISOLATION CODE' , 
	PENDINGDISCHARGE TEXT IS 'DISCHARGE PENDING UPDATE FLA' , 
	DISCHARGECODE TEXT IS 'DISCHARGE CODE' , 
	VALUABLESARETAKEN TEXT IS 'VALUABLES ARE TAKEN' , 
	ABSTRACTEXISTS TEXT IS 'ABSTRACT EXISTS-Y/N' , 
	CLERGYVISIT TEXT IS 'CLERGY VISIT' , 
	CHIEFCOMPLAINT TEXT IS 'DIAGNOSIS' , 
	ACCOMODATIONCODE TEXT IS 'ACCOMODATION CODE' , 
	ACCOMODATIONDESC TEXT IS 'DESCRIPTION' , 
	BLOODLESS TEXT IS 'BLOODLESS' , 
	RELIGIONID TEXT IS 'RELIGION CODE' , 
	PLACEOFWORSHIP TEXT IS 'Parish Code' , 
	DOB TEXT IS 'PATIENT D.O.B.' , 
	GENDERID TEXT IS 'SEX CODE' , 
	OPTOUT TEXT IS 'NPP HIPPA FLAG' , 
	ADMITSOURCECODE TEXT IS 'PATIENT/ADMIT. SOURCE CODE' , 
	ADMITCATEGORY TEXT IS 'ADMITTING CATEGORY',
	BIRTHTIMEENTERED TEXT IS 'BirthTime Entered',
	CONFIDENTIAL TEXT IS 'CONFIDENTIAL FLAG' , 
	PREDISCHARGESTATUS TEXT IS 'RESERVED FIELD  2 POSITION' , 
	LASTMAINTENANCEDATE TEXT IS 'DATE OF LAST MAINTENANCE' , 
	LASTMAINTENANCELOGNUMBER TEXT IS 'LAST MAINTENANCE LOG NUMBER' , 
	UPDATELOGNUMBER TEXT IS 'UPDATE LOG NUMBER' , 
	LOCKEDWORKSTATION TEXT IS 'TRANSACTION TIME' , 
	LFKEY TEXT IS 'RECORD KEY' ) ;

                                         
                                                                                                            
