--  Generate SQL 
--  Version:                   	V5R3M0 040528 
--  Generated on:              	02/27/07 07:43:03 
--  Relational Database:       	DVLG 
--  Standards Option:          	DB2 UDB iSeries 

SET PATH *LIBL ; 

CREATE PROCEDURE PACCESS/ISACCOUNTLOCKED ( 
	IN P_FACILITY_ID INTEGER , 
	IN P_ACCOUNT_NUMBER VARCHAR(9) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC PACCESS/ISACCLOCK 
	NOT DETERMINISTIC 
	READS SQL DATA 
	CALLED ON NULL INPUT 

	P1 : BEGIN 
		 
		DECLARE CURSOR1 CURSOR FOR 
	  
		SELECT	COUNT ( * ) 
		FROM	NQHRLFP 
		WHERE	LFHSP#	= P_FACILITY_ID 
		AND	LFKEY	= P_ACCOUNT_NUMBER ; 	  

		OPEN CURSOR1 ; 		 

		END P1  ;