SET PATH *LIBL ;

CREATE PROCEDURE  SELECTGUARANTORFORACCOUNT (
        IN P_FACILITY_ID INTEGER ,
        IN P_ACCOUNT_NUMBER INTEGER )
        DYNAMIC RESULT SETS 10
        LANGUAGE SQL
        SPECIFIC  SELGUARACC
        NOT DETERMINISTIC
        READS SQL DATA
        CALLED ON NULL INPUT

        SET OPTION DBGVIEW =*SOURCE

        P1 : BEGIN

        DECLARE CURSOR1 CURSOR FOR

			 SELECT 
			 0									AS PERSONID,
			 0									AS SEXID,
             GUAR.MGGSEX						AS SEXCODE,             
             TRIM(GENDER.QTSEXD)				AS SEXDESCRIPTION,
             GUAR.MGGSSN						AS SSN,
			 TRIM(SUBSTRING(GUAR.MGDRL#,1,15))	AS DRIVERSLICENSENO,
			 SUBSTRING(GUAR.MGDRL#,16,2)		AS DRIVERSLICENSESTATE,
             TRIM(GUAR.MGEMAL)					AS EMAILADDRESS,
             GUAR.MGGLNM						AS LASTNAME,
             GUAR.MGGFNM						AS FIRSTNAME,
             GUAR.MGGMI							AS MIDDLEINITIAL,
             ''									AS TITLE,             
             ''									AS RELATIONSHIPTOGUARANTOR,
             0									AS RELATIONSHIPID,                                   
             PAT.LPRRCD							AS RELATIONSHIPCODE,
             TRIM(REL.QTRED)					AS RELATIONSHIPDESCRIPTION
        	
        	FROM	HPADMGP GUAR			
        	LEFT OUTER JOIN HPADQTSX GENDER		ON GUAR.MGGSEX = GENDER.QTKEY		AND GENDER.QTID02 = 'SX'	AND GENDER.QTHSP# = 999
        	LEFT OUTER JOIN HPADLPP PAT			ON GUAR.MGGAR# = PAT.LPGAR#			AND GUAR.MGHSP# = PAT.LPHSP#
        	LEFT OUTER JOIN HPADQTRE REL		ON PAT.LPRRCD = REL.QTKEY			AND REL.QTID02 = 'RE'		AND REL.QTHSP# = 999			
        	
			WHERE	GUAR.MGHSP# = P_FACILITY_ID AND GUAR.MGGAR# = P_ACCOUNT_NUMBER;
	
	OPEN CURSOR1 ;
	
	END P1 ;

			