--  Generate SQL 
--  Version:                   	V7R3M0 160422 
--  Generated on:              	04/21/20 06:26:16 
--  Relational Database:       	DVLA 
--  Standards Option:          	Db2 for i 
SET PATH *LIBL ; 
  
CREATE PROCEDURE SELECTPHYSICIANWITH ( 
	IN P_FACILITYID INTEGER , 
	IN P_HSP NUMERIC(5, 0) , 
	IN P_PHYSICIANNUMBER NUMERIC(5, 0) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SELPHYWI 
	NOT DETERMINISTIC 
	READS SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DBGVIEW = *SOURCE , 
	CLOSQLCSR = *ENDACTGRP , 
	DECRESULT = (31, 31, 00) , 
	DLYPRP = *NO , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	RDBCNNMTH = *RUW , 
	SRTSEQ = *HEX   
	P1 : BEGIN DECLARE CURSOR1 CURSOR FOR 
SELECT MRDNM AS PHYSICIANNAME , 
MRDR# AS PHYSICIANNUMBER , 
MRLNM AS PHYSICIANLASTNAME , 
MRFNM AS PHYSICIANFIRSTNAME , 
MRMI AS PHYSICIANMIDDLEINITIAL , 
MRHSP# AS FACILITYID , MRUPI# AS UPIN , 
MRINA AS ACTIVEFLAG , MRMDAP AS ADMITPRIVILEGE , 
MRMPDT AS ADMITPRIVSUSPENDDATE , 
MRSPCD AS PHYSICIANSPECIALITYCODE , 
S . QTDSPD AS PHYSICIANSPECIALITYDESC , 
MRSLIC AS STATELICENSENUMBER , E . EXDATE AS EXCLUDEDATE , 
MRSTAT AS STATUSCODE , ST . QTDSTD AS STATUSDESCRIPTION 
FROM  HPADMRP LEFT OUTER JOIN  HPADQTDS S	ON S . QTKEY = MRSPCD	 
AND S . QTHSP# = P_FACILITYID LEFT OUTER JOIN  NDEXMDP E	 
ON EXHSP# = MRHSP#	 
AND EXDR# = MRDR# LEFT OUTER JOIN  HPADQTDC ST	 
ON ST . QTKEY = MRSTAT	 
AND ST . QTHSP# = P_FACILITYID 
WHERE MRHSP# = P_HSP			 
AND MRDR# = P_PHYSICIANNUMBER ;				 
OPEN CURSOR1 ; END P1  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE SELPHYWI 
TO RMTGRPPRF WITH GRANT OPTION ; 
  
