 --  Generate SQL 
--  Version:                   	V5R4M0 060210 
--  Generated on:              	01/24/08 02:22:22 
--  Relational Database:       	DVLA 
--  Standards Option:          	DB2 UDB iSeries 
  
SET PATH *LIBL ; 
  
CREATE PROCEDURE SELECTFACILITYFLAGWITH ( 
	IN @P_HSP INTEGER , 
	IN @P_FACILITYFLAGCODE VARCHAR(10) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SLFACFLGWT 
	NOT DETERMINISTIC 
	READS SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DBGVIEW = *SOURCE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
  
		DECLARE CURSOR1 CURSOR FOR 
		( SELECT 0 AS FACILITYFLAGID , 
		TRIM ( F . QTKEY ) AS FACILITYFLAGCODE , 
		TRIM ( F . QTFLDS ) AS DESCRIPTION , 
		F . QTHSP# AS FACILITYID	 
		FROM HPADQTFL F	 
		WHERE 
		F . QTHSP# = @P_HSP 
		AND TRIM ( F . QTKEY ) = TRIM ( @P_FACILITYFLAGCODE )	) ; 
		 
	OPEN CURSOR1 ; 
  
END P1  ;
