--  Generate SQL 
--  Version:                   	V7R3M0 160422 
--  Generated on:              	04/21/20 06:24:21 
--  Relational Database:       	DVLA 
--  Standards Option:          	Db2 for i 
SET PATH *LIBL ; 
  
CREATE PROCEDURE SELECTPHYSICIANSPECIALITESFOR ( 
	IN P_FACILITYID INTEGER , 
	IN P_HSP NUMERIC(5, 0) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SLPHYSPFOR 
	NOT DETERMINISTIC 
	READS SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DBGVIEW = *SOURCE , 
	CLOSQLCSR = *ENDACTGRP , 
	DECRESULT = (31, 31, 00) , 
	DLYPRP = *NO , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	RDBCNNMTH = *RUW , 
	SRTSEQ = *HEX   
	P1 : BEGIN 
	DECLARE CURSOR1 CURSOR FOR 
	SELECT OID , CODE , DESCRIPTION 
	FROM ( 
	SELECT DISTINCT 0 AS OID , 
	TRIM ( S . QTKEY ) AS CODE , 
	TRIM ( S . QTDSPD ) AS DESCRIPTION		 
	FROM  HPADQTDS S 
	JOIN  HPADMRP P ON 
	P . MRSPCD = S . QTKEY 
	AND P . MRHSP# = S . QTHSP#	 
  
	WHERE MRHSP# = P_HSP	 
	AND S . QTHSP# = P_FACILITYID	 
	UNION ALL		 
	SELECT 0 AS OID , '' AS CODE , 
	'' AS DESCRIPTION		 
	FROM SYSIBM . SYSDUMMY1		) AS		 
	V ( OID , CODE , DESCRIPTION )		 
	ORDER BY CODE ;		OPEN CURSOR1 ; END P1  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE SLPHYSPFOR 
TO RMTGRPPRF WITH GRANT OPTION ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE SLPHYSPFOR 
TO TURNOVER WITH GRANT OPTION ; 
  
