--  Generate SQL 
--  Version:                   	V7R3M0 160422 
--  Generated on:              	04/21/20 06:16:17 
--  Relational Database:       	DVLA 
--  Standards Option:          	Db2 for i 
SET PATH *LIBL ; 
  
CREATE PROCEDURE SELECTADMITSOURCEWITH ( 
	IN P_FACILITYID INTEGER , 
	IN P_CODE VARCHAR(10) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SLADSRWI 
	NOT DETERMINISTIC 
	READS SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DBGVIEW = *SOURCE , 
	CLOSQLCSR = *ENDACTGRP , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DLYPRP = *NO , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	RDBCNNMTH = *RUW , 
	SRTSEQ = *HEX   
	P1 : BEGIN DECLARE CURSOR1 CURSOR FOR 
SELECT 0 AS OID , TRIM ( QTKEY ) AS CODE ,	 
TRIM ( QTPSD ) AS DESCRIPTION	FROM  HPADQTPS	 
WHERE QTHSP# = P_FACILITYID	 
AND QTKEY = P_CODE	 
ORDER BY QTKEY ; 
OPEN CURSOR1 ; END P1  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE SLADSRWI 
TO RMTGRPPRF WITH GRANT OPTION ; 
  
