/**********************************************************************/
/*                                                                    */
/* iSeries400    SELDTLACCI  - STORED PROCEDURE FOR PX                */
/*                                                                    */
/*    ************************************************************    */
/*    * Perot Systems, Copyright 2003, All rights reserved(U.S.) *    */
/*    *                                                          *    */
/*    * This unpublished material is proprietary to Perot Sys.   *    */
/*    * The methods and techniques described herein are          *    */
/*    * considered trade secrets and/or confidential.            *    */
/*    * Reproduction or distribution, in whole or in part, is    *    */
/*    * forbidden except by express written permission of        *    */
/*    * Perot Systems, Inc.                                      *    */
/*    ************************************************************    */
/*                                                                    */
/**********************************************************************/
/*  Date        Programmer          Modification Description          */
/**********************************************************************/
/* 04/26/2006   Melissa Bouse       NEW STORED PROCEDURE              */
/* 07/06/2006                       Modified STORED PROCEDURE         */
/* 07/18/2006                       MODIFIED STORED PROCEDURE         */
/* 11/09/2006   Tatiana Gulakova    Modified proc for January 07      */
/* 11/16/2006   Tatiana Gulakova    Modified proc for January 07      */
/* 11/28/2006   Deepa Raghavaraju   Modified proc for January 07      */
/* 06/05/2007   Kevin Sedota        Added new cursor for SR39485      */
/* 07/23/2007   Sophie Zhang        Added two columns passport & coun */
/*								      try to 1st cursor for SR 39493  */
/* 07/18/2007   Kevin Sedota        Add new fields to INS cursors     */
/*                                    for SR 39480                    */
/* 09/18/2007   Gauthreaux		    Add doco for table names & locs   */
/* 10/19/2007   Gauthreaux		    Add InsuranceCompanyName to       */
/*                                    result set for Insurances       */
/*                                    ( Cursors 2 and 9 )             */
/* 02/21/2008   KJS                 Query performance improvement     */
/* 11/18/2008   Deepa Raghavaraju   Add new fields for MCR rem PartA  */
/*                                   PartB Deductibles for SR49735    */
/**********************************************************************/
/* SP Definition - PACCESS.SELECTALLDETAILACCOUNTINFO                 */
/*    Params     - P_HSP	- an HSP Code							  */
/*    Params     - P_MRN    - a Medical record number                 */
/*    Params     - P_ACCOUNTNUMBER	- an account number               */
/**********************************************************************/

SET PATH *LIBL ;

CREATE PROCEDURE SELECTALLDETAILACCOUNTINFO (
        IN P_HSP INTEGER ,
        IN P_MRN INTEGER ,
        IN P_ACCOUNTNUMBER INTEGER )
        DYNAMIC RESULT SETS 10
        LANGUAGE SQL
        SPECIFIC SELDTLACCI
        NOT DETERMINISTIC
        MODIFIES SQL DATA
        CALLED ON NULL INPUT
        SET OPTION DBGVIEW =*SOURCE

        P1 : BEGIN

        DECLARE CURSOR1 CURSOR FOR

        SELECT
        A . LPHSP# AS HSPNUMBER ,
        A . LPACCT AS ACCOUNTNUMBER ,
        A . LPALOC AS ACCIDENTLOCATION ,
        A . LPATIM AS ACCIDENTTIME ,
        A . LPACTP AS ACCIDENTTYPE ,
        A . LPDIAG AS DIAGNOSIS ,
        A . LPACST AS AUTOACCIDENTSTATE ,
        A . LPACCN AS ACCIDENTCOUNTRYCODE ,
        A . LPLAT AS TIMEOFADMISSION ,
        A . LPOC01 AS OCCURANCECODE1 ,
        A . LPOC02 AS OCCURANCECODE2 ,
        A . LPOC03 AS OCCURANCECODE3 ,
        A . LPOC04 AS OCCURANCECODE4 ,
        A . LPOC05 AS OCCURANCECODE5 ,
        A . LPOC06 AS OCCURANCECODE6 ,
        A . LPOC07 AS OCCURANCECODE7 ,
        A . LPOC08 AS OCCURANCECODE8 ,
        A . LPOA01 AS OCCURANCEDATE1 ,
        A . LPOA02 AS OCCURANCEDATE2 ,
        A . LPOA03 AS OCCURANCEDATE3 ,
        A . LPOA04 AS OCCURANCEDATE4 ,
        A . LPOA05 AS OCCURANCEDATE5 ,
        A . LPOA06 AS OCCURANCEDATE6 ,
        A . LPOA07 AS OCCURANCEDATE7 ,
        A . LPOA08 AS OCCURANCEDATE8 ,
        A . LPCI01 AS CONDITIONCODE1 ,
        A . LPCI02 AS CONDITIONCODE2 ,
        A . LPCI03 AS CONDITIONCODE3 ,
        A . LPCI04 AS CONDITIONCODE4 ,
        A . LPCI05 AS CONDITIONCODE5 ,
        A . LPCI06 AS CONDITIONCODE6 ,
        A . LPCI07 AS CONDITIONCODE7 ,
        A . LPCLVS AS CLERGYVISIT ,
        A . LPIPA AS IPACODE ,
        A . LPIPAC AS IPACLINICCODE ,
        A . LPLMEN AS LASTMENSTRATION ,
        A . LPWRNF AS FACILITYFLAG ,
        A . LPPSTO AS OPSTATUSCODE ,
        A . LPPSTI AS IPSTATUSCODE ,
        A . LPFBIL AS FINALBILLINGFLAG ,
        A . LPVIS# AS OPVISITNUMBER ,
        A . LPPOLN AS PENDINGPURGE ,
        A . LPUBAL AS UNBILLEDBALANCE ,
        A . LPMSV AS MEDICALSERVICECODE ,
        A . LPADT1 AS ADMITMONTH ,
        A . LPADT2 AS ADMITDAY ,
        A . LPADT3 AS ADMITYEAR ,
         --a.LPLAT    AS TIMEOFA
        A . LPLDD AS DISCHARGEDATE ,
        A . LPFC AS FINANCIALCLASSCODE ,
        A . LPPTYP AS PATIENTTYPE ,
        A . LPDCOD AS DISCHARGEDISPOSITIONCODE ,
        A . LPSPNC AS FIRSTSPANCODE ,
        A . LPSPFR AS FIRSTSPANFROMDATE ,
        A . LPSPTO AS FIRSTSPANTODATE ,
        A . LPINSN AS FIRSTSPANFACILITY ,
        A . LPSPN2 AS SECONDSPANCODE ,
        A . LPAPFR AS SECONDSPANFROMDATE ,
        A . LPAPTO AS SECONDSPANTODATE ,
        A . LPRSRC AS REFERRALSOURCE ,
        A . LPLMD AS LASTMAINTENANCEDATE ,
        A . LPLML AS LASTMAINTENANCELOGNUMBER ,
        A . LPLUL# AS UPDATELOGNUMBER ,
        A . LPCL01 AS CLINICCODE1 ,
        A . LPCL02 AS CLINICCODE2 ,
        A . LPCL03 AS CLINICCODE3 ,
        A . LPCL04 AS CLINICCODE4 ,
        A . LPCL05 AS CLINICCODE5 ,
        A . LPPUBL AS REREGISTER ,
        A . LPSCHD AS SCHEDULECODE ,
        A . LPMSV AS MEDICALSERVICECODE ,
         --S . QTKEY AS MEDICALSERVICECODE ,
         --S . QTMSVD AS MEDICALSERVICEDESC ,
        SUP . RVPRGI AS ISPREGNANT ,
        FUS . PMTCH8 AS TOTALCHARGES ,
        MPI . RWCNFG AS CONFIDENTIALFLAG ,
        D . MDNPPV AS NPPVERSION ,
        D . MDNPPF AS OPTOUTFLAGS ,
	D . MDNPPS AS NPPSIGNATURESTATUS ,
	D . MDNPPD AS NPPDATESIGNED ,
        D . MDSMOK AS SMOKER ,
        D . MDBLDL AS BLOODLESS ,
        D . MDRORG AS RESISTANTORGANISM ,
        D . MDFDOB AS FATHERDOB ,
        D . MDMDOB AS MOTHERDOB ,
        D . MDPCNY as DNR,
        D . MDPPT# as PASSPORTNUMBER,
        D . MDICUN as PASSPORTCOUNTRY,
        C . LACMT1 AS COMMENTLINE1 ,
        C . LACMT2 AS COMMENTLINE2 ,
        C . LATECR AS TENETCARE ,
        H . LFRCID AS LOCKINDICATOR ,
        H . LFUSER AS LOCKERPBARID ,
        H . LFTDAT AS LOCKDATE ,
        H . LFTTIM AS LOCKTIME ,
        EMER . EDRACD AS READMITCODE ,
        EMER . EDFRCD AS REFERRALFACILITY ,
        EMER . EDRTYP AS REFERRALTYPE ,
        EMER . EDAVTM AS ARRIVALTIME ,
        EMER . EDARVC AS MODEOFARRIVAL
        
        FROM HPADLPP A					-- Patient Physical File (HPDATA1)
        JOIN NOHLHSPP FAC				-- Hospital Definition Master (NMDATA1)
			ON ( FAC . HHHSPN = P_HSP )
        JOIN HPADMDP D					-- Patient Demographics (HPDATA1)
			ON ( D . MDHSP# = P_HSP
			AND D . MDMRC# = P_MRN )
        LEFT OUTER JOIN HPADLAP9 C		-- Patient comments/ states aux file (HPDATA1)
			ON ( C . LAHSP# = P_HSP
			AND C . LAACCT = P_ACCOUNTNUMBER )
        LEFT OUTER JOIN PM0001P FUS		-- FUS Patient Master File (PADATA)
			ON ( FUS . PMHSPC = FAC . HHHSPC
			AND FUS . PMPT#9 = P_ACCOUNTNUMBER )
        LEFT OUTER JOIN HXMRRV2P SUP	-- Supplemental Abstracts file (HPDATA1)
			ON ( SUP . RVHSP# = P_HSP
			AND SUP . RVPT#9 = P_ACCOUNTNUMBER )
        LEFT OUTER JOIN HXMRRWP MPI		-- Master Patient Index (HPDATA1)
          ON ( MPI . RWHSP# = P_HSP
			AND MPI . RWACCT = P_ACCOUNTNUMBER )
        LEFT JOIN NQHRLFP H				-- HRAM locks (XADATA)
			ON ( LPAD ( TRIM ( CHAR ( P_ACCOUNTNUMBER ) ) , 9 , '0' ) = SUBSTR
			( H . LFKEY , 1 , 9 ) AND H . LFHSP# = P_HSP)
        LEFT OUTER JOIN NDED01P EMER	-- Emergency Dept. log file (NMDATA1)
			ON ( EMER . EDHSP# = P_HSP
			AND EMER . EDACCT = P_ACCOUNTNUMBER )
        WHERE A . LPHSP# = P_HSP
        AND A . LPACCT = P_ACCOUNTNUMBER ;

         --Insurances

        DECLARE CURSOR2 CURSOR FOR
        SELECT
        HSPNUMBER ,
        ACCOUNTNUMBER ,
        INSUREDLASTNAME ,
        INSUREDFIRSTNAME ,
        INSUREDMIDDLEINITIAL ,
        INSUREDSEX ,
        INSUREDRELATIONSHIP ,
        INSUREDIDENTIFIER ,
        INSUREDCOUNTRYCODE ,
        INSUREDBIRTHDATE ,
        INSURANCECERTIFICATIONNUM ,
        INSURANCEGROUPNUMBER ,
        GROUPNUMBER ,
        POLICYNUMBER ,
        EVCNUMBER ,
        AUTHORIZATIONNUMBER ,
        AUTHORIZEDDAYS ,
        ISSUEDATE ,
        INSUREDADDRESS ,
        INSUREDCITY ,
        INSUREDSTATE ,
        INSUREDZIP ,
        INSUREDZIPEXT ,
        INSUREDAREACODE1 ,
        INSUREDPHONENUMBER1 ,
        INSUREDAREACODE2 ,
        INSUREDPHONENUMBER2 ,
        INSUREDCELLPHONE ,
        INSURANCECOMPANYNUMBER ,
        SIGNEDOVERMEDICAREHICNUMBER ,
        PRIORITYCODE ,
        BILLINGADDRESS1 ,
        BILLINGCITYSTATECOUNTRY ,
        BILLINGZIPZIPEXTPHONE ,
        DEDUCTIBLE ,
        COPAY ,
        NOLIABILITY ,
        ELIGIBILITY ,
        CONDITIONOFSERVICE ,
        PRIMARYEMPSTATUS ,
        PRIMARYEMPCODE ,
        PRIMARYEMPNAME ,
        PRIMARYEMPADDRESS ,
        PRIMARYLOC ,  --city, state
        PRIMARYEMPZIP ,
        PRIMARYEMPZIPEXT ,
        PRIMARYPHONE ,
        SECONDARYEMPSTATUS ,
        SECONDARYEMPCODE ,
        SECONDARYEMPNAME ,
        SECONDARYEMPADDRESS ,
        SECONDARYLOC ,  --city,
        SECONDARYEMPZIP ,
        SECONDARYEMPZIPEXT ,
        SECONDARYPHONE ,
        EFFECTIVEON ,
        APPROVEDON ,
        -- NOPATIENTLIABILITYFLAG ,
        AUTHORIZATIONPHONE ,
        AUTHORIZATIONCOMPANY ,
        AUTHORIZATIONPMTEXT ,
        AUTHORIZATIONFLAG ,
        VERIFICATIONDATE ,
        VERIFICATIONFLAG ,
        VERIFIEDBY ,
        ATTORNEYNAME ,
        ATTORNEYSTREET ,
        ATTORNEYCITY ,
        ATTORNEYSTATE ,
        ATTORNEYZIP5 ,
        ATTORNEYZIP4 ,
        ATTORNEYCOUNTRYCODE ,
        ATTORNEYPHONE ,
        AGENTNAME ,
        AGENTPHONE ,
        AGENTSTREET ,
        AGENTCITY ,
        AGENTSTATE ,
        AGENTZIP5 ,
        AGENTZIP4 ,
        AGENTCOUNTRYCODE ,
        BILLINGCAREOFNAME ,
        BILLINGNAME ,
        TRACKINGNUMBER ,
        ADJUSTERSNAME ,
        EMPLOYEESSUPERVISOR,
        AUTHCOMPANYREPFIRSTNAME ,
		AUTHCOMPANYREPLASTNAME ,
		SERVICESAUTHORIZED ,
		EFFECTIVEDATEOFAUTH , 
		EXPIRATIONDATEOFAUTH ,
		AUTHORIZATIONSTATUS ,
		AUTHORIZATIONREMARKS,
		INSURANCECOMPANYNAME
        FROM INSURANCES I
        WHERE I . HSPNUMBER = P_HSP
        AND I . ACCOUNTNUMBER = P_ACCOUNTNUMBER
        AND ( PRIORITYCODE = '1' OR PRIORITYCODE = '2' )
        ORDER BY PRIORITYCODE ;

		DECLARE CURSOR2a CURSOR FOR
		SELECT 
		I.HBPTY as PRIORITYCODE,
		
		MCD.MCDCPTY as MCD_PRIORITY_CODE,
		MCD.MCDCELDT as MCD_ELIGIBILITYDATE,
		MCD.MCDCPTMC as  MCD_PATIENT_HAS_MEDICARE,
		MCD.MCDCPTOI as MCD_PATIENT_HAS_OTHER_INS,
		MCD.MCDCCPAY as MCD_COPAY_AMOUNT,
		MCD.MCDCEVCN as MCD_EVC_NUMBER,
		MCD.MCDCINFF as MCD_INFO_RECEIVED_FROM,
		MCD.MCDCREMK as MCD_REMARKS,
		
		WKC.WKCCPTY as WKC_PRIORITY_CODE,
		WKC.WKCCNMNT as WKC_NAME_OF_NETWORK,
		WKC.WKCCCLMN as WKC_CLAIM_NUMBER_FOR_INCIDENT,
		WKC.WKCCADVR as WKC_CLAIM_ADDRESS_VERIFIED,
		WKC.WKCCINPH as WKC_INSURANCE_PHONE_NUMBER,
		WKC.WKCCEMPM as WKC_EMP_PREMIUM_PAID_TODATE,
		WKC.WKCCINFF as WKC_INFO_RECEIVED_FROM,
		WKC.WKCCREMK as WKC_REMARKS,
		
		GOV.GOVCPTY		AS GOV_PRIORITY_CODE,
		GOV.GOVCINFF	AS GOV_INFO_RECEIVED_FROM,
		GOV.GOVCELPH	AS GOV_ELIGIBILITY_PHONE_NUM,
		GOV.GOVCINRP	AS GOV_INS_COMPANY_REP_NAME,
		GOV.GOVCTYCV	AS GOV_TYPE_OF_COVERAGE,
		GOV.GOVCEFDI	AS GOV_EFFECTIVE_DATEOF_INSURED,
		GOV.GOVCTMDI	AS GOV_TERM_DATE_FOR_INSURED,
		GOV.GOVCDEDA	AS GOV_DEDUCTABLE_AMOUNT,
		GOV.GOVCDEMT	AS GOV_ISDEDUCTABLE_MET,
		GOV.GOVCDEAM	AS GOV_DEDUCTABLE_AMOUNT_MET,
		GOV.GOVCCOIN	AS GOV_COINSURANCE,
		GOV.GOVCOTPK	AS GOV_OUT_OF_POCKET,
		GOV.GOVCOTPM	AS GOV_IS_OUTOFPOCKET_MET,
		GOV.GOVCOTPA	AS GOV_OUTOFPOCKET_AMOUNT_MET,
		GOV.GOVCPROT	AS GOV_PERCENT_OUTOFPOCKET,
		GOV.GOVCCPAY	AS GOV_COPAY_AMOUNT,
		GOV.GOVCREMK	AS GOV_REMARKS,
		
		MCR.MCRCPTY		AS MCR_PRIORITY_CODE,
		MCR.MCRCPACV	AS MCR_PARTA_COVERAGE,
		MCR.MCRCPAED	AS MCR_PARTA_EFFECTIVE_DATE,
		MCR.MCRCPBCV	AS MCR_PARTB_COVERAGE,
		MCR.MCRCPBED	AS MCR_PARTB_EFFECTIVE_DATE,
		MCR.MCRCMHCV	AS MCR_PAT_HAS_MEDICARE_HMO_CVRG,
		MCR.MCRCMDSC	AS MCR_MEDICARE_IS_SECONDARY,
		MCR.MCRCDTLB	AS MCR_DATEOFLAST_BILL_ACTIVITY,
		MCR.MCRCRMHD	AS MCR_REM_HOSPITAL_DAYS,
		MCR.MCRCRCID	AS MCR_REM_COINSURANCE_DAYS,
		MCR.MCRCRLRD	AS MCR_REM_LIFETIME_RESERVE_DAYS,
		MCR.MCRCRSNF	AS MCR_REM_SNF_DAYS,
		MCR.MCRCRSNC	AS MCR_REM_SNF_COINS_DAYS,
		MCR.MCRCRPAD	AS MCR_REM_PART_A_DEDUCTIBLE,
		MCR.MCRCRPBD	AS MCR_REM_PART_B_DEDUCTIBLE,
		MCR.MCRCPTHS	AS MCR_PATIENT_IS_IN_HOSPICE,
		MCR.MCRCBNNV	AS MCR_BENEFICIARY_NAME_VERIFIED,
		MCR.MCRCINFF	AS MCR_INFO_RECEIVED_FROM,
		MCR.MCRCREMK	AS MCR_REMARKS,

		SLF.SLFCPTY		AS SELF_PRIORITY_CODE,
		SLF.SLFCPTMD	AS SELF_HAS_MEDICAID,
		SLF.SLFCINIF	AS SELF_INSURANCE_INFO_AVAILABLE,
		
		COM.COMCPTY		AS COM_PRIORITY_CODE,
		COM.COMCINFF	AS COM_INFO_RECEIVED_FROM,
		COM.COMCELPH	AS COM_ELIGIBILITY_PHONE_NUMBER,
		COM.COMCINRP	AS COM_INSURANCE_COMP_REP_NAME,
		COM.COMCEFDI	AS COM_EFFECTIVE_DATE_OF_INSURED,
		COM.COMCTMDI	AS COM_TERM_DATE_FOR_INSURED,
		COM.COMCSFPC	AS COM_ISSVC_FORPREEXISTING_COND,
		COM.COMCSACB	AS COM_ISSERVICEA_COVERED_BENEFIT,
		COM.COMCCAAV	AS COM_CLAIMSA_ADDRESS_VERIFIED,
		COM.COMCCOBF	AS COM_COORD_OF_BENEFITS,
		COM.COMCRCOB	AS COM_RULE_TO_DETERMINE_COB,
		COM.COMCTPPR	AS COM_TYPE_OF_PRODUCT,
		COM.COMCNPPO	AS COM_NAMEOFPPONETWORK_ORBROKER,
		COM.COMCHCPR	AS COM_HOSP_IS_CONTRACTED_PROV,
		COM.COMCACNM	AS COM_AUTO_CLAIM_NUMBER,
		COM.COMCMPCV	AS COM_AUTO_MEDPAY_COVERAGE,
		COM.COMCREMK	AS COM_REMARKS,

		CBC.CBCPTY	AS BC_PRIORITY_CODE,
		CBC.CBCCTID	AS BC_BENEFIT_CATEGORY_ID,
		CBC.CBCDEDA	AS BC_DEDUCTABLE_AMOUNT,
		CBC.CBCTMPR	AS BC_TIME_PERIOD,
		CBC.CBCDEMT	AS BC_DEDUCTABLE_MET,
		CBC.CBCDEAM	AS BC_DEDUCTABLE_METAMOUNT,
		CBC.CBCCOIN	AS BC_COINSURANCE,
		CBC.CBCOTPK	AS BC_OUT_OF_POCKET,
		CBC.CBCOTPM	AS BC_OUTOF_POCKET_MET,
		CBC.CBCOTPA	AS BC_OUTOF_POCKETMET_AMOUNT,
		CBC.CBCPROT	AS BC_PCT_AFTER_OUTOF_POCKET,
		CBC.CBCCPAY	AS BC_COPAY_AMOUNT,
		CBC.CBCWCPY	AS BC_WAIVE_COPAYIF_ADMITTED,
		CBC.CBCNMVS	AS BC_NUMBER_OFVISITS_PER_YEAR,
		CBC.CBCLFMB	AS BC_LIFETIME_MAX_BENEFIT,
		CBC.CBCLFRM	AS BC_REM_LIFETIME_VALUE,
		CBC.CBCLFVM	AS BC_REM_LIFETIME_VALUEMET,
		CBC.CBCMXBN	AS BC_MAXIMUM_BENEFIT_PERVISIT,
		CBC.CBCRMBN	AS BC_REM_BENEFIT_PERVISIT,
		CBC.CBCRMMT	AS BC_REM_BENEFIT_PERVISITMET

		from HPADHBP I
        left outer join NHADMCDCP MCD on (MCDCHSP# = P_HSP 
			and MCDCACCT = P_ACCOUNTNUMBER  and MCDCPTY = I.HBPTY)
		left outer join NHADWKCCP WKC on (WKCCHSP# = P_HSP 
			and WKCCACCT = P_ACCOUNTNUMBER  and WKCCPTY = I.HBPTY)
		left outer join NHADMCRCP MCR on (MCRCHSP# = P_HSP 
			and MCRCACCT = P_ACCOUNTNUMBER  and MCRCPTY = I.HBPTY)
		left outer join NHADGOVCP GOV on (GOVCHSP# = P_HSP 
			and GOVCACCT = P_ACCOUNTNUMBER  and GOVCPTY = I.HBPTY)
		left outer join NHADSLFCP SLF on (SLFCHSP# = P_HSP 
			and SLFCACCT = P_ACCOUNTNUMBER  and SLFCPTY = I.HBPTY)
		left outer join NHADCOMCP COM on (COMCHSP# = P_HSP 
			and COMCACCT = P_ACCOUNTNUMBER  and COMCPTY = I.HBPTY)
		left outer join NHADCBCP CBC on (CBCHSP# = P_HSP 
			and CBCACCT = P_ACCOUNTNUMBER  and CBCPTY = I.HBPTY)
		WHERE I . HBHSP# = P_HSP
        AND I . HBACCT = P_ACCOUNTNUMBER
        AND ( HBPTY = '1' OR HBPTY = '2' )
        ORDER BY HBPTY ;
		
        DECLARE CURSOR3 CURSOR FOR
        SELECT
        LACNM AS CONTACTNAME ,  --CHAR(25) CCSID 37 NOT NULL DEFAULT ''
        LACADR AS ADDRESS ,  --CHAR(25) CCSID 37 NOT NULL DEFAULT ''
        LACCIT AS CITY ,  --CHAR(15) CCSID 37 NOT NULL DEFAULT ''
        LACSTE AS STATE ,  --CHAR(2) CCSID 37 NOT NULL DEFAULT ''
        LACZPA AS ZIP ,  --CHAR(5) CCSID 37 NOT NULL DEFAULT ''
        LACZ4A AS ZIPEXT ,  --CHAR(4) CCSID 37 NOT NULL DEFAULT ''
        LACRCD AS RELATIONSHIPCODE ,  --CHAR(2) CCSID 37 NOT NULL DEFAULT ''
        LACACD AS AREACODE ,  --DECIMAL(3, 0) NOT NULL DEFAULT 0
        LACPH# AS PHONENUMBER  --DECIMAL(7, 0) NOT NULL DEFAULT 0
        FROM HPADLAP3 WHERE LAHSP# = P_HSP
        AND LAMRC# = P_MRN ORDER BY LACNM ;  --nearest relative contacts

        DECLARE CURSOR4 CURSOR FOR
        SELECT LARNM AS CONTACTNAME ,  --CHAR(25) CCSID 37 NOT NULL DEFAULT ''
        LARADR AS ADDRESS ,  --CHAR(25) CCSID 37 NOT NULL DEFAULT ''
        LARCIT AS CITY ,  --CHAR(15) CCSID 37 NOT NULL DEFAULT ''
        LARSTE AS STATE ,  --CHAR(2) CCSID 37 NOT NULL DEFAULT ''
        LARZPA AS ZIP ,  --CHAR(5) CCSID 37 NOT NULL DEFAULT ''
        LARZ4A AS ZIPEXT ,  --CHAR(4) CCSID 37 NOT NULL DEFAULT ''
        LANRCD AS RELATIONSHIPCODE ,  --CHAR(2) CCSID 37 NOT NULL DEFAULT ''
        LARACD AS AREACODE ,  --DECIMAL(3, 0) NOT NULL DEFAULT 0
        LARPH# AS PHONENUMBER  --DECIMAL(7, 0) NOT NULL DEFAULT 0
        FROM HPADLAP2
        WHERE LAHSP# = P_HSP
        AND LAMRC# = P_MRN ORDER BY LARNM ;  -- FinancialData

        DECLARE CURSOR5 CURSOR FOR
        SELECT
        FIN . PMDTBL AS BILLDROPPED ,
        FIN . PMLSCD AS LASTCHARGEDATE ,
        I . HBAMCL AS INSTOTALPAYMENTSCOLLECTED ,
        I . HBMNPY AS INSNUMBEROFMONTHLYPAYMENTS ,
        I . HBPDUE AS DAYOFMONTHPAYMENT ,
        I . HBNUM1 AS TOTALAMOUNTDUE ,  --insured
        I . HBNUM2 AS DISCPLANAMOUNT ,  -- uninsured
        I . HBNUM3 AS INSUREDTOTALMONTHLYPYMTDUE ,  -- insured
        I . HBEFPT AS UNINSTOTALMONTHLYPAYMENTSDUE ,
        I . HBUFPT AS UNINSTOTALPAYMENTSCOLLECTED ,
        I . HBUCPY AS UNINSNUMBEROFMONTHLYPAYMENTS ,
        I . HBUCBL AS UNINSUREDCONTRACTBALANCE ,
        I . HBCRSC AS RESOURCELISTPROVIDED
        FROM PM0001P FIN ,
        FF0015P F
        LEFT OUTER JOIN HPADHBP I ON
        ( I . HBHSP# = F . FFHSPN
        AND I . HBACCT = FIN .PMPT#9 )
        WHERE F . FFHSPN = P_HSP
        AND FIN . PMHSPC = F . FFHSPC
        AND FIN . PMPT#9 = P_ACCOUNTNUMBER
        AND I . HBSEQ# = 1 ;  -- only pull the financial INFO fr

        --MSP INFO

        DECLARE CURSOR6 CURSOR FOR
        SELECT 1 from sysibm/SYSDUMMY1;  --Guarantor Employer INFO

        DECLARE CURSOR7 CURSOR FOR
        SELECT
        LAGAR# AS GUARANTORNUMBER ,
        LAENM AS EMPLOYERSNAME ,
        LAEADR AS EMPLOYERADDRESS ,
        LAECTY AS EMPLOYERCITY ,
        LAEZIP AS EMPLOYERSZIPCODE ,
        LAEACD AS EMPLOYERAREACODE ,
        LAEPH# AS EMPLOYERPHONENUMBER ,
        LAGOCC AS GUARANTORSOCCUPATION ,
        LAHSP# AS HOSPITALNUMBER ,
        LADEL AS DELETECODE ,
        LAECIT AS EMPLOYECITY ,
        LAESTE AS GUARANTOREMPLOYERSTATE ,
        LAEZP4 AS GUARANTOREMPLOYERZIPEXT ,
        LAGESC AS GUARANTOREMPLOYMENTSTATUS ,
        LAGEID AS GUARANTOREMPLOYEEID ,
        LAGLOE AS GUARANTORLENGTHOFEMPLOY ,
        LAUN AS UNIONLOCALANDNUMBER ,
        LAGPSM AS GUARSAMEASINSURED ,
        LAGLR AS LENGTHRESIDENCE ,
        LAGLRO AS RENTOWN ,
        LAEZPA AS EMPLOYERZIP ,
        LAEZ4A AS EMPLOYERZIP4 ,
        LAECUN AS EMPLOYERCOUNTRY
        FROM HPADLAP1 GE ,
        HPADLPP A
        WHERE A . LPHSP# = P_HSP
        AND A . LPACCT = P_ACCOUNTNUMBER
        AND GE . LAHSP# = A . LPHSP#
        AND GE . LAGAR# = A . LPGAR# ;


	DECLARE CURSOR8 CURSOR FOR
	SELECT
		M . MSEPACCT AS COPIEDFROMACCOUNTNUMBER ,
		A . LPFC,
		B . LPIPA AS IPACODE ,
        B . LPIPAC AS IPACLINICCODE
	FROM	NHMSE01P M 	
	join HPADLPP A on (A . LPHSP# = M . MSEHSP#		
		AND A . LPMRC# = M . MSEMRC#		
		AND A . LPACCT = M . MSEPACCT)	
	join HPADLPP B on ( A . LPHSP# = B . LPHSP#		
		AND A . LPMRC# = B . LPMRC#		
		AND A . LPACCT = B . LPACCT)	
	WHERE	M . MSEHSP# = P_HSP 		
	AND M . MSEMRC# = P_MRN 		
	AND M . MSENACCT = P_ACCOUNTNUMBER;


	DECLARE CURSOR9 CURSOR FOR	
	SELECT	
		HSPNUMBER ,	
		ACCOUNTNUMBER ,	
		INSUREDLASTNAME ,	
		INSUREDFIRSTNAME ,	
		INSUREDMIDDLEINITIAL ,	
		INSUREDSEX ,	
		INSUREDRELATIONSHIP ,	
		INSUREDIDENTIFIER ,	
		INSUREDCOUNTRYCODE ,	
		INSUREDBIRTHDATE ,	
		INSURANCECERTIFICATIONNUM ,	
		INSURANCEGROUPNUMBER ,	
		GROUPNUMBER ,	
		POLICYNUMBER ,	
		EVCNUMBER ,	
		AUTHORIZATIONNUMBER ,	
		AUTHORIZEDDAYS ,	
		ISSUEDATE ,	
		INSUREDADDRESS ,	
		INSUREDCITY ,	
		INSUREDSTATE ,	
		INSUREDZIP ,	
		INSUREDZIPEXT ,	
		INSUREDAREACODE1 ,	
		INSUREDPHONENUMBER1 ,	
		INSUREDAREACODE2 ,	
		INSUREDPHONENUMBER2 ,	
		INSUREDCELLPHONE ,	
		INSURANCECOMPANYNUMBER ,
		SIGNEDOVERMEDICAREHICNUMBER ,	
		PRIORITYCODE ,	
		BILLINGADDRESS1 ,	
		BILLINGCITYSTATECOUNTRY ,	
		BILLINGZIPZIPEXTPHONE ,	
		DEDUCTIBLE ,	
		COPAY ,	
		NOLIABILITY ,	
		ELIGIBILITY ,	
		CONDITIONOFSERVICE ,	
		PRIMARYEMPSTATUS ,	
		PRIMARYEMPCODE ,	
		PRIMARYEMPNAME ,	
		PRIMARYEMPADDRESS ,	
		PRIMARYLOC , --city, stat
		PRIMARYEMPZIP ,	
		PRIMARYEMPZIPEXT ,	
		PRIMARYPHONE ,	
		SECONDARYEMPSTATUS ,	
		SECONDARYEMPCODE ,	
		SECONDARYEMPNAME ,	
		SECONDARYEMPADDRESS ,	
		SECONDARYLOC , --city,
		SECONDARYEMPZIP ,	
		SECONDARYEMPZIPEXT ,	
		SECONDARYPHONE ,	
		EFFECTIVEON ,	
		APPROVEDON ,	
		-- NOPATIENTLIABILITYFLAG , --
		AUTHORIZATIONPHONE ,	
		AUTHORIZATIONCOMPANY ,	
		AUTHORIZATIONPMTEXT ,	
		AUTHORIZATIONFLAG ,	
		VERIFICATIONDATE ,	
		VERIFICATIONFLAG ,	
		VERIFIEDBY ,	
		ATTORNEYNAME ,	
		ATTORNEYSTREET ,	
		ATTORNEYCITY ,	
		ATTORNEYSTATE ,	
		ATTORNEYZIP5 ,	
		ATTORNEYZIP4 ,	
		ATTORNEYCOUNTRYCODE ,	
		ATTORNEYPHONE ,	
		AGENTNAME ,	
		AGENTPHONE ,	
		AGENTSTREET ,	
		AGENTCITY ,	
		AGENTSTATE ,	
		AGENTZIP5 ,	
		AGENTZIP4 ,	
		AGENTCOUNTRYCODE ,	
		BILLINGCAREOFNAME ,	
		BILLINGNAME ,	
		TRACKINGNUMBER ,	
		ADJUSTERSNAME ,	
		EMPLOYEESSUPERVISOR,
		AUTHCOMPANYREPFIRSTNAME ,
		AUTHCOMPANYREPLASTNAME ,
		SERVICESAUTHORIZED ,
		EFFECTIVEDATEOFAUTH , 
		EXPIRATIONDATEOFAUTH ,
		AUTHORIZATIONSTATUS ,
		AUTHORIZATIONREMARKS,
		INSURANCECOMPANYNAME		
	FROM INSURANCES I , NHMSE01P M	
	WHERE I . HSPNUMBER = P_HSP	
		AND M . MSENACCT = P_ACCOUNTNUMBER	
		AND I . ACCOUNTNUMBER = M . MSEPACCT	
		AND I . HSPNUMBER = M . MSEHSP#	
		AND ( I . PRIORITYCODE = '1' OR I . PRIORITYCODE = '2' )	
	ORDER BY PRIORITYCODE ;
	
	OPEN CURSOR1 ;
	OPEN CURSOR2 ;
	OPEN CURSOR3 ;
	OPEN CURSOR4 ;
	OPEN CURSOR5 ;
	OPEN CURSOR6 ;
	OPEN CURSOR7 ;
	OPEN CURSOR8 ;
	OPEN CURSOR9 ;	
	OPEN CURSOR2a;
	
	END P1 ;

