/**********************************************************************/
/*                                                                    */
/* iSeries400    SLACBVDT    - STORED PROCEDURE FOR PX                */
/*                                                                    */
/*    ************************************************************    */
/*    * Perot Systems, Copyright 2003, All rights reserved(U.S.) *    */
/*    *                                                          *    */
/*    * This unpublished material is proprietary to Perot Sys.   *    */
/*    * The methods and techniques described herein are          *    */
/*    * considered trade secrets and/or confidential.            *    */
/*    * Reproduction or distribution, in whole or in part, is    *    */
/*    * forbidden except by express written permission of        *    */
/*    * Perot Systems, Inc.                                      *    */
/*    ************************************************************    */
/*                                                                    */
/**********************************************************************/
/*  Date        Programmer          Modification Description          */
/**********************************************************************/
/* 04/26/2006   Melissa Bouse       NEW STORED PROCEDURE              */
/* 11/18/2008   Deepa Raghavaraju   Add new fields for MCR rem PartA  */
/*                                   PartB Deductibles for SR49735    */
/**********************************************************************/
/* SP Definition - PACCESS.SELECTBENEFITVALDATA                       */
/*    Params     - P_HSP	- an HSP Code							  */
/*    Params     - P_MRN    - a Medical record number                 */
/*    Params     - P_ACCOUNTNUMBER	- an account number               */
/**********************************************************************/

SET PATH *LIBL ;

CREATE PROCEDURE SELECTBENEFITVALDATA (
        IN P_HSP INTEGER ,
        IN P_MRN INTEGER ,
        IN P_ACCOUNTNUMBER INTEGER )
        DYNAMIC RESULT SETS 1
        LANGUAGE SQL
        SPECIFIC SLACBVDT
        NOT DETERMINISTIC
        MODIFIES SQL DATA
        CALLED ON NULL INPUT
        SET OPTION DBGVIEW =*SOURCE
        P1 : BEGIN

		DECLARE CURSOR1 CURSOR FOR
		SELECT 
		I.PRIORITYCODE as PRIORITYCODE,
		
		MCD.MCDCPTY as MCD_PRIORITY_CODE,
		MCD.MCDCELDT as MCD_ELIGIBILITYDATE,
		MCD.MCDCPTMC as  MCD_PATIENT_HAS_MEDICARE,
		MCD.MCDCPTOI as MCD_PATIENT_HAS_OTHER_INS,
		MCD.MCDCCPAY as MCD_COPAY_AMOUNT,
		MCD.MCDCEVCN as MCD_EVC_NUMBER,
		MCD.MCDCINFF as MCD_INFO_RECEIVED_FROM,
		MCD.MCDCREMK as MCD_REMARKS,
		
		WKC.WKCCPTY as WKC_PRIORITY_CODE,
		WKC.WKCCNMNT as WKC_NAME_OF_NETWORK,
		WKC.WKCCCLMN as WKC_CLAIM_NUMBER_FOR_INCIDENT,
		WKC.WKCCADVR as WKC_CLAIM_ADDRESS_VERIFIED,
		WKC.WKCCINPH as WKC_INSURANCE_PHONE_NUMBER,
		WKC.WKCCEMPM as WKC_EMP_PREMIUM_PAID_TODATE,
		WKC.WKCCINFF as WKC_INFO_RECEIVED_FROM,
		WKC.WKCCREMK as WKC_REMARKS,
		
		GOV.GOVCPTY		AS GOV_PRIORITY_CODE,
		GOV.GOVCINFF	AS GOV_INFO_RECEIVED_FROM,
		GOV.GOVCELPH	AS GOV_ELIGIBILITY_PHONE_NUM,
		GOV.GOVCINRP	AS GOV_INS_COMPANY_REP_NAME,
		GOV.GOVCTYCV	AS GOV_TYPE_OF_COVERAGE,
		GOV.GOVCEFDI	AS GOV_EFFECTIVE_DATEOF_INSURED,
		GOV.GOVCTMDI	AS GOV_TERM_DATE_FOR_INSURED,
		GOV.GOVCDEDA	AS GOV_DEDUCTABLE_AMOUNT,
		GOV.GOVCDEMT	AS GOV_ISDEDUCTABLE_MET,
		GOV.GOVCDEAM	AS GOV_DEDUCTABLE_AMOUNT_MET,
		GOV.GOVCCOIN	AS GOV_COINSURANCE,
		GOV.GOVCOTPK	AS GOV_OUT_OF_POCKET,
		GOV.GOVCOTPM	AS GOV_IS_OUTOFPOCKET_MET,
		GOV.GOVCOTPA	AS GOV_OUTOFPOCKET_AMOUNT_MET,
		GOV.GOVCPROT	AS GOV_PERCENT_OUTOFPOCKET,
		GOV.GOVCCPAY	AS GOV_COPAY_AMOUNT,
		GOV.GOVCREMK	AS GOV_REMARKS,
		
		MCR.MCRCPTY		AS MCR_PRIORITY_CODE,
		MCR.MCRCPACV	AS MCR_PARTA_COVERAGE,
		MCR.MCRCPAED	AS MCR_PARTA_EFFECTIVE_DATE,
		MCR.MCRCPBCV	AS MCR_PARTB_COVERAGE,
		MCR.MCRCPBED	AS MCR_PARTB_EFFECTIVE_DATE,
		MCR.MCRCMHCV	AS MCR_PAT_HAS_MEDICARE_HMO_CVRG,
		MCR.MCRCMDSC	AS MCR_MEDICARE_IS_SECONDARY,
		MCR.MCRCDTLB	AS MCR_DATEOFLAST_BILL_ACTIVITY,
		MCR.MCRCRMHD	AS MCR_REM_HOSPITAL_DAYS,
		MCR.MCRCRCID	AS MCR_REM_COINSURANCE_DAYS,
		MCR.MCRCRLRD	AS MCR_REM_LIFETIME_RESERVE_DAYS,
		MCR.MCRCRSNF	AS MCR_REM_SNF_DAYS,
		MCR.MCRCRSNC	AS MCR_REM_SNF_COINS_DAYS,
		MCR.MCRCRPAD	AS MCR_REM_PART_A_DEDUCTIBLE,
		MCR.MCRCRPBD	AS MCR_REM_PART_B_DEDUCTIBLE,
		MCR.MCRCPTHS	AS MCR_PATIENT_IS_IN_HOSPICE,
		MCR.MCRCBNNV	AS MCR_BENEFICIARY_NAME_VERIFIED,
		MCR.MCRCINFF	AS MCR_INFO_RECEIVED_FROM,
		MCR.MCRCREMK	AS MCR_REMARKS,

		SLF.SLFCPTY		AS SELF_PRIORITY_CODE,
		SLF.SLFCPTMD	AS SELF_HAS_MEDICAID,
		SLF.SLFCINIF	AS SELF_INSURANCE_INFO_AVAILABLE,
		
		COM.COMCPTY		AS COM_PRIORITY_CODE,
		COM.COMCINFF	AS COM_INFO_RECEIVED_FROM,
		COM.COMCELPH	AS COM_ELIGIBILITY_PHONE_NUMBER,
		COM.COMCINRP	AS COM_INSURANCE_COMP_REP_NAME,
		COM.COMCEFDI	AS COM_EFFECTIVE_DATE_OF_INSURED,
		COM.COMCTMDI	AS COM_TERM_DATE_FOR_INSURED,
		COM.COMCSFPC	AS COM_ISSVC_FORPREEXISTING_COND,
		COM.COMCSACB	AS COM_ISSERVICEA_COVERED_BENEFIT,
		COM.COMCCAAV	AS COM_CLAIMSA_ADDRESS_VERIFIED,
		COM.COMCCOBF	AS COM_COORD_OF_BENEFITS,
		COM.COMCRCOB	AS COM_RULE_TO_DETERMINE_COB,
		COM.COMCTPPR	AS COM_TYPE_OF_PRODUCT,
		COM.COMCNPPO	AS COM_NAMEOFPPONETWORK_ORBROKER,
		COM.COMCHCPR	AS COM_HOSP_IS_CONTRACTED_PROV,
		COM.COMCACNM	AS COM_AUTO_CLAIM_NUMBER,
		COM.COMCMPCV	AS COM_AUTO_MEDPAY_COVERAGE,
		COM.COMCREMK	AS COM_REMARKS,

		CBC.CBCPTY	AS BC_PRIORITY_CODE,
		CBC.CBCCTID	AS BC_BENEFIT_CATEGORY_ID,
		CBC.CBCDEDA	AS BC_DEDUCTABLE_AMOUNT,
		CBC.CBCTMPR	AS BC_TIME_PERIOD,
		CBC.CBCDEMT	AS BC_DEDUCTABLE_MET,
		CBC.CBCDEAM	AS BC_DEDUCTABLE_METAMOUNT,
		CBC.CBCCOIN	AS BC_COINSURANCE,
		CBC.CBCOTPK	AS BC_OUT_OF_POCKET,
		CBC.CBCOTPM	AS BC_OUTOF_POCKET_MET,
		CBC.CBCOTPA	AS BC_OUTOF_POCKETMET_AMOUNT,
		CBC.CBCPROT	AS BC_PCT_AFTER_OUTOF_POCKET,
		CBC.CBCCPAY	AS BC_COPAY_AMOUNT,
		CBC.CBCWCPY	AS BC_WAIVE_COPAYIF_ADMITTED,
		CBC.CBCNMVS	AS BC_NUMBER_OFVISITS_PER_YEAR,
		CBC.CBCLFMB	AS BC_LIFETIME_MAX_BENEFIT,
		CBC.CBCLFRM	AS BC_REM_LIFETIME_VALUE,
		CBC.CBCLFVM	AS BC_REM_LIFETIME_VALUEMET,
		CBC.CBCMXBN	AS BC_MAXIMUM_BENEFIT_PERVISIT,
		CBC.CBCRMBN	AS BC_REM_BENEFIT_PERVISIT,
		CBC.CBCRMMT	AS BC_REM_BENEFIT_PERVISITMET

		from INSURANCES I
        left outer join NHADMCDCP MCD on (MCDCHSP# = I.HSPNUMBER 
			and MCDCACCT = I.ACCOUNTNUMBER  and MCDCPTY = I.PRIORITYCODE)
		left outer join NHADWKCCP WKC on (WKCCHSP# = I.HSPNUMBER 
			and WKCCACCT = I.ACCOUNTNUMBER  and WKCCPTY = I.PRIORITYCODE)
		left outer join NHADMCRCP MCR on (MCRCHSP# = I.HSPNUMBER 
			and MCRCACCT = I.ACCOUNTNUMBER  and MCRCPTY = I.PRIORITYCODE)
		left outer join NHADGOVCP GOV on (GOVCHSP# = I.HSPNUMBER 
			and GOVCACCT = I.ACCOUNTNUMBER  and GOVCPTY = I.PRIORITYCODE)
		left outer join NHADSLFCP SLF on (SLFCHSP# = I.HSPNUMBER 
			and SLFCACCT = I.ACCOUNTNUMBER  and SLFCPTY = I.PRIORITYCODE)
		left outer join NHADCOMCP COM on (COMCHSP# = I.HSPNUMBER 
			and COMCACCT = I.ACCOUNTNUMBER  and COMCPTY = I.PRIORITYCODE)
		left outer join NHADCBCP CBC on (CBCHSP# = I.HSPNUMBER 
			and CBCACCT = I.ACCOUNTNUMBER  and CBCPTY = I.PRIORITYCODE)
		WHERE I . HSPNUMBER = P_HSP
        AND I . ACCOUNTNUMBER = P_ACCOUNTNUMBER
        AND ( PRIORITYCODE = '1' OR PRIORITYCODE = '2' )
        ORDER BY PRIORITYCODE ;

	OPEN CURSOR1;
	
	END P1 ; 