--  Generate SQL 
--  Version:                   	V7R3M0 160422 
--  Generated on:              	04/21/20 06:21:02 
--  Relational Database:       	DVLA 
--  Standards Option:          	Db2 for i 
SET PATH *LIBL ; 
  
CREATE PROCEDURE SELECTALLGENDERS ( 
	IN P_FACILITYID INTEGER ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC SLALLGEND 
	NOT DETERMINISTIC 
	READS SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DBGVIEW = *SOURCE , 
	CLOSQLCSR = *ENDACTGRP , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DLYPRP = *NO , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	RDBCNNMTH = *RUW , 
	SRTSEQ = *HEX   
	P1 : BEGIN DECLARE CURSOR1 CURSOR FOR 
	SELECT 0 AS OID ,		 
	TRIM ( QTKEY ) AS CODE ,		 
	CASE QTSEXD		WHEN 'UNKNOW' THEN 'UNKNOWN'		 
	ELSE TRIM ( QTSEXD )		 
	END AS DESCRIPTION		 
	FROM HPADQTSX		 
	WHERE QTHSP# = P_FACILITYID			 
	UNION ALL		
	SELECT 0 AS OID ,		'' AS CODE ,		
	'' AS DESCRIPTION		 
	FROM SYSIBM . SYSDUMMY1			
	ORDER BY CODE ; 
	OPEN CURSOR1 ; 
	END P1  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE SLALLGEND 
TO RMTGRPPRF WITH GRANT OPTION ; 
  
